### ISSUE TITLE
General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [craftcms/feed-me#1037]
### Description
There is a multisite - 6 separate websites which use the same list of products.
We use 1 feed me job which is used to import about 5700 products regularly. This feed me job is paginated - 30 products per 1 page. Also our job has enabled setting `Disable missing elements globally`. The setting `runQueueAutomatically` in config file general.php is set to `false` and a cronjob to run the queue from the console command was added.

On the server a shared MySQL server is used and no way to change MySQL setting `wait_timeout` which has a value `300`, so we are limited to 5 minutes for one MySQL process.

When the last page to import products has processed, feed me starts the process to disable missing element for all websites and it takes about 11 minutes to finish this. It's too mush than MySQL setting `wait_timeout`  is allow.

As the result:
- The product import works well and all unnecessary products are disabled.
- But the job itself is stuck in the queue with the progress at 0% and will the import will be restarted after some time.
- Also file console.log contains the error `PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in vendor/yiisoft/yii2/db/Command.php:1299`

Is there some way to fix this without changing MySQL server settings?

### Additional info

- Craft CMS version: 3.6.12
- Feed Me version: 4.3.6
- PHP version: 7.4.23
- Database driver & version: MySQL 5.7.33
- Other plugins & versions: Craft Commerce Pro 3.2.17.4

**Comment by AMandujano-BI** [comment]
Did you manage to solve this issue?

**Comment by angrybrad** [comment]
The "proper" fix is to adjust the MySQL server settings, but on a shared hosting environment, that's probably not feasible.

I'd suggest trying to process the feed in smaller paginated batches to see if that helps - or bump the web & database server specs so that things complete faster in general (thus reducing the chance you hit timeout settings).
