### ISSUE TITLE
Update to Datahelper.php in 4.4.0 introduced new bug when values are arrays (e.g. category fields)

### ISSUE THREAD

**Issue by kristiansp** [craftcms/feed-me#1041]
### Description
The update done for v 4.4.0 to avoid stripping values of leading zeros introduced a new bug when the values being compared are arrays, which happens when comparing e.g. category fields. The comparison will then error out, as `mb_strlen()` is passed arrays, and only accepts strings.

The reason is the checks with `mb_strlen()` that's being done in the new `_compareSimpleValues()` method in [DataHelper.php line 317](https://github.com/craftcms/feed-me/commit/704d511e85adba8caca7a90644c29e78b0a3490a#diff-00b65bfbafca7d94fc79ef28c99cb363e43a28e3e7a56c1822e7b447e41055c1R317).

It needs to be adjusted so that it only checks the length if the values passed in are actually strings.

### Steps to reproduce

1. Upgrade to v 4.4.0
2. Run feed that compares array values (e.g. category fields)

### Additional info

- Craft CMS version: 3.7
- Feed Me version: 4.4.0
- PHP version:
- Database driver & version:
- Other plugins & versions:

**Comment by green17** [comment]
We have got this happing to us now too. Same problem I think category fields.

**Comment by angrybrad** [comment]
@kristiansp  @green17  

Can you `vendor/craftcms/feed-me/src/helpers/DataHelper.php`, find `_compareSimpleValues`, replace it with this and verify that fixes it for you?

```
private static function _compareSimpleValues($fields, $key, $firstValue, $secondValue): bool
    {
        /** @noinspection TypeUnsafeComparisonInspection */
        // Should probably do a strict check, but doing this for backwards compatibility.
        if (Hash::check($fields, $key) && ($firstValue == $secondValue)) {
            // If this is a string, check the lengths
            if (is_string($firstValue) && is_string($secondValue)) {
                // String length comparison to take into account "637" and "0637"
                if (mb_strlen($firstValue) == mb_strlen($secondValue)) {
                    return true;
                }

                return false;
            }

            // An array, but loosely equal
            return true;
        }

        // Didn't
        return false;
    }
```

**Comment by angrybrad** [comment]
Cut a 4.4.1.1 release with this fixed based on feedback from https://github.com/craftcms/feed-me/issues/1067
