### ISSUE TITLE
Argument 1 passed to craft\web\twig\variables\Cp::field() must be of the type string, null given

### ISSUE THREAD

**Issue by nickwanhere** [craftcms/feed-me#1065]
### Description
Just upgraded to latest Craft CMS and Feedme. Error prevent me from creating new feed.

### Steps to reproduce
1. Go to Feedme
2. Click create new

### Additional info

- Craft CMS version: 3.7.24
- Feed Me version: 4.4.0 
- PHP version: 7.4.18
- Database driver & version: MySQL 5.7.34

If edit templates/feeds/_edit.html
from 
`    {{ forms.field({
        label: "Import strategy"|t('feed-me'),
        instructions: 'Choose what happens when this feed is run again.'|t('feed-me'),
        id: 'duplicateHandle',
    }) }}`

to 
`    {{ forms.field({
        label: "Import strategy"|t('feed-me'),
        instructions: 'Choose what happens when this feed is run again.'|t('feed-me'),
        id: 'duplicateHandle',
    },'') }}`

then it could show normally.

**Comment by russback** [comment]
+1 for this on 4.4.0 after upgrading to Craft 3.7.24 today
