### ISSUE TITLE
feed-me 4.4.1 breaks import of entries with assets

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/feed-me#1067]
### Description

This commit breaks import of entries with assets: https://github.com/craftcms/feed-me/commit/704d511e85adba8caca7a90644c29e78b0a3490a

I have defined an import of entries in which assets are used. During the import, you'll get the following error message:

`Error: mb_strlen(): Argument #1 ($string) must be of type string, array given - DataHelper.php: 319. `

Looking at the passed variables, I can see that in fact an array is passed for `$firstValue` and `$secondValue`, e.g.

```
$key: "objectImages"
$firstValue:  ["49864"]
$secondValue:  ["49864"]
```

### Steps to reproduce

1. Create an import of entries
2. Map a field to an asset field
3. Import

### Additional info

- Craft CMS version: 3.7.24
- Feed Me version: 4.4.1
- PHP version: 8.0

**Comment by sparkalow** [comment]
I'm see the same issue unrelated to asset importing. The bug occurs for me when importing matrix or array data or anything other than simple strings.

The below in `helpers/DataHelper.php` is comparing string values with mb_strlen but the data sent to this method is not guaranteed to be a string.

```
 return Hash::check($fields, $key) && ($firstValue == $secondValue && mb_strlen($firstValue) === mb_strlen($secondValue));
```

**Comment by angrybrad** [comment]
@sparkalow @dgsiegel 

Can you `vendor/craftcms/feed-me/src/helpers/DataHelper.php`, find `_compareSimpleValues`, replace it with this and verify that fixes it for you?

```
private static function _compareSimpleValues($fields, $key, $firstValue, $secondValue): bool
{
    /** @noinspection TypeUnsafeComparisonInspection */
    // Should probably do a strict check, but doing this for backwards compatibility.
    if (Hash::check($fields, $key) && ($firstValue == $secondValue)) {
        // If this is a string, check the lengths
        if (is_string($firstValue) && is_string($secondValue)) {
            // String length comparison to take into account "637" and "0637"
            if (mb_strlen($firstValue) == mb_strlen($secondValue)) {
                return true;
            }

            return false;
        }

        // An array, but loosely equal
        return true;
    }

    // Didn't match
    return false;
}
```

**Comment by sparkalow** [comment]
@angrybrad  I can confirm that fix works for my case.

**Comment by angrybrad** [comment]
Thanks for the feedback... just cut a 4.4.1.1 release with this fix.

**Comment by green17** [comment]
@angrybrad perfect thanks so much for the quick fix, I can confirm that works for us too.
