### ISSUE TITLE
Wrong type error in entries field (mb_strlen() in DataHelper.php)

### ISSUE THREAD

**Issue by floatingbits** [craftcms/feed-me#1071]
### Description
When using an entries field, you'll get the following error:

> mb_strlen(): Argument #1 ($string) must be of type string, array given - DataHelper.php: 317

Seems to be an issue in 4.4.1 introduced by commit 704d511

### Steps to reproduce

1. Set up feed using an entries field
2. Maybe you need to run it twice to execute update and comparison code.

### Additional info

- Craft CMS version: 3.7.24
- Feed Me version: 4.4.1

I'm gonna write a fix + pull request...

**Comment by angrybrad** [comment]
This is resolved in 4.4.1.1. https://github.com/craftcms/feed-me/blob/develop/CHANGELOG.md#4411---2021-12-06
