### ISSUE TITLE
Importing multiple Assets into one Field with JSON

### ISSUE THREAD

**Issue by NicoUnderTheStairs** [craftcms/feed-me#1076]
# Importing multiple Assets into one Field with JSON

### Description

I want to import more than only one asset into an asset-field, but I can't find a way for my usecase.
My Entry has an Assets Field, that allows multiple assets/files like a gallery.
Only by selecting the e.g. picture_1_filename, i can import only the first image for the gallery.

I can't use the way it's described in the [docs](https://docs.craftcms.com/feed-me/v4/guides/importing-assets.html#example-feed-data), because I still need the other data and I can't have multiple feeds.

The following JSON, which is provided by my client, is structured as followed:

```
[
    {
      "version": "IDX3.01",
      "sender_id": "immotools v1.99",
      "object_category": "APPT",
      "object_type": 1,
      "offer_type": "SALE",
      "ref_property": "a",
      "ref_house": "h",
      "ref_object": 2,
      "picture_1_filename": "img1.png",
      "picture_2_filename": "img2.png",
      "picture_3_filename": "img3.png",
      "picture_4_filename": "img4.png",
      "picture_5_filename": "img5.png",
      "picture_6_filename": "img6.png",
      "picture_7_filename": "img7.png",
      "picture_8_filename": "img8.png",
      "picture_9_filename": "img9.png",
      "picture_10_filename": "img10.png",
    }
]

```

Is there a solution for my problem?

### Additional info

My FeedMe configuration:
![Bildschirmfoto 2021-12-17 um 16 34 39](https://user-images.githubusercontent.com/88322851/146569139-fdb8b4ec-5419-4087-8e94-11f4640991e3.png)
![Bildschirmfoto 2021-12-17 um 16 34 55](https://user-images.githubusercontent.com/88322851/146569183-081efeef-c6a1-4466-b101-8917875b870f.png)

- Craft CMS version: 3.7.25.1
- Feed Me version: 4.4.1.1
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Other plugins & versions: Super Table: 2.7.0

**Comment by kristiansp** [comment]
I think you would need to change it to something like this, otherwise you would ask Feed Me to map 10 different feed items to the same field:

```
[
    {
      "version": "IDX3.01",
      "sender_id": "immotools v1.99",
      "object_category": "APPT",
      "object_type": 1,
      "offer_type": "SALE",
      "ref_property": "a",
      "ref_house": "h",
      "ref_object": 2,
      "picture_filename": {
              "img1.png",
              "img2.png",
              ….
          }
    }
]
```

**Comment by kristiansp** [comment]
If you can’t control your source feed, you would have to use the Feed Me events to combine them to a list of assets to import. If you need any pointers, I can help you out.
