### ISSUE TITLE
Create entries using slug as data provided.

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/feed-me#1077]
### Description
I have a section where entries have can have 1 or more entries and categories referenced.

I thought checking the box for "Create entries if they do not exist" and selecting "Slug" from the drop down for "Data provided for this entry" would create an entry if it didn't exist using the selected feed element as the check. If the entry does exist then it is populated on new/updated entries.

Changing "Slug" to "Title" does create the entry if it doesn't exist (what I was trying to achieve).

### Steps to reproduce

1. Go through steps to create a new feed
2. Set "Data provided for this entry" to "Slug"
3. Check box to "Create entries if they do not exist"

### Additional info

- Craft CMS version: 3.7.25.1
- Feed Me version: 4.4.0
- PHP version: 7.4

**Comment by i-just** [comment]
Hi, thanks for getting in touch and apologies for the late response. Feed Me is only able to create new related Categories and Entries if they’re mapped by `title` and related Users if they’re mapped by `email`. 

I just raised a PR to hide the “Create <elements> if they do not exist” if the matching is done by any other attribute.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1341 for the next v4 and v5 releases. Thanks!
