### ISSUE TITLE
Category from title '0' will not be created

### ISSUE THREAD

**Issue by bencresty** [craftcms/feed-me#1102]
### Description

When importing data categories should be created from a data string. This works perfectly, except when the title in the title field inside the json data is literally "0". Data with title "0" seems to be skipped by Feed-me, so instead of creating a new category with that string as title ("0") no category will be created at all.

This issue isn't the case in Craft itself as it's perfectly possible to just create a category item with title "0" when done manually. So this is an issue in feed-me.

feed me:
![image](https://user-images.githubusercontent.com/69322733/156846615-0263328a-7242-4f09-bf1a-124e0cfb9212.png)

data:
``` text
[
   {
       "spriteKey": "0"
   }
]
```

### Steps to reproduce

See above

### Additional info

- Craft CMS version: 3.7.36
- Feed Me version: 4.4.1.1
- PHP version: 8.x
- Database driver & version: mysql/mariadb

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1339 and will be included in the next v5 release.
