### ISSUE TITLE
Error query for default value field

### ISSUE THREAD

**Issue by ipatate** [craftcms/feed-me#1106]
### Description

I select a default value for a field imported but apparently the query use 
```{"status":null,"groupId":5,"limit":"1","where":["=","slug",["10100"]]}```

slug with a id in where condition !

### Steps to reproduce

1. select a default value for a field
2. the field use slug for corresponding with value imported
3. import json with a null value for this field

### Additional info

- Craft CMS version: 3.7.37
- Feed Me version: 4.4.2
- PHP version: 8.0.16
- Database driver & version:
- Other plugins & versions:

**Comment by ipatate** [comment]
<img width="1065" alt="Screenshot 2022-03-17 at 13 41 36" src="https://user-images.githubusercontent.com/46760/158810562-6fa09c89-4258-4101-a888-500536f372a5.png">

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1229

**Comment by brandonkelly** [comment]
Feed Me 4.6.0 (Craft 3) and 5.1.0 (Craft 4) have been released with the fix for this.
