### ISSUE TITLE
Push file to import

### ISSUE THREAD

**Issue by arentsen** [craftcms/feed-me#1112]
I would like to know if it is possible for our client to push a json file with each change in their system to import in FeedMe.

**Comment by kristiansp** [comment]
You mean for the update to be triggered externally, whenever they have a change in the JSON? You could set up a custom controller action, and make it accessible from a URL, to trigger Feed Me to run, and go fetch the JSON file. This could be triggered manually when there's a change, or something on the source side could ping it when the JSON is changed. You could also set up a cronjob to run the feed regularly, as if there are no changes, it will just skip items that are not changed, and be done in no time. This is what I do to sync external content.

**Comment by arentsen** [comment]
Yes, this is correct. Actually, I don't remember exactly why I wanted a JSON file to be pushed. I use a cronjob instead, but it would save quite a bit of trafic since the cronjob activates every hour and there is quite some data. At the time, Feed Me would clog up the queue, but it's better now. It also means there is no need of triggering scripts on the database end that I don't control. Thanks for your response!
