### ISSUE TITLE
Unable to use the Save and Save & Continue buttons on the feed page

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/feed-me#1116]
### Description
After a feed has been created, I have tried to edit some information. However the save buttons do not do anything, and I see the following error in the console:

```log
Uncaught TypeError: can't access property "craft\\elements\\Entry", Craft.FeedMe.elementTypes is undefined
[feed-me.js:3749:13](https://slayed.local/cpresources/2f32c142/js/feed-me.js?v=1650316827)
```

### Steps to reproduce

1. Create a feed
2. Go to the plugin's main screen and then try to return to the feed's page and save.

### Additional info

- Craft version: 4 beta 4
- PHP version: 8.1.3
- Database driver & version: MySQL 8.0.26
- Plugins & versions:
Feed Me | 5.0.0-beta.1
Ray | 2.0
Redactor | 3.0.0-beta.2

**Comment by kristiansp** [comment]
This was fixed in a recent update, if you update to the latest version of Feed Me, the issue should be resolved.

**Comment by i-just** [comment]
Thank you for reporting @mauricioarangoosorio, and thank you for replying @kristiansp!
