### ISSUE TITLE
New users are imported as active, not pending?

### ISSUE THREAD

**Issue by remcoov** [craftcms/feed-me#1119]
### Description
I have a JSON feed, which imports users. I'd like these users to import as **pending**, rather than **active**.

I have both status settings set to: _don't import_.

When I change these settings to _use default value_ and _pending_, they indeed are created as pending, but when the admin/superuser activates these users in craft, they are overwritten to pending during the next cron import.

What am i missing here?

### Additional info

- Craft version: Craft CMS 3.7.38 Pro
- PHP version: 7.4.24
- Database driver & version: MySQL 5.7.33
- Plugins & versions: Feed Me | 4.4.3

**Comment by olivierbon** [comment]
If you uncheck _Update existing elements_ in your feed settings, existing users will not be updated.

**Comment by remcoov** [comment]
I understand that. But that means all other new information is not updated as well, which obviously isn't desirable.
