### ISSUE TITLE
[5.0.0-beta.2] Setting unknown property: craft\\elements\\db\\EntryQuery::enabledForSite

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/feed-me#1126]
### Description
When trying to import commerce products and linking an entry field you are getting the following error
`Setting unknown property: craft\\elements\\db\\EntryQuery::enabledForSite - Component.php: 209`

### Additional info

- Craft version: 4.0.0-RC2
- PHP version: 8.0.8
- Database driver & version: MySQL 8.0.26
- Plugins & versions: 5.0.0-beta.2

**Comment by nikolenko-dmitriy** [comment]
Hello!

Was able to reproduce this as well. For me this happend when I try to set the `Default Entry` for an entry field on the last `Map` step in a feed settings.

![2022-09-07_18-04](https://user-images.githubusercontent.com/65535954/188912554-741c0d21-b236-4fc0-a06c-14231895c035.png)


### Additional info

- Craft version: 4.2.1.1
- PHP version: 8.1.10
- FeedMe Version: 5.0.4

**Comment by olivierbon** [comment]
Thanks @nikolenko-dmitriy! I was able to replicate this time. [The fix](https://github.com/craftcms/feed-me/commit/42eb3ce6d6b914017cff41e76f605687b4f417b9) will be in next release.

**Comment by martinherweg** [comment]
@olivierbon Is there a new release scheduled? Would be great to have this fixed.

**Comment by aaronmclayton** [comment]
@olivierbon I saw the release for January for 5.0.5 fixed this. Does this also apply for `craft\elements\db\CategoryQuery::enabledForSite`?
