### ISSUE TITLE
Cannot assign array to property craft\feedme\models\Settings::$enabledTabs of type string

### ISSUE THREAD

**Issue by SanboKyo** [craftcms/feed-me#1131]
After Upgrading Craft 4.0.0 ... Feed Me 5.0.0, I run `php craft migrate/all` and get the error `Cannot assign array to property craft\feedme\models\Settings::$enabledTabs of type string` - same in control panel.

### Additional info

- Craft version: 4.0.0
- PHP version: 8.0.18
- Database: MySQL 8
- Feed Me version: 5.0.0
- Plugins versions: ...

**Comment by brandonkelly** [comment]
Thanks for reporting! Feed Me 5.0.1 is out now with a fix for this.

**Comment by SanboKyo** [comment]
Thanks, I upgraded it, but now I get 

```
Exception 'TypeError' with message 'Cannot assign bool to property craft\feedme\models\Settings::$parseTwig of type array'

in /html/craft_w_commerce/vendor/yiisoft/yii2/base/Model.php:741
```

**Comment by brandonkelly** [comment]
Can you please post that as a new issue?
