### ISSUE TITLE
getGroups type exception for Solo

### ISSUE THREAD

**Issue by ishitatsuyuki** [craftcms/feed-me#1133]
### Description

If the user is running Craft Solo (free edition), the plugin throws type exception and does not work.

### Steps to reproduce

1. Install Craft Solo
2. Install Feed Me
3. Create some element type
4. Set up any feed entry
5. Press "Save & Continue"
6. Observe 500 and error log

```
craft\\feedme\\elements\\User::getGroups(): Return value must be of type array, bool returned at /app/vendor/craftcms/feed-me/src/elements/User.php:91)
```

### Additional info

- Craft version: 4.0.1
- PHP version: 8.1.4
- Database driver & version: pdo_pgsql version 8.1.4
- Plugins & versions: Feed Me 5.0.1

**Comment by angrybrad** [comment]
Just released [5.0.2](https://github.com/craftcms/feed-me/releases/tag/5.0.2) with a fixed for this.
