### ISSUE TITLE
Get "Undefined offset: 1", cant start mapping 

### ISSUE THREAD

**Issue by timohinze** [craftcms/feed-me#1148]
### Description
After selecting the primary element and clicking "save & continue" i get "undefined offset: 1"

### Steps to reproduce

1. Add new feed,
2. Select Json Feed
3. Select Root Element

### Additional info

- Craft version: Craft CMS 3.7.43
- PHP version:  7.4.29
- Database driver & version: MySQL 5.7.38 (Linux 4.15.0-177-generic)
- Plugins & versions:
Element API | 2.8.5
Feed Me | 4.5.3
Redactor | 2.10.8

### Error

yii\base\ErrorException: Undefined offset: 1 in /var/www/project/vendor/craftcms/feed-me/src/web/twig/variables/FeedMeVariable.php:147
Stack trace:
#0 /var/www/project/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError()
#1 /var/www/project/vendor/craftcms/feed-me/src/web/twig/variables/FeedMeVariable.php(147): craft\web\ErrorHandler->handleError()
#2 /var/www/project/vendor/craftcms/feed-me/src/web/twig/variables/FeedMeVariable.php(204): craft\feedme\web\twig\variables\FeedMeVariable->getCategorySourcesByField()
#3 /var/www/project/vendor/twig/twig/src/Extension/CoreExtension.php(1566): craft\feedme\web\twig\variables\FeedMeVariable->getElementLayoutByField()
#4 /var/www/project/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#5 /var/www/project/storage/runtime/compiled_templates/e8/e853c8b2b124aed547eaeb48987dd9edef3819daaa6dc77c746761b472ed320a.php(58): craft\helpers\Template::attribute()
#6 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_eb08718d09324c9c9f2b2bfaa395b802b2bb832dc1d9eff71ec8be6b2fc0c797->doDisplay()
#7 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#8 /var/www/project/storage/runtime/compiled_templates/c3/c3eecb365547b2065513f764607623c8127af3ecf7d259d4c10f77e7286f1da3.php(246): Twig\Template->display()
#9 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_87fcc9cbe98ab503710e3e1d5c8b5ae29a54c50cb01fb0ebd6db02c1140ffd01->doDisplay()
#10 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#11 /var/www/project/storage/runtime/compiled_templates/83/83d8f7795810b19e3d28b0402b1fbee42e97f5ab9107efbd67222db3a0975bdd.php(169): Twig\Template->display()
#12 /var/www/project/vendor/twig/twig/src/Template.php(182): __TwigTemplate_fe9be6227dd116b00b994633ac20ddcae1a054e1daa1e9e582101be9d17f6719->block_content()
#13 /var/www/project/storage/runtime/compiled_templates/13/13e3ddfeb76f0e67e6348a1912815e43d4a0de870a024a860783cddee50f131d.php(535): Twig\Template->displayBlock()
#14 /var/www/project/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e29d17817e537949f542b6d41cf821346677704106a9d9cca82e3a1d6969d9b3->block_main()
#15 /var/www/project/storage/runtime/compiled_templates/13/13e3ddfeb76f0e67e6348a1912815e43d4a0de870a024a860783cddee50f131d.php(346): Twig\Template->displayBlock()
#16 /var/www/project/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e29d17817e537949f542b6d41cf821346677704106a9d9cca82e3a1d6969d9b3->block_body()
#17 /var/www/project/storage/runtime/compiled_templates/0c/0cf42cbce207370218b338fe20d1ac4659a70acdc960c40885d0a53b0bc0b819.php(96): Twig\Template->displayBlock()
#18 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2ddac204d4c7659f6d8ce5aae248140e49e893db415c80b9bbc3b0c84d853fcf->doDisplay()
#19 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#20 /var/www/project/storage/runtime/compiled_templates/e2/e2dd3a8acb21a7520fc30f57223202c7fd9153db6e3d00e227762c87fdbedf03.php(56): Twig\Template->display()
#21 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_268cb78d1584eae191751b9f8287497e91105728d69ae8ff72ad000f6bbaa8b4->doDisplay()
#22 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#23 /var/www/project/storage/runtime/compiled_templates/13/13e3ddfeb76f0e67e6348a1912815e43d4a0de870a024a860783cddee50f131d.php(165): Twig\Template->display()
#24 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e29d17817e537949f542b6d41cf821346677704106a9d9cca82e3a1d6969d9b3->doDisplay()
#25 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#26 /var/www/project/storage/runtime/compiled_templates/cc/cc26107e09c52bf766a7659801340df095c401fc18c189229baf35f8d2359016.php(57): Twig\Template->display()
#27 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0c96bc9d6f44b03af368c52c02a1e004f59a7821d4ca01621cc586820844ce82->doDisplay()
#28 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#29 /var/www/project/storage/runtime/compiled_templates/83/83d8f7795810b19e3d28b0402b1fbee42e97f5ab9107efbd67222db3a0975bdd.php(79): Twig\Template->display()
#30 /var/www/project/vendor/twig/twig/src/Template.php(405): __TwigTemplate_fe9be6227dd116b00b994633ac20ddcae1a054e1daa1e9e582101be9d17f6719->doDisplay()
#31 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#32 /var/www/project/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#33 /var/www/project/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#34 /var/www/project/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#35 /var/www/project/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#36 /var/www/project/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#37 /var/www/project/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate()
#38 /var/www/project/vendor/craftcms/feed-me/src/controllers/FeedsController.php(104): craft\web\Controller->renderTemplate()
#39 [internal function]: craft\feedme\controllers\FeedsController->actionMapFeed()
#40 /var/www/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#41 /var/www/project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#42 /var/www/project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#43 /var/www/project/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#44 /var/www/project/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#45 /var/www/project/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#46 /var/www/project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#47 /var/www/project/web/index.php(12): yii\base\Application->run()
#48 {main}

**Comment by kristiansp** [comment]
Could you post a sample JSON?
