### ISSUE TITLE
Unable to import Fullname of users

### ISSUE THREAD

**Issue by tinybeans** [craftcms/feed-me#1152]
### Description

I tried to import users, but there is no fullname field in the User Fields section.

<img width="1432" alt="CleanShot-2022-06-09_11 48 45" src="https://user-images.githubusercontent.com/181721/172736379-7d6a12b0-7865-4882-b43d-08b6689e0b3f.png">

### Steps to reproduce

1. Create a new feed 
2. Choose User as Element Type
3. Save & Continue

### Additional info

- Craft version: 4.0.4
- PHP version: 8.0.17
- Database driver & version: MySQL 8.0.25
- Plugins & versions: Feed Me 5.0.4

**Comment by angrybrad** [comment]
resolved via https://github.com/craftcms/feed-me/pull/1235
