### ISSUE TITLE
Asset import with filename from path - filename cannot be used as unique identifier

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/feed-me#1159]
### Description
When importing images, I leave the "Filename" field blank. However, I want to use the system-assigned filename generated from the path as a unique identifier. But this is not possible, because the following error is triggered: 
Unable to match an existing element. Have you set a unique identifier for ["filename"]? Make sure you are also mapping this in your feed and it has a value. - Element.php: 172.

### Steps to reproduce

1. Set up feed to import assets with strategy create new ans update existing
2. Map URL to image path and leave filename to don't import
3. Set unique identifier to "Filename"
4. run feed
5. Look in Logs

### Additional info

- Craft version: 4.0.4
- PHP version: 8.0.18
- Plugin version: 5.0.4

**Comment by adrienpicard** [comment]
Facing this bug today too.

I had to prep my feed with an extra filename field (using `\craft\helpers\Assets::prepareAssetName`) in order to make it work.

**Additional info**
- Craft version: 4.4.0
- Plugin version: 5.0.5
- PHP version: 8.2.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. This is working as expected. As the error says, `Make sure you are also mapping this in your feed, and it has a value.`. The unique identifier is what matches the data from your feed with the data in the database. We can’t do the matching if the unique identifier data is not in your feed. Here’s how it’s explained in the documentation: https://docs.craftcms.com/feed-me/v4/feature-tour/field-mapping.html#unique-identifiers. Hope this helps!
