### ISSUE TITLE
dataDelimiter is not taken into account during asset import

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/feed-me#1160]
### Description
When importing assets with absolute paths in a cell separated by a dataDelimiter, the path is not recognized because the explode with the dataDelimiter does not work.
We have tested this with JSON, CSV and Google Sheet. In the config file we have defined the dataDelimiter.

Asset error: https://exped.rokka.io/product_teaser-500/options-dpr-2/aed85416d64dda104297604357e59765b743de87/Comfort_Wmns_frontal_0.png-|||-https://exped.rokka.io/product_teaser-500/options-dpr-2/52c456c6faa970c9cd3c313f253b2abc733f4d08/Comfort_-5_Wmns.png - fopen(https://exped.rokka.io/product_teaser-500/options-dpr-2/aed85416d64dda104297604357e59765b743de87/Comfort_Wmns_frontal_0.png-|||-https://exped.rokka.io/product_teaser-500/options-dpr-2/52c456c6faa970c9cd3c313f253b2abc733f4d08/Comfort_-5_Wmns.png): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

### Steps to reproduce

1. Create a CSV, JSON or Google Sheet file with the columns Title and Path
2. Add two absollute image paths and separate them with the defined dataDelimiter. We have tested the following delimiters: |, -|-, -|||-
3. Create a feed with strategy create new and update existing
4. Map Title and Path
5. Set unique identifier to Title
6. Import the feed

### Additional info

- Craft version: 4.0.4
- PHP version: 8.0.18
- Plugins & versions: 5.0.4

**Comment by rene-haefliger** [comment]
Any news on this?

**Comment by i-just** [comment]
Hi, thanks for getting in touch and apologies for the delayed response. I just tested this with the latest Feed Me v4 and v5 and in both cases it works as expected. I'm going to close this now, but if you're still experiencing the issue, please let us know.
