### ISSUE TITLE
Issue with tables for Commerce Variants

### ISSUE THREAD

**Issue by CharlieGentle** [craftcms/feed-me#1168]
Hi, I'm trying to add support for Feed Me to a custom field type in a plugin. It works ok when added to Entries and Products but when I move it to a Variant it stops working. In trying to debug this I think I've found it shares the same issue as Table field types do on Variants. The _parseVariants function fails to parse the table columns and doesn't get fields from $fieldInfo.

### Steps to reproduce

1. Create Commerce Product with variants
2. Add table filed type to the variants
3. Create feed and map data to the table field
4. Run feed, variants will not be updated with the mapped data.

### Additional info

- Craft version: 4.1.0.2
- PHP version: 8.0.20
- Plugins & versions: Feed Me 5.0.4, Craft Commerce 4.0.4

**Comment by samuelbirch** [comment]
Any updates on this?

**Comment by CharlieGentle** [comment]
[Pull request](https://github.com/craftcms/feed-me/pull/1181) submitted to fix this issue.

**Comment by robzor** [comment]
+1 to this issue, it is a major issue with an upcoming critical data import 

@angrybrad do you have any time to have a look at this?

**Comment by bymayo** [comment]
+1 also

Similar related issue posted 2 years ago https://github.com/craftcms/feed-me/issues/464

**Comment by angrybrad** [comment]
Resolved for the next v4 and v5 releases via https://github.com/craftcms/feed-me/pull/1268
