### ISSUE TITLE
Field type entry does not get saved if entry is from another website

### ISSUE THREAD

**Issue by yingban** [craftcms/feed-me#1174]
### Description

Hi, 
i am trying to import data to create entries in a website B.
Each entry has a relation to another entry from another website A (I am using the ID as data provided).
Also, both websites are not in the same group.

It seems that it does not work with a website from another group.
In my case the website A is like the main website, and the other websites are like branches, who can have contact data if they can sell an offer which is defined in the main website.

### Steps to reproduce

1. Create 2 websites in two different group
2. Create a feed a relation between different kind of entries

### Additional info

- Craft version: 4.2.0.2
- PHP version: 8.0.21
- Database driver & version: MySQL 10.3.35
- Plugins & versions: FeedMe 5.0.4

**Comment by i-just** [comment]
Hi @yingban, thanks for reaching out. I'm not 100% sure I understand your example. You have two sites using the same installation of Craft: website A and website B. You have a section in entries. Is that section enabled for website A and website B? Or are you using one section for website A and another for website B?

If you are using the same section for websites A and B, then another option to achieve what you're after could be to set the propagation method to "Let each entry choose which sites it should be saved to". Then you can choose which entries you create for website A should also be present on website B.

If you are using different sections for website A and website B, could you please clarify what you mean by "I am using the ID as data provided"? Are you saying you have "Entry ID" selected under "Set a unique identifier to match against existing elements", or did I misunderstand that part?

**Comment by i-just** [comment]
I think I may have got it all wrong. Is it that the data is not imported to the entry type field on website B, and you're using entry ID to map the data from your feed to the field, similar to this:
<img width="2279" alt="Screenshot 2023-01-26 at 15 55 40" src="https://user-images.githubusercontent.com/4500340/214884184-e70e88e3-5306-4c82-843d-085ccf55a2c0.png">

**Comment by yingban** [comment]
Hi @i-just 

Thanks getting back to me.
I am using two different sections for website A and B, and the related Entry ID is coming from website A when importing content into website B.

But you can close the issue as we decided to stop the import, the client will have to fill in content manually.
