### ISSUE TITLE
Feedme is creating new entries instead of filling in the supertable rows

### ISSUE THREAD

**Issue by Radu033** [craftcms/feed-me#1175]
I have a small API that delivers 3 text inputs and 1 image.

The structure of the JSON is the following.

`
"result":[

>>>> {

>>>>>"year":"2007",
>>>>>"title":"Title of the item, 2007", 
>>>>>"imageSize":"28 x 22 cm (11 x 8 2/3 in)",
>>>>>"imageUrls":["https://website/api/v1.0/types/works/entities/9c5e3e73-df00-4833-9987-9dfc11163956/files/be4f5155-52f1-45b8-aace-0d6fbb75e048"]
>>>>>},
{
>>>>>"year":"2007",
>>>>>"title":"Title of the item 2, 2007", 
>>>>>"imageSize":"28 x 22 cm (11 x 8 2/3 in)","imageUrls":["https://website/api/v1.0/types/works/entities/9c5e3e73-df00-4833-9987-9dfc11163956/files/be4f5155-52f1-45b8-aace-0d6fbb75e048"]
>>>>>}.......]`

These are my feedme settings 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/6954983/184127027-0c304a83-7162-4fea-9f1f-26f0abbf9550.png">

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/6954983/184127254-a4c9aaea-345c-4103-84e7-22855e9b5535.png">

Now Feedme instead of populating my Supertable "Prints" with 20 rows (the size of array in JSON) is creating 20 Entries with 1 row insead the super table each.

How can I create 20 rows of super table inside 1 single page from this JSON?

### Additional info

- Craft version: 4.2.1.1
- PHP version: 8.1
- Plugins & versions: Craft commerce 4.1.0, Feedme 5.0.4, Super table 3.0.0

**Comment by i-just** [comment]
Hi, thanks for reaching out. Is that your entire json feed? If it is, each object will be treated as a new entry. If you want the `results` to be applied to a single entry, then your json structure needs to nest the `results` in an object that indicates an entry first. 

For example:
```
{
   "entries": {
      "title": "My entry",
      "result":[
         {
            "year":"2007",
            "title":"Title of the item, 2007",
            "imageSize":"28 x 22 cm (11 x 8 2/3 in)",
            "imageUrls":[
               "https://website/api/v1.0/types/works/entities/9c5e3e73-df00-4833-9987-9dfc11163956/files/be4f5155-52f1-45b8-aace-0d6fbb75e048"
            ]
         },
         {
            "year":"2007",
            "title":"Title of the item 2, 2007",
            "imageSize":"28 x 22 cm (11 x 8 2/3 in)",
            "imageUrls":[
               "https://website/api/v1.0/types/works/entities/9c5e3e73-df00-4833-9987-9dfc11163956/files/be4f5155-52f1-45b8-aace-0d6fbb75e048"
            ]
         }
      ]
   }
}
```

You can then choose your primary element on the second screen:
<img width="692" alt="Screenshot 2023-01-26 at 15 05 30" src="https://user-images.githubusercontent.com/4500340/214871982-5dfcb471-abb3-4691-a493-3834e7bf0177.png">

And map your super table fields on the third one:
<img width="2331" alt="Screenshot 2023-01-26 at 15 07 36" src="https://user-images.githubusercontent.com/4500340/214872096-d8d9ba87-f2cf-4e57-ad56-d843b37dadd2.png">

Also, you need to ensure you are setting your "unique identifier to match against existing elements" to something that exists in your feed (you set that at the bottom of the mapping screen).

I will close this ticket now, but please feel free to reply if you have any more questions.
