### ISSUE TITLE
NULL CP trigger causing malformed direct feed urls

### ISSUE THREAD

**Issue by bradlilley** [craftcms/feed-me#1189]
### Description
When hosting the control panel on an [alternate domain](https://craftcms.com/knowledge-base/access-control-panel-from-alternate-domain) with a `null` CP trigger, FeedMe produces malformed [direct feed urls](https://docs.craftcms.com/feed-me/v4/feature-tour/feed-overview.html#settings-pane).

**Expected:**
`https://cms.domain.tld/index.php?p=actions/feed-me/feeds/run-task&direct=1&feedId=1&passkey=xxxxxxxxxx`

**Actual:**
`https:cms.domain.tldindex.php?p=actionsfeed-mefeedsrun-task&direct=1&feedId=1&passkey=xxxxxxxxxx`

**Cause:**
This issue is caused by the `cpTrigger` being [set](https://github.com/craftcms/feed-me/blob/main/src/templates/feeds/index.html#L106) before it's [stripped](https://github.com/craftcms/feed-me/blob/main/src/templates/feeds/index.html#L108) from the `directUrl`. This logic does not account for `null` or empty triggers. This results in the `cpTrigger` being set to `/`, which then results in all forward slashes being stripped from the `directUrl` when the `cpTrigger` is replaced with an empty string in the `actionUrl`.

### Steps to reproduce

1. Update the `baseCpUrl` and `cpTrigger` in the general config manually, or via `ENV` variables.

**.env**
```
BASE_CP_URL=https://cms.domain.tld
CP_TRIGGER=
```
_Setting `CP_TRIGGER=NULL` is also a valid option._

**general.php**
```
'baseCpUrl' => App::env('BASE_CP_URL') ?: null,
'cpTrigger' => App::env('CP_TRIGGER') ?: null,
```
3. Add a feed via the CP or through the Feed Me config file.
4. Check the **"Direct Feed URL"** for the newly created feed.

### Additional info

- Craft version: 3.7.45.1
- PHP version: 8.0.13
- Database driver & version: PostgreSQL 13.4
- Plugins & versions: 4.5.3

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/feed-me/pull/1190
