### ISSUE TITLE
preg_match() type error when setting default for asset field

### ISSUE THREAD

**Issue by siffring** [craftcms/feed-me#1195]
### Description
When running an entry import that has a default asset set for an asset field I get this error:

```
**preg_match(): Argument #2 ($subject) must be of type string, array given**
```

It's from line 133 of feed-me/src/fields/Assets.php

### Steps to reproduce

1. Set a default file for an asset field in an entry import
2. Run the import

If you remove the default file setting the import works.

### Additional info

- Craft version: 4.2.8
- PHP version: 8.1.11
- Database driver & version: MySQL 8.0.26
- Plugins & versions: FeedMe 5.0.4

**Comment by DTesch-Reem** [comment]
Also experiencing this bug.

**Comment by i-just** [comment]
Hi, thanks for reporting. I need help replicating this issue. I tried a JSON feed for entry import with add & update strategy; my asset field has access to all volumes and is a standalone field (not embedded in a matrix or anything like that). Could anyone please give me some more info on how I can reproduce this?

**Comment by siffring** [comment]
@i-just I don't have that environment setup any more, but as I recall I was just trying to assign a default image to an asset field. I don't recall if the asset was in an Matrix or stand alone.

My source was a Google Sheet if that matters.

**Comment by i-just** [comment]
Thanks for the info. The source shouldn’t matter here. 

I can replicate this if I map the assets field to a value from a feed, have some empty values in my feed and then still select a default value.

<img width="2268" alt="Screenshot 2023-01-24 at 11 38 02" src="https://user-images.githubusercontent.com/4500340/214282259-4f5b3a3c-7d39-4825-aa68-d800e20e03b0.png">

We’ll discuss this behaviour internally.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1229

**Comment by brandonkelly** [comment]
Feed Me 4.6.0 (Craft 3) and 5.1.0 (Craft 4) have been released with the fix for this.
