### ISSUE TITLE
Call to a member function getBlockTypeFields() on null - Matrix.php

### ISSUE THREAD

**Issue by DTesch-Reem** [craftcms/feed-me#1197]
### Description
Having trouble importing rich text in a matrix->supertable->matrix field with JSON.

Error: Call to a member function getBlockTypeFields() on null - Matrix.php: 199

### Steps to reproduce

1. Setup import with JSON feed
2. Import text in a matrix->supertable->matrix field.
3. Run import

### Additional info

- Craft version: 4.3.1
- PHP version: 8.0.1
- Plugin version: 5.0.4

**Comment by olivierbon** [comment]
Any chance you can send a database backup and your `composer.json`, `composer.lock` to support@craftcms.com and reference this issue, please?

**Comment by angrybrad** [comment]
Closing out for inactivity, but respond here or to support@craftcms.com is this is still an issue.
