### ISSUE TITLE
craft\commerce\services\ProductTypes::hasPermission(): Argument #1 ($user) must be of type craft\elements\User

### ISSUE THREAD

**Issue by hassanmah** [craftcms/feed-me#1199]
### Description
Whenever I run a feed via the Direct link eg. https://site.com/index.php?p=actions/feed-me/feeds/run-task&direct=1&feedId=[id]&passkey=[passkey] when I'm logged out of the CP.

When logged in, it works fine

I get the following error:

`craft\commerce\services\ProductTypes::hasPermission(): Argument #1 ($user) must be of type craft\elements\User, null given, called in /public_html/vendor/craftcms/commerce/src/services/ProductTypes.php on line 178`

### Steps to reproduce

1. Log out of CP 
2. Run a feed via the Direct link

- Craft version: 4.2.5.1
- PHP version: 8.0.22
- Database driver & version: MySQL
- Plugins & versions: Commerce: 4.1.2, Feed Me: 5.0.4

**Comment by angrybrad** [comment]
Resolved this in Commerce via https://github.com/craftcms/commerce/commit/b3ec7bb0d21f461df7a3297fbc74c295a5e1fc82 for both Commerce 3 and 4 and will be included in the next releases.
