### ISSUE TITLE
Order of assets not being honoured when imported

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/feed-me#1206]
### Description
We've generated a json file from an external api connection. This json file can be viewed here: https://www.mint-homes.co.uk/vebra-connection/all-properties.json

The images are being imported in a strange order. The json file specifies an array of images and here is an example of this:

```
images: {
  0: {
    name: [],
    url: "https://alto3-alto-media.s3.amazonaws.com/cuOx2MV_CrpN_RTSki29Z_l694U/7sdw3CzROoL3XuFtZZlSHrZ8fC8/Photo/[3]/CqeQgZr1X_seRy8HJ-mfeehgoCw.jpg",
    updated: "2022-11-11T16:46:20.133"
  },
  1: {
    name: [],
    url: "https://alto3-alto-media.s3.amazonaws.com/cuOx2MV_CrpN_RTSki29Z_l694U/7sdw3CzROoL3XuFtZZlSHrZ8fC8/Photo/[3]/kL9bsUtB2S4ht2Gl3msZd-U9eAI.jpg",
    updated: "2022-11-11T16:46:20.133"
  },
  2: {
    name: "front view.jpg",
    url: "https://alto3-alto-media.s3.amazonaws.com/cuOx2MV_CrpN_RTSki29Z_l694U/7sdw3CzROoL3XuFtZZlSHrZ8fC8/Photo/[3]/uYd1W5RUqkyZ1rvmKev9gg.jpg",
    updated: "2022-11-11T16:46:20.133"
  },
  3: {
    name: "bedroom.jpg",
    url: "https://alto3-alto-media.s3.amazonaws.com/cuOx2MV_CrpN_RTSki29Z_l694U/7sdw3CzROoL3XuFtZZlSHrZ8fC8/Photo/[3]/L-HKZTiOLUa9byhqfbOuDA.jpg",
    updated: "2022-11-11T16:46:20.133"
  }
}
```

Feedme is mapped to this array and using the "Create asset from url if exists" setting and the dropdown is set to "Use existing asset"

When checking the imported entry we are seeing the assets in the following order: 2, 3, 0, 1. We have tried manually reordering these to 0, 1, 2, 3 but as soon as the import runs again it resets the order to incorrectly be 2, 3, 0, 1.

Is there anything you can see in the above data which would cause this discrepancy? We believe this to be a feedme bug as we can't spot any issues with our json feed.

### Steps to reproduce

1. Reorder assets in craft field and save the entry
2. Run feedme import
3. Check assets and see they are in the wrong order

### Additional info

- Craft version: Craft Pro 3.7.61
- PHP version: 7.4.33
- Database driver & version: MySQL 8.0.31
- Plugins & versions: FeedMe 4.5.3

**Comment by brianjhanson** [comment]
I put together a super simple test using the same feed and I'm seeing the assets in the field have the same order as they are in the JSON feed. Are there any other details that might help me reproduce the issue? Or do you have any custom code getting executed within the import code path?

It's expected that changes you make to the order in the field will get washed away when Feed Me does another import. It's not quite smart enough to compare the order of elements within a field and respect it on each import. When a match is found, the entire field value is replaced with data from the field.

**Comment by olivierbon** [comment]
Discussing in support. Will update accordingly.

**Comment by brianjhanson** [comment]
Looks like this has been handled for the moment via support. Thanks @olivierbon!
