### ISSUE TITLE
When trying to go from php version 7.4 to 8.0 the following error is shown

### ISSUE THREAD

**Issue by Troops994** [craftcms/feed-me#1207]
Once upgraded php version and trying to update packages we get the following error.

Your requirements could not be resolved to an installable set of packages.

Problem 1
- cakephp/utility 3.10.4 requires php >=5.6.0, your php version (8.0.24; overridden via config.platform, same as actual) does not satisfy that requirement.
- craftcms/feed-me 4.5.3 requires cakephp/utility ^3.3.12 -> satisfiable by cakephp/utility[3.10.4].
- craftcms/feed-me is locked to version 4.5.3 and an update of this package was not requested.

**Comment by brianjhanson** [comment]
I'm having some trouble replicating this one. Can you give us a bit more info?
- What PHP version are you updating to? It looks like 8.0.24, but just want to be sure
- What version of Craft are you using? I'm assuming 3, but again, just want to make sure

It seems odd that the error message claims `cakephp/utility` requires PHP >=5.6.0 but recognizes a higher version. Is there anything else about your setup that's notable?

**Comment by brandonkelly** [comment]
`composer update` should automatically downgrade `cakephp/utility` to 3.9.4 to avoid the conflict.

**Comment by angrybrad** [comment]
Going to go ahead an close this, but respond back if you're still having issues and we'll debug further.
