### ISSUE TITLE
Entries in site-group sites disabled when importing to a specific site

### ISSUE THREAD

**Issue by ThomasDeMarez** [craftcms/feed-me#1208]
### Description
When a dedicated feed is used to update entry statuses for a site in a site group all entries in that site group across the different sites their statuses are updated.

### Expected behavior
Only the entry in the site for which the feed-me feed was set up should be disabled. 

### Steps to reproduce

1. Create a site group with three sites (EN, FR, NL)
2. Create a section with the propagation method 'Save entries to other sites in the same site group'
3. Create some entries across the different sites for this section
4. Setup a feed with only id's to match to the entries
     - Set the target site to one of the site in the group (do not use the default global site)
     - Set the default status for the mapping to "use default value" and "disabled" 
     - Run the feed
5.  Check the entries and verify they are disabled in the desired site
6. Now check the other sites, they will be disabled as well

### Additional info

- Craft version: 3.5.19.1
- PHP version: 7.3.33
- Database driver & version: MariaDB 10.3.36
- Plugins & versions: Feed-Me 4.3.6

--- 

The following is a simple db & import file for a new setup on Craft 4 with the latest feed-me that demonstrates the issue.
[db-and-import-file.zip](https://github.com/craftcms/feed-me/files/10294269/db-and-import-file.zip)

**Comment by ThomasDeMarez** [comment]
This issue is back for us in 5.1.4. 
I was able to create a fix for this in https://github.com/craftcms/feed-me/pull/1345

**Comment by angrybrad** [comment]
Fixed for the next release!
