### ISSUE TITLE
Importing title will always save the entry even when the title remains the same

### ISSUE THREAD

**Issue by boudewijn-zicht** [craftcms/feed-me#1219]
### Description
There is a bug in the code that compares the element's attributes (this includes the title) with the new imported data.  Currently this always determines that the element attributes have changed, even when they did not.

This results in an element save event and all the additional overhead that this causes, i.e. database growth because of revisions.

### Steps to reproduce

1. Host a static file somewhere with data that you want to import, i.e. `{"data":[{"title":"Imported A"}]}`
2. Configure a feed-me import to create a new Entry with the title, and enable the update flag
3. Run the import multiple times, you can see that the import created one Entry 'Imported A' but it has one revision for every time you ran the import, even though the title never changed

A fix is already available, see https://github.com/craftcms/feed-me/pull/1218

**Comment by boudewijn-zicht** [comment]
Since making this issue I have found several more issues, I have patched them locally so I can continue in the hopes of removing the patch once a fix is made in this library by the author.  Is this likely to happen?  I see very little activity and many open issues and pull requests...

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1218 - thanks!

Feel free to keep making PRs/issues @boudewijn-zicht - going to be spending the next few months doing a housecleaning and bug-fixing sprint on Feed Me.

**Comment by boudewijn-zicht** [comment]
> going to be spending the next few months doing a housecleaning and bug-fixing sprint on Feed Me.

That is very nice to hear, thanks!

**Comment by brandonkelly** [comment]
Feed Me 4.6.0 (Craft 3) and 5.1.0 (Craft 4) have been released with the #1218 changes 🎉
