### ISSUE TITLE
The issue with Matrix fields

### ISSUE THREAD

**Issue by mofman** [craftcms/feed-me#1226]
The documentation explicitly says do not name the nodes for each block. eg.

```
<MatrixContent>
    <RichTextBlock>
        <Copy>Lorem ipsum...</Copy>
        <Caption>Some more text.</Caption>
    </RichTextBlock>

    <ImageBlock>
        <Image>img_fjords.jpg</Image>
    </ImageBlock>
</MatrixContent>
```

I still can't wrap my head around the approach in the documentation which is the following.

```
<MatrixContent>
    <MatrixBlock>
        <Copy>Lorem ipsum...</Copy>
        <Caption>Some more text.</Caption>
    </MatrixBlock>

    <MatrixBlock>
        <Image>img_fjords.jpg</Image>
    </MatrixBlock>
</MatrixContent>
```

This makes no sense to me, lets assume you have two blocks in your matrix that have identical fields names eg 

**Hero Block**
Main Title, Main Image

**Text & Image Block**
Main Title, Main Image

There is abolutely no way for you to import content into these block in any sort of uniform way. The example the documention says you should not use is exactly the way it should be in my view?

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/commit/b7c5c9e8c48290077acc4f0d1a280dbf48b60d50, https://github.com/craftcms/feed-me/commit/8931ff6a29261a0509b7ffb9ee79f64a06588567, and https://github.com/craftcms/feed-me/commit/0a530207775f4c4e1c93e96f9ffc449a8494fdfa

**Comment by brandonkelly** [comment]
Feed Me 5.1.0 has been released with the fix for this.
