### ISSUE TITLE
Asset import error with Craft 4.3.7

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/feed-me#1231]
### Description
Importing a feed with assets results in an error.
```
craft\helpers\Db::escapeForLike(): Argument #1 ($value) must be of type string, null given, called in /vendor/craftcms/cms/src/services/Assets.php on line 493 - Db.php: 488
```

### Steps to reproduce
1. Update  to Craft 4.3.7
2. Start an import with assets

### Additional info

- Craft version: 4.3.7
- PHP version: 8.1.14
- Database driver & version: MySQL 10.3.36
- Plugins & versions: Feedme 5.0.5

**Comment by i-just** [comment]
Hi, thanks for reporting that!

The issue was within the CMS itself. I created a PR to resolve this.

**Comment by brandonkelly** [comment]
Craft 3.7.65 and 4.3.8 are out with a fix for this.
