### ISSUE TITLE
Import feed: craft\helpers\Db::escapeForLike(): Argument #1 ($value) must be of type string, null given

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/feed-me#1233]
### Description

I now get this error when running a feed:

`Import feed: craft\helpers\Db::escapeForLike(): Argument #1 ($value) must be of type string, null given, called in /vendor/craftcms/cms/src/services/Assets.php on line 493 - Db.php: 488.`

I have an Asset field, which has a valid image value. `Create asset from URL` is checked. I also have a few fields filled in the Asset object (text and number fields).

This seems to be working previously without this issue previously. FYI I recently updated `craftcms/cms` from `4.3.6.1` to `4.3.7.1` (and then from `4.3.7.1` to `4.3.8`).

Here's a sample of the JSON for the asset node:
```
{
	"cover": [
      {
        "url": "https://agendabrussels.imgix.net/bozar-c691e2c95009f89dd5efc09996d17e6a427cb89f.jpg",
        "caption": null,
        "importId": 546587,
        "museumId": 117,
        "importUrl": "https://agendabrussels.imgix.net/bozar-c691e2c95009f89dd5efc09996d17e6a427cb89f.jpg"
      }
    ],
}
```

What does this error means, and how to fix it?

### Steps to reproduce

1. Run a JSON feed
2. Get the error
3. No update

### Additional info

- Craft version: 4.3.8
- PHP version: 8.1.0
- Database driver & version: MySQL 5.7.23

**Comment by romainpoirier** [comment]
I just have downgraded `craftcms/cms` to `4.3.6.1` and I don't get this error anymore.

**Comment by i-just** [comment]
Hi, thanks for reaching out. This was first reported here: https://github.com/craftcms/feed-me/issues/1231, fixed in 4.3.8 and 3.7.65.

**Comment by romainpoirier** [comment]
Thank you, for as explained I have this issue with `4.3.8`, so it doesn't seem fixed.

**Comment by i-just** [comment]
Thanks. I have tested this again, and I can replicate it on `4.3.7` but not on `4.3.8` (or above).
This is the line causing issues in `4.3.7`: https://github.com/craftcms/cms/blob/4.3.7/src/services/Assets.php#L493 (same as in the error you mentioned).
And this is how it looks starting from `4.3.8`: https://github.com/craftcms/cms/blob/4.3.8/src/services/Assets.php#L497.

Could you please update again, try clearing the cache and check if this is still happening for you?

**Comment by romainpoirier** [comment]
Thank you, you were right. I now have updated to the latest `4.3.8.2`, and now the problem is gone.

**Comment by i-just** [comment]
Great news. Thanks for confirming!
