### ISSUE TITLE
Improve array comparison during import

### ISSUE THREAD

**Issue by boudewijn-zicht** [craftcms/feed-me#1238]
Two more PR's that improve how values are compared to reduce the updates done during import

https://github.com/craftcms/feed-me/pull/1237
https://github.com/craftcms/feed-me/pull/1236

**Comment by kristiansp** [comment]
I also have a really old pull request that's kind of related, to sort arrays before comparing, as otherwise it will always update if the elements are in a different order. Could maybe be combined.

[#735](https://github.com/craftcms/feed-me/pull/735/commits/e29d9821935fd96c679f9504737c8ee513c75fde)

**Comment by kristiansp** [comment]
Another unrelated and simple pull request regarding performance, with the hope that it will be seen – checking if an element is already disabled before disabling it, avoiding to uneccessarily save them again (I have the need to update elements that might be enabled later under circumstances, and can't see it hurts).

#736

**Comment by angrybrad** [comment]
Resolved on develop branch.
