### ISSUE TITLE
Comparison fails to recognise lightswitch fields when nothing else is changed

### ISSUE THREAD

**Issue by kristiansp** [craftcms/feed-me#1242]
### Description

When values are compared in `Datahelper.php`, it fails to recognise a lightswitch field being toggled off as a changed value, even if it's passed as a string, e.g. `'false'`, `'No'`, etc.

If another value has changed, the new value will be passed through, and the lightswitch toggles off correctly. The problem is that if this is the only value changed, Feed Me will see the element as unchanged, and will skip updating it altogether.

It seems to be a bit the same as #760, but the comparison code has changed since then. I suspect this comment about probably doing a strict check might be a good idea, but I don't what the issue with backwards compatibility would be:
``` 
        // Should probably do a strict check, but doing this for backwards compatibility.
        if (Hash::check($fields, $key) && ($firstValue == $secondValue)) {
```

### Steps to reproduce

1. Run feed where only change is turning lightswitch field off
2. Lightswitch field is NOT turned off

### Additional info

- Craft version: 4.3.10
- PHP version: 8.0.26
- Database driver & version: MySQL 10.4.27
- Plugins & versions: FeedMe 5.0.5

**Comment by bryantAXS** [comment]
I'm running into this as well.

**Comment by i-just** [comment]
Hi, thanks for reporting. This was recently fixed: https://github.com/craftcms/feed-me/blob/develop/CHANGELOG.md#514---2023-06-15
