### ISSUE TITLE
Pagination URL doesn't work when Feed URL contains an alias

### ISSUE THREAD

**Issue by simonkuran** [craftcms/feed-me#1244]
When the Pagination URL is something like `/folder/feed-data-2.json` and the Feed URL is something like `@rootUrl/folder/feed-data-2.json` (`@rootUrl` being set to something like `https://site.test`) Feed Me will silently ignore the pagination and only import one file.

It seems like line 52 of `vendor/craftcms/feed-me/src/base/DataType.php` doesn't parse aliases.

I believe this was working correctly with Feed Me v4.2.4 and Craft v3.5.12.1. Perhaps there's been a regression of [this bug fix](https://github.com/craftcms/feed-me/commit/38f36078527e8f5fdc683609dfea3a2aca8fc4d2). There's a chance I missed a change in my configuration and this isn't a bug. But in that case I think this would make a good feature request. It's confusing that Feed URL only supports aliases when there's _not_ pagination.

**Current versions**
Feed Me v4.5.4
Craft v3.7.63.1

**Comment by himynameisphil** [comment]
also running into this issue!

**Comment by i-just** [comment]
Hi, thanks for getting in touch. I’m having trouble replicating this issue. This is how I understand this problem:
- you have an alias called `@rootUrl` set to `https://site.test`
- you have a feed URL set to, e.g. `@rootUrl/folder/feed-data.json`
- in your feed, you have a node, e.g. `nextPage` set to `/folder/feed-data-2.json` 
- and that node is mapped as Pagination URL
And when you run the feed, only the first page is imported?

I have tried the above with Feed Me 4.5.4, and it works as expected.

I can trigger the pagination to silently fail if my `nextPage` node is set to `@rootUrl/folder/feed-data-2.json`. For that, I have raised a PR.

Please let me know if I misunderstood the problem.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1301 for the next v4 and v5 releases. If we're misunderstanding the issue, just comment back here with more information and we can re-open.

**Comment by angrybrad** [comment]
We just released Feed Me 4.6.3. and 5.1.3 with this fix.
