### ISSUE TITLE
Table fields UI missing the "Default value" input field

### ISSUE THREAD

**Issue by tomkiss** [craftcms/feed-me#1254]
### Description

When attempting to import to a table field, there is an option for setting a default value:

However - the input field, which normally appears on the right, is missing. So it's not possible to enter a default value.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/183310/224565430-bafb6451-c421-448d-bcf0-0a66be378820.png">

### Additional info

- Craft version: 4.4
- PHP version: 8.1
- Database driver & version: MySQL 8
- Plugins & versions: Feedme 5.0.5

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1300 for the next v4 and v5 releases.

**Comment by angrybrad** [comment]
We just released Feed Me 4.6.3. and 5.1.3 with this fix.
