### ISSUE TITLE
Mapping fields, child element selection - use element selection modal instead regular select

### ISSUE THREAD

**Issue by piotrpog** [craftcms/feed-me#1255]
During the mapping of feed, when we want to import into structure entry, we can select default parent. WIdget for parent selection is regular `<select>`, instead of craft element selection modal.

This means that plugin template queries ALL elements of section we want to import into, to populate select. And this can cause db to just freeze from trying to query 10000 entries at once :)

**Comment by i-just** [comment]
Hi, thanks for reaching out. I raised a PR to switch the default parent selection to a modal.

**Comment by angrybrad** [comment]
Resolved at https://github.com/craftcms/feed-me/pull/1293 for the next v4 and v5 releases

**Comment by angrybrad** [comment]
We just released Feed Me 4.6.3. and 5.1.3 with this fix.
