### ISSUE TITLE
Save, Save & Continue Buttons Not Working (After Upgrade to CraftCMS 4.4.3)

### ISSUE THREAD

**Issue by adrianjean** [craftcms/feed-me#1257]
### Description
After upgrading to CraftCMS 4.4.3, the "Save" and "Save & Continue" buttons don't seem to work. Using the keys COMMAND+S do seem to trigger a save operation on a feed.

### Additional info

- Craft version: 4.4.3
- PHP version: 8.2.4
- Database driver & version: 8.0.32
- Plugins & versions: 5.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting. A PR to fix this has been submitted.

**Comment by angrybrad** [comment]
5.1.1 and 4.6.1 are out with a fix for this.
