### ISSUE TITLE
"Show Detail" links on the Logs tab don't seem to work (After Upgrade to CraftCMS 4.4.3)

### ISSUE THREAD

**Issue by adrianjean** [craftcms/feed-me#1258]
### Description
After upgrading to CraftCMS 4.4.3, while attempting to diagnose why a feed was not able to run, I checked the Logs tab and clicked on the "Show Detail" link next to the error log entry in the Feeds interface. Clicking on this link only snaps the browse back to the top of the page.

### Additional info
- Craft version: 4.4.3
- PHP version: 8.2.4
- Database driver & version: 8.0.32
- Plugins & versions: 5.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting. A PR to fix this has been submitted.

**Comment by angrybrad** [comment]
5.1.1 and 4.6.1 are out with a fix for this.
