### ISSUE TITLE
Feedme.js 404 (file was renamed FeedMe.js)

### ISSUE THREAD

**Issue by juddlyon** [craftcms/feed-me#1259]
### Description
I was getting a 404 error in the console for Feedme.js. My cpresources had a file called FeedMe.js (uppercase M) and renaming it fixed the issue. I noticed the filename changes in commit 6375375 and I'm guessing this is a minor bug but I'm not 100% certain. 

### Additional info

- Craft version: 4.4.3
- PHP version: 8.0.2
- Database driver & version: MySQL 8.0.23
- Plugins & versions: FeedMe 5.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting. Good spot! A PR to fix this has been submitted.

**Comment by angrybrad** [comment]
5.1.1 and 4.6.1 are out with a fix for this.
