### ISSUE TITLE
$feed argument added to DataHelper::fetchValue() is a breaking change and needs to be made optional.

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/feed-me#1264]
### Description

The $feed argument that was added to [DataHelper::fetchValue()](https://github.com/craftcms/feed-me/blob/2528d15a9e234338a00a36d43bc0c3546316f831/src/helpers/DataHelper.php#L122) in Feed Me 5.1.0 is required and not mentioned in the release notes. [Here's some analysis from an issue I mistakenly filed with Neo](https://github.com/spicywebau/craft-neo/issues/727#issuecomment-1482066273), but it sounds like this a breaking change for any packages using `DataHelper::fetchValue()`, so it needs to be made optional in Feed Me.

### Steps to reproduce

1. Install Feed Me and Neo (or any other package using `DataHelper::fetchValue()`).
2. Attempt to run a feed importing affected items.

### Additional info

- Craft version: 4.4.5
- PHP version: 8.1.1
- Database driver & version: MySQL 8.0.30
- Plugins & versions: "craftcms/feed-me": "5.1.1", "spicyweb/craft-neo": "3.7.3"

**Comment by angrybrad** [comment]
Just released Feed Me 5.1.1.1 and 4.6.1.1 with a fix for this.
