### ISSUE TITLE
Unable to log errors only

### ISSUE THREAD

**Issue by leigeber** [craftcms/feed-me#1295]
### Description

It seems the logging feed-me.php config value might be cast to a boolean somewhere? When I have the value set to "error" info logs are still captured. Appreciate the assist.

### Additional info

- Craft version: 4.4.7.1
- PHP version: 8.2
- Database driver & version: PostgreSQL
- Plugins & versions: 5.1.2

**Comment by i-just** [comment]
Hi, thanks for reaching out. Yes, it’s a bug. I created a PR for this.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/issues/1295 for the next v5 release.

**Comment by angrybrad** [comment]
We just released Feed Me 5.1.3 with this fix.
