### ISSUE TITLE
Product Variant status set to false after update

### ISSUE THREAD

**Issue by joshparylak** [craftcms/feed-me#1304]
### Description
We recently updated our site from Craft 3.7.11 to 3.8.7, Commerce 3.4.2 to 3.4.20.1, Feed Me 4.4.0 to 4.6.2.

We had regular product imports running on the site without issue. The imports used a column with a value of 0 or 1 to set product status, and then the variant field 'enabled' was set to 'Use default value', with the default dropdown set to enabled. All products in our store have a single default variant.

This process was working until these updates. After we ran the updates, the next import set _all_ product variants touched by the import enabled field to `0`, preventing them from being added to carts.

I updated the import to use the status column in our import on the variant enabled field so it's being passed an explicit 1 or zero. This has restored all the products, so the issue is resolved for us by no longer using the 'use default value' option, but that functionality appears to be broken by one of these updates.

### Additional info

- Craft version: 3.8.7
- PHP version: 7.4.19
- Database driver & version: MySQL 8.0.26
- Plugins & versions:  
    - Craft Commerce | 3.4.20.1
    - Feed Me | 4.6.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for it.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1305 for the next v4 and v5 releases

**Comment by angrybrad** [comment]
We just released Feed Me 4.6.3. and 5.1.3 with this fix.
