### ISSUE TITLE
Can't Import Category data when using "Single Cat" Plugin

### ISSUE THREAD

**Issue by adrianjean** [craftcms/feed-me#1316]
### Description
When importing feeds from FeedMe, using category fields that are set to use Single Cat, the data is not imported.
I also noticed that the FeedMe configuration for the category does not have the same config as when it's set to a plain Category field type.

### Steps to reproduce

1. Change a category field to use "Single Cat"
2. Setup a feed that imports data into the category field managed by "Single Cat"
3. Run the feed and note the data is not imported.

### Additional info

- Craft version: 4.4.10
- PHP version: 8.2.5
- Database driver & version: 8.0.30
- Plugins & versions: 
  - Feed Me: 5.1.3.1
  - Single Cat: 3.0.3

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Feed Me does not support the “Single Category” field (natively or via the Simple Cat plugin itself). You can find a list of supported 3rd party fields here: https://docs.craftcms.com/feed-me/v4/content-mapping/field-types.html#third-party
