### ISSUE TITLE
Price not importing from a very simple CSV

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/feed-me#1324]
### Description
I have a CSV of product ID's in one column and their new prices in the next. When I try and import this, everything runs as expected except the prices don't get seen by FeedMe. The "Data Ready to import" should be `{"id":"1152087", "price":1375}` I'd have thought.

<img alt="image" src="https://github.com/craftcms/feed-me/assets/140605/ebcbfed2-b784-4a51-9f7b-3eb1f52ff102">

Below is the contents of my testing CSV (It's one row for easy testing, but this doesn't change if it's all 700 rows or not.

```csv
ID,Price
1152087,1375
```

### Steps to reproduce

1. Use FeedMe to only update an existing Commerce Product's price
2. Map only the ID and the Price field
3. Set the ID as the unique factor

### Additional info

- Craft version: Craft Pro 3.7.62
- PHP version: 8.0.19
- Database driver & version: MySQL 8.0.30
- Plugins & versions: FeedMe 4.5.3 and many others but none related to this. Know im behind a few FeedMe versions, but couldnt see mention of this being fixed in the releases and dont want to risk breaking anything else where i can help it.

Changing my file to a JSON file or updating the price to be a string or with decimals doesn't change anything.

I have other feeds who's prices work on creation, but this feed is just for updating.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Yes, to update any variant-related fields, mapping on Variant SKU is needed. Otherwise, we can’t reliably identify a variant that’s supposed to be updated.

Hope this helps!
