### ISSUE TITLE
some feed options are always ignored

### ISSUE THREAD

**Issue by i-just** [craftcms/feed-me#1356]
### Description
While reviewing PR 1353, I noticed that some feed options were always being ignored: `queueTtr`, `queueMaxRetry` and `assetDownloadCurl`, no matter what value was set in the `feed-me.php` config file.

### Steps to reproduce

1. create `feed-me.php` config, with the following config (for either all feeds or a specific one)
```
  'queueTtr' => 150,
  'queueMaxRetry' => 2,
  'assetDownloadCurl' => true,
```  
2. create a feed that is supposed to grab an image from provided url; make sure that asset doesn’t exist in the CMS;
3. set a breakpoint here https://github.com/craftcms/feed-me/blob/develop/src/helpers/AssetHelper.php#L39 and notice that the `$assetDownloadCurl` is always `false`
4. run the feed and notice that the job is added to the queue with the default `ttr` of `300`

### Additional info

- Craft version: 3.8.16 and 4.4.16.1
- PHP version: 7.2 and 8.1
- Database driver & version: n/a
- Plugins & versions: Feed Me 4.7.0 and 5.2.0

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1357 and will be included in the next v4 and v5 releases.
