### ISSUE TITLE
Missing "Create entries if they do not exist" if the selected option isn't "title"

### ISSUE THREAD

**Issue by sander-lameco** [craftcms/feed-me#1358]
### Description
We noticed that the option `Create entries if they do not exist` for an entry field is only available if the `Data provided for this entry` is set to `Title`. Is it possible to also make this option available for a custom field? We use the `title` field to rename the entry and an custom `identifier` field to match with the data. So the `identifier` field is always the same but matching the external data and so the `title` field can be changed within the CMS.

### Steps to reproduce

1. Create an `test` entry section
2. Create a `test` Entry field mapped to the created `test` entry section
3. Create a `identifier` Number field
4. Create a `feed` entry section
5. Add the `test` field to the `feed` entry section
6. Add the `identifier` field to the `test` entry section
7. Create a feed for the `feed` entries and map a value to the `test` field.
8. Map some json data to the feed and select `identifier` as the  `Data provided for this entry`. Now the option `Create entries if they do not exist` is missing.

### Additional info

- Craft version: `4.4.16.1`
- PHP version: `8.2`
- Database driver & version:
- Plugins & versions: `5.2.0`

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This is currently working as intended. More details can be found here: https://github.com/craftcms/feed-me/pull/1341. Please feel free to open a discussion about it, though!
