### ISSUE TITLE
Empty column headings in feed cause incorrect pagination url dropdown value.

### ISSUE THREAD

**Issue by mikeymeister** [craftcms/feed-me#1375]
### Description
We have come across a case where the google sheet used for the feed has a column of data with no heading in the first row. When trying to save the pagination url, the select field has multiple options with `value=""`. 
<img width="432" alt="Screenshot 2023-10-30 at 20 31 16" src="https://github.com/craftcms/feed-me/assets/34517288/98545ddc-3c32-4621-bb14-b374d7bca65e">
This causes the dropdown to show the latest empty value option as the pagination url. I fully accept that the data is poorly formed for a feed and that this is in edge case territory. 
Perhaps "No Pagination URL" should be an option with a value that specifies there is no pagination url rather than the absence of a value eg `<option value="no-pagination">No Pagination URL</option>`? Or exclude options from the dropdown that don't have a key? There could even be a lightswitch for pagination url that when enabled, displays valid options for a pagination url from the feed.

### Steps to reproduce

1. Set up a feed from a google sheet where at least one of the table columns has no heading
2. Try to save the feed with no pagination url set.

### Additional info

- Craft version: 4.4.15
- PHP version: 8.1
- Database driver & version: MariaDB 10.11.5
- Plugins & versions: Feed Me - 5.2.0

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1385 and will be included in the next release.
