### ISSUE TITLE
Element fields not being honored

### ISSUE THREAD

**Issue by dr-codswallop** [craftcms/feed-me#1378]
### Description
Importing nested element fields aren't populating. 

Given a use case of populating an Agents section. Each Agent has a headshot asset, and there's an asset field for photo credit.

Example node from the XML feed:

```xml
<data>
  <agent>
    <ID>329</ID>
    <photo>https://example.com/wp-content/uploads/2016/11/joe-bloggs.jpg</photo>
    <credit>Mark Pringle</credit>
    <Firstname>Joe</Firstname>
    <Lastname>Bloggs</Lastname>
  </agent>

  ..more <agent> nodes

</data>
```

![image](https://github.com/craftcms/feed-me/assets/49959728/c2072027-444e-4fbd-a1d8-f99450862f29)

The asset gets created, but misses the 'photo credit' data. No evidence of it being used in the logs :

![image](https://github.com/craftcms/feed-me/assets/49959728/c86cf783-2499-49e9-9ec1-7a66214507ec)

Tried it with a csv feed instead, but same issue. 

### Additional info

- Craft version: 4.5.9
- PHP version: 8.2
- Database driver & version: MySQL
- Plugins & versions: FeedMe 5.2.0

**Comment by fgd007** [comment]
I have the same issue. I'm importing Entries via a json file. Each entry has an image object with additional fields, which I map with Element Fields. Unfortunately they're being ignored when importing the content.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1383 and will be included in the next release.
