### ISSUE TITLE
Can not add `false` override for feed settings

### ISSUE THREAD

**Issue by tricki** [craftcms/feed-me#1380]
### Description
I'm trying to disable the "Update search indexes" and "Backup" using the `feed-me.php` override config, but it's getting completely ignored.

I tracked it down to this line: https://github.com/craftcms/feed-me/blob/develop/src/services/Feeds.php#L296

I'd suggest that instead of checking the value, it should check if the key exists.

FYI the reason I want to disable those is because I have multiple feeds which get triggered at the same time, and I only want to do those operations for the one that runs last.

### Steps to reproduce

1. Set the `feedOptions` field in `/config/feed-me.php` to this:
```php
[
    '1' => [
        'backup' => false,
    ]
]
```
3. Create a new feed. On the "Create a new feed" page, note how the "Backup" toggle is active.

### Additional info

- Craft version: 4.5.10
- PHP version: 8.0.30
- Database driver & version: MariaDB 10.5.13
- Plugins & versions: Feed Me 5.2.0

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1382 and will be included in the next release.
