### ISSUE TITLE
Adding assets using id/custom field

### ISSUE THREAD

**Issue by josh-attwood** [craftcms/feed-me#1402]
I have a site which we are migrating from Prismic.

The way that we have the data from the JSON exports means that we have successfully imported all of the assets. We are now left with importing entries. The data we have for importing assets within entries only includes data such as the ID and slug but I can't see a way to link our existing assets with our entries on import using anything other than the image url which we don't have within this data.

When populating an 'entries' field there is the option to select 'Data provided for this entry is:'. Is there any reason this isn't available when importing entries and is there any other way to do this?

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

As of v5.5.0 (for cms 4) and v6.1.0 (for cms 5), it’s possible to choose to map assets based on the element ID and not just filename/url.
