### ISSUE TITLE
Date fields in matrixblocks are incorrectly compared spawns new revisions

### ISSUE THREAD

**Issue by jeffreyzant** [craftcms/feed-me#1403]
### Description
The `_recursiveCompare` method in the DataHelper does not handle date fields correctly. Craft return dates as "Y-m-d H:i:s", while feed-me compares them to a Carbon object which results in a mismatch. This causes feed-me to resave the post spawning a new revision even though there are no content changes.

The root method `compareElementContent` does handle dates correctly.

I'll submit a PR following this issue to resolve it.

### Additional info

- Craft version: 4.5.13
- PHP version: 8.3.0
- Plugins & versions: 5.3.0

**Comment by angrybrad** [comment]
Merged PR and this will be included in the next release.
