### ISSUE TITLE
Can't import if the value of multi-select field is 0

### ISSUE THREAD

**Issue by samdi** [craftcms/feed-me#1413]
### Description
I created a field with multi-select for all the days of the week (days_of_week), with values from 0 to 6. However, when I try to the sunday with value 0,  it does not show "Sunday" as selected in the entry editor. I tried other values 1 - 6, it works. I also tried 0 and 1 and only 1 is selected.

### Steps to reproduce

1. Create a multi-select field with options and values for all days of the week, starting with Sunday (value 0) to Saturday (value 6).
2. Add this field to an entry type.
3. Import a new entry with this property, for example, <days_of_week>< item >0< /item ></days_of_week>
4. Check to see it in the entry editor and the field is empty, not selected.

### Additional info

- Craft version: 4.7.3
- PHP version: 8.2
- Database driver & version: Mariadb 10.6
- Plugins & versions: 5.3.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by angrybrad** [comment]
Merged and will be included in the next release.
