### ISSUE TITLE
Editing a field locks up site while importing.

### ISSUE THREAD

**Issue by green-plastic** [craftcms/feed-me#280]
### Description
The `craft_content` table will lock if you try to do an import (while import is still going) then go to edit a field.

In MySQL I see a "Waiting for table metadata lock" state on an alter table for `craft_content` for the field that was just edited. If I kill the query, the site works again.

I tested this same thing on editing entries, globals and categories.

I'm not an expert, but since the import works with the `craft_content` table, I'd suspect that altering it at the same time causes this issue.

Maybe put a notice or somehow lock a user out from editing anything that could alter the `craft_content` table?

### Steps to reproduce

1. Start import (make sure it's big enough where it'll take a moment or two)
2. Go to Settings > Fields > pick a field to edit
3. While the import is still going, edit the field and save.

### Additional info

- Plugin version: 2.0.11
- Craft version: 2.6.3012

**Comment by engram-design** [comment]
Just checking in on this, still an issue?

**Comment by green-plastic** [comment]
It is, but I just make sure not to edit any fields during an import.

**Comment by angrybrad** [comment]
Going to assume this is stale now with the architecture changes in Craft 3 and the latest Feed Me, but comment back and we can re-open if it's still an issue on the latest.
