### ISSUE TITLE
Asset error: Trying to get property 'filename' of non-object

### ISSUE THREAD

**Issue by bindoff** [craftcms/feed-me#348]
### Description
When running a feed with an Eventbrite endpoint with an asset image field against <logo/original/url>, I'm getting the error `Asset error: [url] Trying to get property 'filename' of non-object`

An example value of <logo/original/url> is `https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F44334567%2F246497259411%2F1%2Foriginal.jpg?auto=compress&s=70c447248e3026761bda4dc2103c095e`

### Steps to reproduce

1. Set feed URL to https://www.eventbriteapi.com/v3/organizers/[organizerId]/events/?token=[token]&status=all
2. Set an Asset field to <logo/original/url>
3. Run the feed

### Additional info

- Plugin version: 3.0.0-beta.15
- Craft version: 3.0.13.2

**Comment by engram-design** [comment]
I can't actually reproduce the exact error given your example image, but I have made an improvement in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16) that might help.

**Comment by ijy** [comment]
I can confirm this is still a problem in beta.18.

From the FeedMe log:

`{"date":"2018-10-04 17:46:30","message":"Asset error: http:\/\/images.domain.com\/property\/images\/6\/5175f1a6a2b6421ccfc263713fec5e97.jpg - Trying to get property 'filename' of non-object","type":"error"}`

This occurs when images are nested inside a parent node (XML):

```
<images>
    <image>http://images.domain.com/images/3/0d4a6979adae5bfef097c698278940b0.jpg</image>
</images>
```

When I remove the nested to have a single `<image>` things seem to work fine. Unfortunately I have a requirement to pull in multiple images per entry.

**Comment by engram-design** [comment]
@ijy This is a bit tricky to debug without the actual URLs and your feed and field structure, which I understand you might not be able to share. Can we hook up on the Craft Slack (handle crawf) to see what we can do?

**Comment by angrybrad** [comment]
Going to assume this is stale now, but comment back and we can re-open if it's still an issue on the latest of Craft and Feed Me.
