### ISSUE TITLE
Feature Request: Use token in endpoint URL to pass the last fetch date to the API

### ISSUE THREAD

**Issue by jamealg** [craftcms/feed-me#361]
We're planning to use FeedMe to sync hundreds of items from a remote API and we'd like to avoid re-syncing the entire thing at a frequent interval. We can pass a `date_modified_after` parameter to our API that will fetch only items that were created/modified after a certain date. It would be really neat if FeedMe could pass the date of the previous run each time the feed is run.

For example, a feed could be configured with the following URL:
```http://myfeed.com/api.json?date_modified_after={date_last_fetched}```

When it runs the first time, it could be left blank:
```http://myfeed.com/api.json?date_modified_after=```

And the second time it would include the date from the previous time it was run:
```http://myfeed.com/api.json?date_modified_after=2018-07-18```

**Comment by weotch** [comment]
This would also be handy for [Google Calendar feeds](https://developers.google.com/calendar/v3/reference/events/list) and it's `syncToken` or `timeMin` parameter.
