### ISSUE TITLE
Create Commerce variants from CSV?

### ISSUE THREAD

**Issue by j-greig** [craftcms/feed-me#368]
Is it possible to create Commerce variants using pipes etc in the CSV file?

(Our client currently has their product catalogue in Airtable)

**Comment by engram-design** [comment]
At the moment, not really sorry. CSV as a data type doesn't give us a great deal of flexibility for nested repeated content. Sure they could be rows, but its difficult for Feed Me to know what are products, what are variants, and more (what if those have Super Table or Matrix fields), etc.

So no plan to support this right now, and if added will be quite opinionated in its structure.

**Comment by baronetto** [comment]
I think this is already possible using Feed Me:
1. Create a new custom field e.g. "Import ID" and add it to the product type that has variants
2. Create new line for each product variant
3. Make sure "Import ID" is the same for variants of the same product
4. Under "Import Strategy" of Feed Me check both: "Create new elements" and "Update existing elements"
5. Under "Set a unique identifier to match against existing elements" check the field you created in step 1: eg. "Import ID"
6. Map all other fields as you would normally do with a non-variant import
7. Make sure you have an extra column for the "Is Default" field and that only one of the variants has that value to 1

So far my imports have been successful.

**Comment by j-greig** [comment]
Somehow missed this before, thank you @baronetto !

Would be great to mention this in the docs : )
