### ISSUE TITLE
no data for `id` to match an existing element on. Is data present for this in your feed?

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/feed-me#407]
### Description
Receiving this error in the log for C2 version of Feed Me. I've formatted into CSV, XML, RSS and JSON with no luck. Trying to update existing entries by adding a category to them. Entry data was exported from Craft with IDs and slugs, and trying to match on either one doesn't match. For XML and RSS I've tried setting primary element to nothing and to item.

_[error] [plugin] [Forced] Entry: no data for `id` to match an existing element on. Is data present for this in your feed?_

Files attached

Screenshots: https://d.pr/i/WlN4Zb https://d.pr/i/f5nHCM https://d.pr/i/5KUbQw

Also note that the channel name is Assets - this site is a digital asset manager system. Craft Assets have been renamed Files.

### Steps to reproduce

1. Create feed definition
2. Run feed

### Additional info

- Plugin version: Feed Me 2.0.13
- Craft version: Craft CMS 2.7.2
[Archive.zip](https://github.com/verbb/feed-me/files/2474629/Archive.zip)
[feedme.log](https://github.com/verbb/feed-me/files/2474633/feedme.log)

**Comment by engram-design** [comment]
@chadcrowell I can't tell from your screenshots, but are you including "Entry ID" in your import? You must include that in your mapping, otherwise Feed Me doesn't know about it.

**Comment by chadcrowell** [comment]
I tried that before, and again today, with the id field named both id and Entry ID, and tried also using the slug, which is also in the import file. The Archive.zip file in the original post includes versions of the import files I've tried.

**Comment by angrybrad** [comment]
Going to assume this is stale now with the architecture changes in Craft 3 and the latest Feed Me, but comment back and we can re-open if it's still an issue on the latest.
