### ISSUE TITLE
Allow feeds to use OAuth as authentication

### ISSUE THREAD

**Issue by engram-design** [craftcms/feed-me#420]

**Comment by janmeeus** [comment]
@engram-design Any news on the progress of the OAuth implementation?

**Comment by pieter-janDB** [comment]
Bump, Is it yet possible to import from google sheets API using OAuth ?

**Comment by siebird** [comment]
I have a use case for this with Zoom's API which requires `oauth2`. I could probably hack something together with [OAuth 2.0 Client](https://github.com/venveo/craft-oauthclient) and point FeedMe to a template.

**Comment by mark-chief** [comment]
Bumpety Bump -  this would be awesome!
