### ISSUE TITLE
Table doesn't import deeply nested data

### ISSUE THREAD

**Issue by jorenvanhee** [craftcms/feed-me#464]
### Description

Importing deeply nested data into a table or supertable field does not work.

This works:
```
[
  {
    "title": "Test1",
    "level0": {
      "items": [
        {
          "value": "value1",
          "key": "key1"
        },
        {
          "value": "value2",
          "key": "key2"
        }
      ]
    }
  }
]
```

This doesn't:
```
[
  {
    "title": "Test1",
    "level0": {
      "level1": {
        "items": [
          {
            "key": "key1",
            "value": "value1"
          },
          {
            "key": "key2",
            "value": "value2"
          }
        ]
      }
    }
  }
]
```

### Steps to reproduce

1. Add a content type with a table and supertable field (columns key and value for instance)
2. Try to import data from both snippets

### Additional info

- Plugin version: 3.1.3
- Craft version: 3.1.8

**Comment by xhuang9** [comment]
I have the same issue here. 
Mine is I couldn't feed a Json format data into a table field of commerce variant.

Here is my test data.

```
[
   {
       "productGroup": "1101060",
       "title": "Coopers Premium Light 355mL Bottle",
       "shortDescription": "",
       "richDescription": "",
       "variants": [
           {
               "location": "Richmond",
               "SKU": "1101060-14",
               "stock": "199",
               "price": "10",
               "table": [
                   {
                       "image": "[\"COOP_9310441003944-1.jpg\"]",
                       "size": "355mL",
                       "price": "1",
                       "barcode": "9310441003944"
                   },
                   {
                       "image": "[\"COOP_9310441003951-1.jpg\"]",
                       "size": "6 x 355mL",
                       "price": "1",
                       "barcode": "9310441003951"
                   },
                   {
                       "image": "[\"COOP_9310441003968-1.jpg\"]",
                       "size": "",
                       "price": "1",
                       "barcode": "9310441003968"
                   }
               ]
           },
           {
               "location": "Highton",
               "SKU": "1101060-16",
               "stock": "121",
               "price": "10",
               "table": [
                   {
                       "image": "[\"COOP_9310441003944-1.jpg\"]",
                       "size": "355mL",
                       "price": "1",
                       "barcode": "9310441003944"
                   },
                   {
                       "image": "[\"COOP_9310441003951-1.jpg\"]",
                       "size": "6 x 355mL",
                       "price": "1",
                       "barcode": "9310441003951"
                   },
                   {
                       "image": "[\"COOP_9310441003968-1.jpg\"]",
                       "size": "",
                       "price": "1",
                       "barcode": "9310441003968"
                   }
               ]
           },
           {
               "location": "Boland St",
               "SKU": "1101060-20",
               "stock": "6",
               "price": "10",
               "table": [
                   {
                       "image": "[\"COOP_9310441003944-1.jpg\"]",
                       "size": "355mL",
                       "price": "1",
                       "barcode": "9310441003944"
                   },
                   {
                       "image": "[\"COOP_9310441003951-1.jpg\"]",
                       "size": "6 x 355mL",
                       "price": "1",
                       "barcode": "9310441003951"
                   },
                   {
                       "image": "[\"COOP_9310441003968-1.jpg\"]",
                       "size": "",
                       "price": "1",
                       "barcode": "9310441003968"
                   }
               ]
           }
       ]
   }
]
```

Feed Me version: 3.1.15
Feed Me Pro vesion: 3.0.4
Craft Commere Version: 2.1.2
Craft Version: 3.1.17.2

**Comment by McCrisp** [comment]
I have a similar problem with a matrix field containing a table in XML:

`<?xml version="1.0" encoding="UTF-8" ?>
<recipies>
    <recipie>
        <status>live</status>
        <created>2018-10-04</created>
        <title>Karamellpudding med bær, krem og ristede nøtter</title>
        <image>https://www.norturaproff.no/assets/images/karamellpudding-porsjon-1-168312_181004_104141.jpg</image>
        <dish>Dessert</dish>
        <time />
        <portions>1</portions>
        <concept />
        <groups>
            <group>
                <title>Sauce</title>
                <ingredients>
                    <ingredient>
                        <title>Sukker</title>
                        <amount>1.00</amount>
                        <unit>dl</unit>
                    </ingredient>
                    <ingredient>
                        <title>Melk</title>
                        <amount>6.00</amount>
                        <unit>dl</unit>
                    </ingredient>
                </ingredients>
            </group>
            <group>
                <title>Sukkersaltede nøtter og frø</title>
                <ingredients>
                    <ingredient>
                        <title>Sesamfrø</title>
                        <amount>1.00</amount>
                        <unit>ss</unit>
                    </ingredient>
                    <ingredient>
                        <title>Gresskarkjerner</title>
                        <amount>3.00</amount>
                        <unit>ss</unit>
                    </ingredient>
                </ingredients>
            </group>
        </groups>
    </recipie>
</recipies>`

Only one ingredient per "group" is imported. The rest is ignored.

Matrix field:
![Screenshot 2019-05-13 at 13 50 15](https://user-images.githubusercontent.com/13944443/57619525-6873d580-7586-11e9-9b8a-b8d0d35d5413.png)

FeedMe:
![Screenshot 2019-05-13 at 13 53 41](https://user-images.githubusercontent.com/13944443/57619599-8b05ee80-7586-11e9-8cd8-e29cc1ff5ecd.png)

FeedMe Pro version: 4.1.0
Craft CMS 3.1.26

**Comment by internetztube** [comment]
Same issue over here. Any news @brandonkelly?

**Comment by paulweareframework** [comment]
Same issue with product variant table feeds being ignored.
Have tried a multitude of data setup combos but always gets ignored.

I thought it might be Hash::get($fieldInfo, 'field') within craft\feedme\services\Process

But it is not unless go further into seeing how it keeps processing and matching up fields. 

So I thought its lines 345-348 with the foreach loop of:
```
// Then, do the same for custom fields. Again, this should be done after populating the element attributes
        foreach ($feed['fieldMapping'] as $fieldHandle => $fieldInfo) {
```
Of course I am probably completely wrong as Im just starting to look through but yeh it comes back empty

If i find a quick fix I'll post later

**Comment by internetztube** [comment]
I replaced the table with a matrix field. That worked well with very little adoption in the template.

**Comment by paulweareframework** [comment]
That I might do then! But Im in the middle of stepping through it all so will update if I find a resolution. Otherwise admit defeat and go matrix!

**Comment by internetztube** [comment]
A few months ago I also dug through the code. I was able to isolate the issue but wasn’t able to fix it.

**Comment by paulweareframework** [comment]
Oh it sounds like then I am doomed to the same fate.
Part of me thinks its what I got to and maybe the field not being recursive to check for the table field?

Or the format of the table data nested just doesn't get picked up in variants array

**Comment by paulweareframework** [comment]
Oh hang on, its the CommerceProduct class itself in elements. I've got to the ComplexFields and their is a check for matrix field.

Did you get similar, wondering if just mush in a check for table?

**Comment by internetztube** [comment]
Yes

**Comment by paulweareframework** [comment]
So I got it working for me, however it is not a fully tested use case! This of course gave me successful output and imported

So withing the file **craft\feedme\elements\CommerceProduct** go to the method **private function _parseVariants($event)**
and scroll down to about line 262 to where they loop through the feed data and try to match it up with the variantMapping:

```
$isMatrixField = (Hash::get($fieldInfo, 'field') === 'craft\fields\Matrix');
if ($isMatrixField) {
      $complexFields[$variantIndex][$fieldHandle]['info'] = $fieldInfo;
      $complexFields[$variantIndex][$fieldHandle]['data'][$nodePath] = $value;
      continue;
}
```

So below this matrixField being added to complexFields, check for table field and do same
 using these lines:

```
$isTableField = (Hash::get($fieldInfo, 'field') === 'craft\fields\Table');
if($isTableField === true) {
        $complexFields[$variantIndex][$fieldHandle]['info'] = $fieldInfo;
        $complexFields[$variantIndex][$fieldHandle]['data'][$nodePath] = $value;
        continue;
}
```

I ran my import and it all worked as shown in screengrab attached 
<img width="1227" alt="Screenshot 2020-05-28 at 11 39 43" src="https://user-images.githubusercontent.com/46562148/83131796-56ed6500-a0d8-11ea-89d3-1819cbe475e0.png">

I hope this helps anyone else and I would submit a PR but its not fully tested for all use cases and do not wish to waste the teams time in case my solution is not fully correct!

thank you all

**Comment by intelivitadeveloper** [comment]
@paulweareframework 
Thanks your
Tried your solution and its working fine with table field.
Can you please submit a PR?

**Comment by assertzero** [comment]
Is this ever going to get fixed? We ran into this problem for one of our sites.

**Comment by weareframework** [comment]
> Is this ever going to get fixed? We ran into this problem for one of our sites.

Did you try the fix above within the file?



> So I got it working for me, however it is not a fully tested use case! This of course gave me successful output and imported
> 
> So withing the file **craft\feedme\elements\CommerceProduct** go to the method **private function _parseVariants($event)** and scroll down to about line 262 to where they loop through the feed data and try to match it up with the variantMapping:
> 
> ```
> $isMatrixField = (Hash::get($fieldInfo, 'field') === 'craft\fields\Matrix');
> if ($isMatrixField) {
>       $complexFields[$variantIndex][$fieldHandle]['info'] = $fieldInfo;
>       $complexFields[$variantIndex][$fieldHandle]['data'][$nodePath] = $value;
>       continue;
> }
> ```
> 
> So below this matrixField being added to complexFields, check for table field and do same using these lines:
> 
> ```
> $isTableField = (Hash::get($fieldInfo, 'field') === 'craft\fields\Table');
> if($isTableField === true) {
>         $complexFields[$variantIndex][$fieldHandle]['info'] = $fieldInfo;
>         $complexFields[$variantIndex][$fieldHandle]['data'][$nodePath] = $value;
>         continue;
> }
> ```
> 
> I ran my import and it all worked as shown in screengrab attached <img alt="Screenshot 2020-05-28 at 11 39 43" width="1227" src="https://user-images.githubusercontent.com/46562148/83131796-56ed6500-a0d8-11ea-89d3-1819cbe475e0.png">
> 
> I hope this helps anyone else and I would submit a PR but its not fully tested for all use cases and do not wish to waste the teams time in case my solution is not fully correct!
> 
> thank you all

**Comment by angrybrad** [comment]
This is resolved for the next v4 and v5 releases via https://github.com/craftcms/feed-me/pull/1268
