### ISSUE TITLE
Unable to process Feed URL

### ISSUE THREAD

**Issue by stromjoe** [craftcms/feed-me#482]
### Description
Getting "Unable to reach" error messages when trying to move forward to the second step.
"Unable to reach @web/feeds/example.json. Message: cURL error 6: Could not resolve: development.test (Domain name not found) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

I've tried to proceed with different (valid) JSON files using @web, @webroot, static paths like file:///Users/joel/Sites/website/web/feeds/example.json etc. without success.

Not completely sure if it's related to the plugin or if it's some dependancy that is missing from my environment (Running Valet Nginx, PHP 7.0, 7.1, 7.2).

### Additional info

- Plugin version: 3.0.0-beta.21 up to newest version
- Craft version: Craft PRO 3.0.32

**Comment by engram-design** [comment]
I will note that your current version is a little old (currently on 3.1.12), so I'm not sure of the exact version specific details of your release. Filesystem paths and relative paths for instance were only improved recently in the 3.1.x branch.

Rather than using an alias, can you use the full URL to your file - just to test?

**Comment by engram-design** [comment]
Just wanted to follow up on this?

**Comment by stromjoe** [comment]
The full url doesn't work either. We will try to get the site updated for a newer Craft version and a newer FeedMe version afterwards and see if it fixes the issue.

Sorry for not replying earlier!

**Comment by stromjoe** [comment]
Hello

I updated Craft and every plugin, but FeedMe is still giving me the same error. 
The JSON file itself is getting validated, I can access the url normally. Will follow up on this and see if there is something that we could do about it.

![Screenshot 2019-04-03 at 10 57 22](https://user-images.githubusercontent.com/9196774/55462435-67eb3500-55ff-11e9-9f2c-e15761a3928e.png)

**Comment by engram-design** [comment]
The `Domain name not found` is interesting, as it sounds like it can't find `http://*.test` - I imagine the same URL you're running this Craft site on.

**Comment by peirix** [comment]
Just want to chime in on this, as this is happening to me as well. Recently switched from MAMP to Valet, and now my feed isn't working any more. Same error as above. If I try to run the `curl` from terminal it works as expected. So there's probably a setting in the FeedMe curl that is making this happen?

**Comment by angrybrad** [comment]
Guessing this is a DNS/Valet issue. Can you both go through the troubleshooting steps here? https://github.com/laravel/valet/issues/736

**Comment by peirix** [comment]
Adding both `127.0.0.1` and `8.8.8.8` (google dns) to the DNS servers in system preferences solved this issue for me.

**Comment by KatieMFritz** [comment]
For me, `127.0.0.1` had to be my first DNS server, per https://github.com/laravel/valet/issues/736#issuecomment-468723342.

**Comment by angrybrad** [comment]
Going to go ahead and close this and it looks to be environment-specific.
