### ISSUE TITLE
Invalid product ID: 1235 - Variant.php: 316

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/feed-me#496]
If i try to update an existing variant price, i get this error from the logs. I set the unique identifier as the Variant's SKU as the docs said , but it returns this error. I imported it only to one site. i only need to create and update to one site only.

### Steps to reproduce

1.I uploaded this csv file:
            id,product,variant,sku,price,weight
            1235,"Product","Variant","SH200",20.5,100
2.Set the strategy as "Create new elements", it imported successfully.
3. Set the strategy as "Update existing elements", then ran the feed.
4. i get the error in the logs

### Additional info

- Plugin version:3.1.16
- Craft version:3.1.18

**Comment by engram-design** [comment]
Can you confirm what version of Commerce you're on?

**Comment by Sam-Black-0013** [comment]
Commerce is 2.1.2
It just happens if i create the elements to one site.

**Comment by angrybrad** [comment]
Did some testing on the latest releases and I'm not able to reproduce this. Comment back if it's still an issue for you and we'll re-open.
