### ISSUE TITLE
Performance improvement to validate large JSON dataset?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/feed-me#510]
### Description
I have a feed of ~5000 entries that I need to import and—while the import process works great!—[this line that checks if the JSON is valid](https://github.com/craftcms/feed-me/blob/develop/src/datatypes/Json.php#L42) runs really slowly and throws a timeout after a bit. 😕

I was wondering if there's a faster way to check for invalid JSON such as:
```php
json_decode($data)

if (json_last_error() !== JSON_ERROR_NONE) {
    // throw exception
}
```
But I'm not sure if this would be a reasonable way to go about this!

### Additional info

- Plugin version: 3.1.16
- Craft version: Craft Pro 3.1.21.1

**Comment by engram-design** [comment]
Yep, so we had this simple error-checking initially, but it just didn't provide enough useful information on an error. For instance, currently, it should show the specific line and character that the error occurs, rather than "a json parsing error occured."

I'll consider looking at improving this without losing logging info!

**Comment by aaronbushnell** [comment]
Ah, that makes total sense! I suppose it's not all that helpful if all you get is a generic error. Maybe the more verbose checking happens if you're in `devMode` or running the feed in debug mode? 

Thanks for checking into this!

**Comment by aaronbushnell** [comment]
Hey, @engram-design—first off, congrats on Feed Me now being the newest first-party plugin! 

Second, I’m happy to put in a PR for this if that’s helpful, @brandonkelly. I think a more thorough response about JSON errors might be better if devMode (or something similar) was enabled. 

Otherwise, perhaps a simpler, faster check is better for feeds that are pretty sizable?

**Comment by brandonkelly** [comment]
Fixed this for the next release by using `craft\helpers\Json::decode()`, and only calling `Seld\JsonLint\JsonParser::lint()` if there was an error.

**Comment by aaronbushnell** [comment]
Thanks, @brandonkelly!

**Comment by brandonkelly** [comment]
4.1.0 is out now with this.
