### ISSUE TITLE
Entry-Field association option wrong after update to 3.1.17

### ISSUE THREAD

**Issue by EternalBlack** [craftcms/feed-me#511]
### Description

Update from `3.1.16` to `3.1.17` (or `4.0.0`) results in wrong `entry-fields` association options
`3.1.16`
<img width="1212" alt="Screen Shot 2019-04-09 at 16 55 13" src="https://user-images.githubusercontent.com/5805243/55856903-03365a00-5b6c-11e9-9931-66a1f580adaf.png">
`3.1.17` (`4.0.0`)
![Screen Shot 2019-04-09 at 16 54 46](https://user-images.githubusercontent.com/5805243/55856923-0c272b80-5b6c-11e9-8292-3ed41dbe6fc5.png)

### Steps to reproduce

1. Update to `3.1.17` (same with `4.0.0`)
2. Notice that the field that you used before when associating an `entry-field` isn't available anymore.
3. Cry, because this just destroyed your feed.

### Additional info

The fieldtype of the previously matched field is of type [IncognitoField-Craft3](https://github.com/mmikkel/IncognitoField-Craft3). Worked before, but now doesn't seem like it.

- Plugin version: 3.1.17 Pro (and `4.0.0` no "Pro" anymore though ;D)
- Craft version: 3.1.21.1 Pro

**Comment by EternalBlack** [comment]
I hate to bother but this is currently kind of urgent as it is holding back our development. :(

**Comment by engram-design** [comment]
You can get this fix by running `composer require craftcms/feedme:dev-develop` until they release a new version with this fix included.
