### ISSUE TITLE
Unknown property on Digital Products

### ISSUE THREAD

**Issue by peirix** [craftcms/feed-me#513]
### Description
This might be related to: https://github.com/craftcms/feed-me/issues/500
But just in case it's not. When I'm running FeedMe to create Digital Products I'm getting the following error: `Setting unknown property: craft\digitalproducts\elements\db\ProductQuery::sku - Component.php: 209`

### Additional info

- Plugin version: 4.0.0
- Craft version: 3.1.21.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send your `composer.json` and `composer.lock` files, a database backup, and a sample digital product feed over to support@craftcms.com?

**Comment by peirix** [comment]
E-mail sent
