### ISSUE TITLE
Documentation Feed Me for Craft 2

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/feed-me#514]
Not sure if this question belongs here.

Where can I find the documentation for Feed Me in Craft CMS 2? Previous documentation was available at https://verbb.io/craft-plugins/feed-me/v2/ but now redirects to the v4 docs on the Craft website.

I have looked at https://archive.org/ but the page wasn't indexed on there either.

**Comment by jamesmacwhite** [comment]
Google currently has the v2 docs cached, example:

https://webcache.googleusercontent.com/search?q=cache:s55wDdEI_GYJ:https://verbb.io/craft-plugins/feed-me/v2/docs/get-started/installation-setup+&cd=1&hl=en&ct=clnk&gl=uk

However, you are right, they probably should exist somewhere for reference.

**Comment by engram-design** [comment]
ITs not hosted anywhere, and maybe the Craft team are open to a Pull Request, but the docs can be found on my fork: https://github.com/engram-design/feed-me/tree/craft-2-docs/docs
