### ISSUE TITLE
Couldn't install plugin

### ISSUE THREAD

**Issue by michaelbutler1998** [craftcms/feed-me#519]
### Description
'Unable to install plugin' message received when installing feed me.

I have a similar issue to #289, however no solutions of this closed/resolved issue have helped. I have already attempted the following: 

- Removed vendor files, composer.lock, and ran composer update.
- Checked logs (web log has the following issue: $_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1555494782
]

$_SERVER = [
    'HTTP_HOST' => 'localhost'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01'
    'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'
    'HTTP_REFERER' => 'http://localhost/sthelier2019/web/admin/settings/plugins'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,el;q=0.8'
    'HTTP_COOKIE' => 'cookieconsent_status=dismiss; 17e754b5577c6d344b268494db9f31a6username=cac975755733cece0a2260678b2cbf3b78a7ce8ds%3A60%3A%22c62b7b6276d3f8230a4db63f763289fcc9cf132aczo3OiJ0aGVib3NzIjs%3D%22%3B; _ga=GA1.1.1026842141.1542106947; ec7e436d9f03d0e1ba6dbbf95560f9fausername=a749af7a5f4567d18bf3c88a388993f090092145s%3A60%3A%22cc5439fb2f35b64b71b4c9fd8aa9945c25b02a3fczo3OiJ0aGVib3NzIjs%3D%22%3B; bf9629239fb080421735311403804d8cusername=5fc7dd910515ce897ad38f4a064d3dbd423f955as%3A60%3A%22e588812ecd95fcbf04b8923e9095f70e7f3ba649czo3OiJ0aGVib3NzIjs%3D%22%3B; _gcl_au=1.1.1413283715.1547736847; 037f8815ef91f12510f4419a99d19ab0username=925d0334a083ba3101a2d5f10bcc01239adefbafs%3A60%3A%226867d628cc43bb6998037f9022fa6c51db9a9c73czo3OiJ0aGVib3NzIjs%3D%22%3B; f118935b89ba73c5a0cee01190ca73c1username=0f9f46d893c1dd3ea7b5d2b68a8e4d3e568b4d49s%3A60%3A%227e28027b03f7c318b411bcf01a3dad5b99681989czo3OiJ0aGVib3NzIjs%3D%22%3B; dbbedb9f69e16c5f3eeff4b5e5518b1cusername=d9a81d7ec48c357aed7b94e05a096c4d1e2bcb9ds%3A60%3A%2298dbc99134b5154bc2028ac51983b30acf74e5f2czo3OiJ0aGVib3NzIjs%3D%22%3B; d94415bb0806dd0485f2e0968e74d6dfusername=a7609d69a22d3db0e47564398ac812f1c2799129s%3A60%3A%22430706ae98310a4de6d4c0f14125877ed0fcc00fczo3OiJ0aGVib3NzIjs%3D%22%3B; 125812c3033adbaea249f52e56629e67username=1892dae8694ff6354475b0c20b7fec627d8b7405s%3A60%3A%22219117a1f442e3107bccf4b383bdf3466a2f7edfczo3OiJ0aGVib3NzIjs%3D%22%3B; favjobs=%2C12409; e6de4bf3da9d55234199646ab89e892ausername=60d0a91b5c56100667dac11016fcb0146c52d53cs%3A60%3A%22a21bbda9041cf3ed9184c8f23946e24ccaefaa68czo3OiJ0aGVib3NzIjs%3D%22%3B; __utmz=111872281.1554813896.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=111872281.1026842141.1542106947.1554813896.1554882360.2; 59d0288c559dc851aae5f1fa7b175ca6username=05f6dd249c63899f7f772a7534ad0824ec3a4b94s%3A60%3A%22ce6edd14a46c4929c063af0313e882629a3c4e28czo3OiJ0aGVib3NzIjs%3D%22%3B; mp_d30e7d7c20d8cf1b3334509f9ca97423_mixpanel=%7B%22distinct_id%22%3A%20%2216a258bc7a1218-05f5f0371802c7-366b7e03-1aeaa0-16a258bc7a2c9f%22%2C%22%24device_id%22%3A%20%2216a258bc7a1218-05f5f0371802c7-366b7e03-1aeaa0-16a258bc7a2c9f%22%2C%22%24initial_referrer%22%3A%20%22http%3A%2F%2Flocalhost%2Fplugin-postcode%2Fweb%2Fadmin%2Flogin%22%2C%22%24initial_referring_domain%22%3A%20%22localhost%22%7D; 1031b8c41dfff97a311a7ac99863bdc5_username=31035b6effd71a55613a093081a40cf5f0cd11b5a79c00331521c4e319b1c6e4a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A7%3A%22theboss%22%3B%7D; CraftSessionId=ac05662793bc6c4b3f2b93697ceb26e9; 1031b8c41dfff97a311a7ac99863bdc5_identity=077146d92a1aba972801502765ca7c626aaebff071c37c2525f67c19c5e00b75a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A250%3A%22%5B%221%22%2C%22%5B%5C%22V5r6-DroUU07HkgsPkk2GjJgXGJ3Dnntl6NmNZDsNVTB0rlCyZKhXGEUPjrbma8g1J8H1GWZX0xrbsbQ-h9Uzjk8lf0GHXpSN54W%5C%22%2Cnull%2C%5C%22Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_13_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F73.0.3683.103+Safari%2F537.36%5C%22%5D%22%2C3600%5D%22%3B%7D; CRAFT_CSRF_TOKEN=a742dae5237e1f558b04c2aa8f5070399d2ffeaea55aa505b877ebc96cda0e3ba%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A40%3A%22qDx3YyPvzymOSc2YnRwzuAZPf3L3sUAFs665Ul4d%22%3B%7D'
    'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0'
    'SERVER_NAME' => 'localhost'
    'SERVER_ADDR' => '::1'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '::1'
    'DOCUMENT_ROOT' => '/Applications/MAMP/htdocs'
    'SERVER_ADMIN' => 'you@example.com'
    'SCRIPT_FILENAME' => '/Applications/MAMP/htdocs/sthelier2019/web/index.php'
    'REMOTE_PORT' => '62379'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'p=admin/actions/users/get-remaining-session-time&dontExtendSession=1'
    'REQUEST_URI' => '/sthelier2019/web/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1'
    'SCRIPT_NAME' => '/sthelier2019/web/index.php'
    'PHP_SELF' => '/sthelier2019/web/index.php'
    'REQUEST_TIME_FLOAT' => 1555491182.02
    'REQUEST_TIME' => 1555491182
    'argv' => [
        0 => 'p=admin/actions/users/get-remaining-session-time&dontExtendSession=1'
    ]
    'argc' => 1
    'ENVIRONMENT' => 'dev'
    'SECURITY_KEY' => '•••••••••••••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'mysql'
    'DB_SERVER' => 'localhost'
    'DB_USER' => 'theboss'
    'DB_PASSWORD' => '••••••••••'
    'DB_DATABASE' => 'sthelier'
    'DB_SCHEMA' => 'public'
    'DB_TABLE_PREFIX' => 'craft'
    'DB_PORT' => ''
])

### Steps to reproduce

1. Navigate to /manage/settings/plugins
2. Select install on the Feed Me plugin

### Additional info

- Plugin version: 4.0.0
- Craft version: 3.1.22

**Comment by angrybrad** [comment]
Can you reproduce this with devMode enabled, then zip up your `storage/logs` folder and send it to support@craftcms.com so we can look into it?

**Comment by moyger** [comment]
I'm also having issue install FeedMe. Same error "Couldn't install plugin". I have the latest CraftCMS version 3.1.32.1. Did everything and do a composer update/require but still no luck. Any help, appreciate it very much.

**Comment by brandonkelly** [comment]
@moyger Same suggestion to you: https://github.com/craftcms/feed-me/issues/519#issuecomment-485979703

**Comment by cityzen** [comment]
Is there any way to troubleshoot this issue locally? Were you all able to figure anything out?

**Comment by cityzen** [comment]
My issue was that I installed feedme on the remote dev server, synced dbs, tried to install locally and it failed since the table existed.

**Comment by michaelbutler1998** [comment]
@cityzen @moyger @angrybrad 

I ended up taking @angrybrad 's advice and was assisted by Oli Bon at Craft support.

His advice was to remove composer.lock, change the Craft version in my composer to one that was at the time more up to date (in this case, I was told to change the version in my composer to "craftcms/cms": "^3.1.0" and then delete all vendor files.

Following this, I was told to run composer update followed by "./craft migrate/all" which caused the site to go to the craft version 3.1.33 without any issues.

I was then told to update all plugins using "./craft update all"

Following this, I still had issues. I was told to remove my vendor files once more along with composer.lock and run "composer install".

This produced the desired effect. I was then able to install the plugin upon attempting it.

Apologies for the late reply guys, hope this helps. If not, follow @angrybrad's advice yourself also, the support was extremely fast (replies were within 15 minutes every time).

**Comment by MattWilcox** [comment]
Just had the same issue and unfortunately nothing suggested in this thread is working. Have mailed support.

**Comment by olivierbon** [comment]
This could happen if you had Feed Me previously installed and it wasn't removed properly.

Clearing any `feedme_` prefixed table from the database fixes the issue.

**Comment by lintoncaldecott** [comment]
> This could happen if you had Feed Me previously installed and it wasn't removed properly.
> 
> Clearing any `feedme_` prefixed table from the database fixes the issue.

The hero gotham needs

**Comment by j-greig** [comment]
Just had same issue with the Workflow plugin by Verbb

**Comment by kevinmu17** [comment]
Trying to find the database entries but can't find them, can you point me in the right direction?
