### ISSUE TITLE
Cant import multiple matrix blocks

### ISSUE THREAD

**Issue by glenndebacker** [craftcms/feed-me#520]
### Description

Cant seem to insert multiple matrix blocks

### Steps to reproduce

1. create entry json with the following matrix related content

```json
...
"Matrix": {
    "MatrixBlock": [
        {
            "ProjectSizeMatrix": {
                "Amount":  "100",
                "Type": "beds"
            }
        },
        {
            "ProjectSurfaceMatrix": {
                "Surface":  "10000",
            }
        },
    ],
}
...
```

2. Map 

* ProjectSizeMatrix *Amount* (Text) to Matrix/MatrixBlock/ProjectSizeMatrix/Amount"
* ProjectSizeMatrix *Type* (Category) to Matrix/MatrixBlock/ProjectSizeMatrix/Type"
* ProjectSurfaceMatrix *Surface* (Text) to Matrix/MatrixBlock/ProjectSurfaceMatrix/Surface"

3. Execute feed 
4. It will only add a ProjectSurfaceMatrix block. When I don't map the ProjectSurfaceMatrix it will insert the ProjectSizeMatrix block so it seems it just takes the last one that is mapped. 

### Additional info

- Plugin version: 4.0.0
- Craft version: 3.1.23
- Log Output 

Data ready to import (does not seem right) 
```
{
   "projectSize":{
      "new1":{
         "type":"projectsurfacematrix",
         "enabled":true,
         "collapsed":false,
         "fields":{
            "sizeAmount":"127",
            "sizeType":[
               "847"
            ],
            "surfaceSize":"110000"
         }
      }
   },
   "projectOriginalWpId":"3813"
}
```
- Other format and mapping does not seem to make a difference

```json
...
"Matrix": {
    "MatrixBlock": [
        {
            "ProjectSizeMatrixAmount":  "100",
             "ProjectSizeMatrixType": "beds"
        },
        {
            "ProjectSurfaceMatrixSurface":  "10000"
        },
    ],
}
...
```

- Another thing I noticed *enabled* and *collapse* seems to be ignored
--

**Comment by RienMoeyaert** [comment]
+1 for this issue

**Comment by brandonkelly** [comment]
I’m having a hard time understanding your JSON. Can you please send your `composer.json` and `composer.lock` files, a database backup, and a sample JSON file over to support@craftcms.com, and reference this issue? We can look into it from there.

**Comment by glenndebacker** [comment]
I've mailed you guys the files.

**Comment by olivierbon** [comment]
Resolved in support
