### ISSUE TITLE
Bug when importing decimal number which is not present as an xml node

### ISSUE THREAD

**Issue by davecoggins** [craftcms/feed-me#527]
### Description

After upgrading from feedme 3.0.4 to 4.1 our feed is throwing the following error when importing into a number field with decimal value set to 2:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect decimal value: '[]' for column 'field_rent' at row 1 

To give a bit more context this is a estate agent website that does both sales and rentals. This is effecting only sales properties. In the XML feed a property that is a sales property doesn't have an xml element for rent.

I currently still have FeedmePro 3.0.4 installed, not sure if this could be effecting things.

Many thanks

### Steps to reproduce

1. Create a feed that has 2 elements, one that has a rent xml node and one that doesn't
2. Map the rent xml node to a number field with decimal point set to 2 

### Additional info

- Plugin version: 4.1
- Craft version: 3.1.24

**Comment by Sam-Black-0013** [comment]
I am having the same problem. It won't fill a number field because the value is empty.

**Comment by davecoggins** [comment]
Hi

I've just updated the site (locally) that was solved by this fix but the bug is now back. As you mention in #4849 would you be able to fix this in the feedme plugin instead?

Many thanks

**Comment by davecoggins** [comment]
Hi 

Just wondering if anyone has had chance to take a look at this issue?

Many thanks

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now with a fix for this.
