### ISSUE TITLE
Impossible to set (correct) default value for MultiSelect field

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/feed-me#530]
### Description
A multiselect field expects an array as a default value. Using FeedMe, the default value for a multiselect field can only be set with a dropdown, resulting in a single value. This causes the feed to throw an error on running.

### Steps to reproduce

1. Create an element with a multiselect field
2. Create a feed and try to set two default values for the multiselect field

### Additional info

- Plugin version: 4.1
- Craft version: 3.1.24

**Comment by olivierbon** [comment]
Fixed coming [here](https://github.com/craftcms/feed-me/pull/628)
