### ISSUE TITLE
`Undefined index: parts` when filling in an address in SimpleMap field

### ISSUE THREAD

**Issue by robbeman** [craftcms/feed-me#531]
https://github.com/craftcms/feed-me/blob/7746dcd1c9ba4bb9faf0d665e34a820431cbd2be/src/fields/SimpleMap.php

Several issues in the `parseField` method here:

1. If you fill in an address in the import settings (see screenshot 1).
2. If you do not use google maps for geocoding.

Both will result in the same error (see screenshot 2).

## Missing address parts (1)

Because you fill in the address there will be made no effort to fetch the address parts, as this is skipped by https://github.com/craftcms/feed-me/blob/7746dcd1c9ba4bb9faf0d665e34a820431cbd2be/src/fields/SimpleMap.php#L52. This will cause the `MapField` to complain about the missing parts value.

## No google maps (2)

When not using google maps (using Nominatim for now) in simple maps and thus you do have not set an API key, `_getAddressFromLatLng` will fail silently and then later on it will throw missing parts error again.

Throwing a more specific error (in `_getAddressFromLatLng`) to state that getting the address failed would already be quite an improvement. (Less debugging effort.) Otherwise it might be an option to use `ether\simplemap\services\GeoService` since the `addressFromLatLng` method is public.

**Screenshots**:

![image](https://user-images.githubusercontent.com/3245659/57075165-507a9700-6ce6-11e9-930f-5ad6599af38c.png)

![image](https://user-images.githubusercontent.com/3245659/57074722-0218c880-6ce5-11e9-91f0-f37a108530c4.png)

**Comment by robbeman** [comment]
On a side note: I tried filling in the parts by adding an event listener, but that did not seem to do much. Not sure if the before and after parse events allow manipulating the data, docs are a little unclear about that.

        Event::on(Fields::class, Fields::EVENT_BEFORE_PARSE_FIELD, function (FieldEvent $e) {
            if ($e->fieldInfo['field'] === MapField::class) {
                $e->parsedValue = [];
                $e->parsedValue['parts'] = [
                    'number' => $e->feedData['Address number'],
                    'address' => $e->feedData['originalStreet'],
                    'city' => ($e->feedData['Address municipality'] ? $e->feedData['Address municipality'] . ', ' : '') . $e->feedData['Address city'],
                    'postcode' => $e->feedData['Address postal code'],

                    // Always Belgium 🇧🇪
                    'country' => 'België',
                ];
            }
        });

**Comment by pdaleramirez** [comment]
I checked the code for the latest v4, and it has been modified to fix this issue.
