### ISSUE TITLE
Error with GeoCoding when importing to SimpleMap field 

### ISSUE THREAD

**Issue by rgbjay** [craftcms/feed-me#533]
When I am importing a record into a SimpleMap field with just an Address. I get the following error:

`Call to undefined method ether\simplemap\services\MapService::getLatLngFromAddress() - SimpleMap.php: 70`

I am using Google Maps service and Google Maps for GeoCoding with a new unrestricted API key (for dev purposes).

### Steps to reproduce

1. Import a record with just an address (no latlng)

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.25

**Comment by rbaud** [comment]
I can confirm that we're also seeing this issue with Craft v3.1.29, Feed Me v4.1.0 and SimpleMap v3.4.11.

**Comment by rbaud** [comment]
Simplemap has been updated to [3.5.0](https://github.com/ethercreative/simplemap/tree/3.5.0), with stated support for FeedMe. I assume that that will fix this issue, but have yet to test.

**Comment by rgbjay** [comment]
Yes our issue is solved now with the latest version of the plugin.
