### ISSUE TITLE
Sitemaps regenerated on import

### ISSUE THREAD

**Issue by clarknelson** [craftcms/feed-me#538]
### Description

When running a feed import, the sitemap is regenerated PER IMPORT (if there are 20 entries being added, the sitemap generation is run 20 times.) It has been confirmed that this is an issue with how Feedme interacts with the SEOmatic plugin. See Andrew's comment in the discord group:

![image](https://user-images.githubusercontent.com/4106671/57723892-45f9bf00-764f-11e9-8038-a28491cd0510.png)

### Steps to reproduce

1. Install SEOmatic & Feedme
2. Run import

### Additional info

- Plugin version: 4.0
- Craft version: 3.0.31

**Comment by pdaleramirez** [comment]
I can’t seem to replicate this issue. When I tested it on version 4.6.1.1, it only ran `Sitemap::generateSitemap` once. We’ll re-open the case if someone reencounters this.
