### ISSUE TITLE
Default entry status is ignored

### ISSUE THREAD

**Issue by nilsnh** [craftcms/feed-me#541]
### Description

This might be related to #270, #469 and #234 . 

### Steps to reproduce

1. Create Craft section with default status 'disabled'.
2. Setup feed with "don't import" set on status.
3. Run import and see that entries have default status 'enabled'.

### Additional info

- Plugin version: 4.1.0
- Craft version: Craft Pro 3.1.26

**Comment by nilsnh** [comment]
More information. I have two feeds set to import to the same section one for English and one for Norwegian (primary site).

The feeds were originally set to default status disabled and to import to the English and Norwegian site.

I now tried to set one feed from Norwegian, to **primary site Norwegian** and now the entries are successfully imported with default status set to disabled. Hope this can help debug this issue. The issue might be with primary site import vs. regular site import.

![image](https://user-images.githubusercontent.com/282865/57853141-4a57e080-77e5-11e9-8b9f-78a04057f061.png)

**Comment by icreatestuff** [comment]
I'm having a similar issue. When I choose to not import anything for the status and instead specify a status (Disabled in my test cases) from the dropdown, this doesn't get applied and all entries show as enabled once imported.

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now with a fix for this.
