### ISSUE TITLE
Bug - Users always saved because of newPassword

### ISSUE THREAD

**Issue by ghost** [craftcms/feed-me#544]
### Description
Users are always being saved because the newPassword value doesn't match the external value. This makes sense but this also makes the import process very slow when importing 900+ users. 

Pretty sure checking the hashed password field like when logging in could solve this. However this might be unsafe, thats up to you to decide.

### Steps to reproduce

1. Create user import with password sync
2. Run feed update

### Additional info
Log message: ↳ User import 1: Data to update for newPassword: "secret".

- Plugin version: 4.1.0
- Craft version: 3.1.28

**Comment by pdaleramirez** [comment]
No new user should be created when you set the Import strategy to "Update existing elements" and Set a unique identifier to match against existing elements to "Username".
