### ISSUE TITLE
Feed Me Breaks If New Commerce Product Type is Added 

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/feed-me#550]
### Description

Create a new feed, go back to create a new product type inside Commerce, Feed Me errors out and complains.

``Argument 1 passed to craft\commerce\services\ProductTypes::getProductTypeById() must be of the type integer, string given, called in /path/to/vendor/twig/twig/src/Extension/CoreExtension.php on line 1687``

### Steps to reproduce

1. Setup a feed inside Feed Me.
2. Save the feed for later.
3. Create a new product type inside Commerce.
4. Visit the main FeedMe Feeds page, get the error.

Workaround: removed old feeds in the database manually.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/commit/8cd6d787a70434a564ee9ccb3393b5106b46ba51
