### ISSUE TITLE
Can't unset category relationship

### ISSUE THREAD

**Issue by keyurshah** [craftcms/feed-me#551]
### Description
In a previous feed import, i set the value of the field to a slug matching the category relationship.

In a later feed, I want to unset this relationship value, but I am unable to do so. 

I have tried to set the value to the following, but the relationship value does not get removed.  
* `null`, 
* `[]`, 
* `""`

### Steps to reproduce

1. Add a new category (`material`)
2. Add a new category (`collections`)
3. Add a field for `collections` that is a category relationship field to `material`
4. Run a json feed for `collections` with a value for the relationship field that matches a slug value for `material`
5. Change the json feed to remove the value relationship field value for the `material` field
6. View the category, and see that the relationship value has not been removed / unset.

### Additional info

- Plugin version: 4.1
- Craft version: 3.1.28

**Comment by i-just** [comment]
Starting with versions 4.6.0 and 5.1.0, there’s a new “Set empty values” setting. When enabled, empty values are considered valid and will be used to replace existing data. When disabled, empty values are ignored. I hope this helps!
