### ISSUE TITLE
Redis Queue Error

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/feed-me#553]
### Description
We've set up a separate server for Redis and modified our config/app.php file accordingly. Everything works until we try to use feedme which complains about Calling unknown method on yii\queue\redis\Queue::getHasReservedJobs(), the relevant part of our config/app.php file looks like so:

```
'staging' => [
    'components' => [
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => 'localhost',
            'port' => 8000,
            'password' => getenv('REDIS_PASSWORD'),
            'database' => 0,
        ],
        'session' => [
            'class' => yii\redis\Session::class,
            'as session' => [
                'class' => craft\behaviors\SessionBehavior::class,
            ],
        ],
        'cache' => [
            'class' => yii\redis\Cache::class,
            'defaultDuration' => 86400,
        ],
        'queue' => [
            'class' => \yii\queue\redis\Queue::class,
            'channel' => 'queue',
        ],
    ],
]
```

When we comment out the 'queue' array, feedme works without issue. We've not encountered any issues with other plugins which use queues such as seomatic and imager. Initial thoughts are that because feedme posts to a page which shows a queue when it runs, an issue would also arise from no front end queue progress when using redis as detailed here: https://github.com/craftcms/cms/issues/3171

Would it be possible to detect if redis is in use for the queue, and then to post to a page without a progress indicator and also skip the conditional which is causing the error on line 18 of templates/feeds/_status.html? I've attached a screenshot displaying the full error we are seeing when trying to save or run an existing feedme feed.

<img width="1378" alt="Screenshot 2019-06-12 at 15 37 10" src="https://user-images.githubusercontent.com/15085874/59365522-950b4080-8d30-11e9-9dce-a761453cf88d.png">

We'd still like to use Redis for our queues so any guidance or suggestions to fix this would be appreciated, thank you.

### Steps to reproduce

1. Modify config/app.php to use Redis for the queue
2. Save an existing feed or try to create a new feed
3. Encounter error screen

### Additional info

- Plugin version: 4.1.0
- Craft version: Craft Pro 3.1.29

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now with a fix for this. Thanks for reporting!
