### ISSUE TITLE
Children of disabled parents will become orphaned

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/feed-me#555]
### Description

If the _parent_ category is **disabled**, Feed Me won't place the _child_ category beneath it.

Instead, the child category will become orphaned, and pushed to the bottom of the list.

**ORIGINAL SOURCE**
<img width="282" alt="Ω 2019-06-13 at 4 02 48 PM" src="https://user-images.githubusercontent.com/5309692/59473261-84250280-8df6-11e9-8212-e3b5d6aee16f.png">

**IMPORT DESTINATION**
<img width="298" alt="Ω 2019-06-13 at 4 03 14 PM" src="https://user-images.githubusercontent.com/5309692/59473269-930bb500-8df6-11e9-950c-59a9e31871f2.png">

Specifically, pay attention to the "Die Sets" and "Thermal Oxidizer" categories. You'll notice that they were not ported beneath their parent categories.

Instead, they were orphaned and dropped to the bottom of the list...
<img width="191" alt="Ω 2019-06-13 at 4 03 52 PM" src="https://user-images.githubusercontent.com/5309692/59473307-ca7a6180-8df6-11e9-96e3-5b55843ff8ba.png">

If you look at the feed, you'll notice that the feed _is correct_, and properly shows the intended parent category ID...
<img width="277" alt="Ω 2019-06-13 at 4 18 06 PM" src="https://user-images.githubusercontent.com/5309692/59473342-fc8bc380-8df6-11e9-99e4-f35593b5bb42.png">

### Steps to reproduce

1. Create a source with nested categories. Disable some of the _parent_ categories.
2. Configure an import which copies the nested structure of your original categories.
3. Run import feed.
4. Notice that _enabled_ parents get their correct children, but _disabled_ parents do not. The children of disabled parents get orphaned, and shoved to the bottom.

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.30

**Comment by BenParizek** [comment]
We demand justice!

**Comment by lindseydiloreto** [comment]
Do it for the children!

**Comment by angrybrad** [comment]
@lindseydiloreto @BenParizek justice is slow, but always prevails.

Resolved in https://github.com/craftcms/feed-me/pull/1303 for the next v4 and v5 releases.

**Comment by angrybrad** [comment]
We just released Feed Me 4.6.3. and 5.1.3 with this fix.
