### ISSUE TITLE
Search not returning all results

### ISSUE THREAD

**Issue by rgbjay** [craftcms/feed-me#556]
### Description

We have a fairly standard search field on our installation that utilises one keywords field. We have noticed that there is some weird behaviour when we search more multiple keywords in a title. For some entries they appear in the search results fine but other don't with no discernible differences between them in the database.

### Steps to reproduce

For the faulty entry:
1. go to https://www.visitsouthampton.co.uk
2. Enter 'young ones' into the search bar
3. hit return/click the search icon
4. no results will show

For an entry that does show:
1. go to https://www.visitsouthampton.co.uk
2. Enter 'sculpture at beaulieu' into the search bar
3. hit return/click the search icon
4. the entry will show in the results

As mentioned before there is no noticeable difference between the two in the db (hidden characters etc) so i am alittle stumped at what would cause this. The keywords for the young ones event are also present in the `searchindex` table in the database.

The twig code to handle the search is:

`{% set entries = craft.entries.section('and, not userGuide, not miscellaneous').search(keywords).limit(10).orderBy('score') %}`

### Additional info
- Craft version:  3.1.25

**Comment by olivierbon** [comment]
This looks resolved on the live site.
