### ISSUE TITLE
Some Category Field Relationships Not Being Saved on Import

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/feed-me#557]
### Description

This one is hard to describe because I can't find a common pattern so I'll just try to describe the conditions... I have a few "update only" imports to sections with entry types that contain multiple category relationship fields. Regardless of whether the category field is set to accept 1 branch selection or an undefined limit, I use an array of category titles to identify the existing categories. For some reason, most of these category fields save fine during the imports. But I have two fields in particular where the category relationship is not being saved. The only thing the two category fields have in common is that they were added after the original imports took place.

I checked the FeedMe log file and I see that the the plugin is successfully retrieving category element IDs for the titles I am passing along and it is attempting to save that to the entry in the same format as the other category fields that work just fine. The entry successfully updates without logging any errors yet those few problematic category fields have empty values in the control panel list view AND the control panel entry edit form.

In both cases, the category field points to a category group that is completely flat (no category hierarchy).

The queue log contains nothing that appears to be relevant to saving entry-category relationships. I see no error messages.

### Steps to reproduce

1. I'm not doing anything special. It's just a JSON feed that runs an update only import to an entry section.

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.28

**Comment by benjaminkohl** [comment]
Is it possible that the issue could be related to the fact that the first entry in the feed has an empty array as the value?

**Comment by brandonkelly** [comment]
Can you send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com? And if the feed URL isn’t public, send a copy of the feed as well.

**Comment by leehaskings** [comment]
I'm not sure if this is related but we had an import that was populating one category field but not another. If we set it to 'create new' it would then create a lot of duplicates.

It wasn't until I was pruning through the logs and I picked up the below difference being driven by the 'branchLimit' for the category field:

**Category1 field (Branch limit empty)**
Search for existing category with query
{"status":null,"groupId":4,"limit":"","where":["=","title","Fruit"]}

**Category2 field (Branch limit 0)**
Search for existing category with query
{"status":null,"groupId":3,"limit":"0","where":["=","title","External"]}

Looking at the categories class for the plugin, it setting the query 'limit' to 0 (based on branch limit) and hence always returning no existing categories:

`$criteria['limit'] = $branchLimit;`

The category we're using doesn't have branches so the 0 was probably a mistake on our end, but I wouldn't have thought it should be the value used for the query limit?

**Comment by pdaleramirez** [comment]
This is an old issue, and without the JSON file, it would be hard to debug the issue. I suggest creating a new issue with the JSON feed attached to replicate the problem.

**Comment by benjaminkohl** [comment]
Sorry, I must have stopped getting notifications for this issue back when it was still relevant. A lot of my github notifications go to spam. In any case, I don't even remember which site this was for and I am sure it got worked out somehow.
