### ISSUE TITLE
Add the ability to cancel a Feed Me queue job.

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/feed-me#558]
### Description

I have an import running that I know is at least 50 pages of records. If after the first page completes I see that the import isn't going as planned, I'd like to able to cancel the rest of the import. I try removing the queue record from the table but it keeps getting added back. I even disabled my web server and restarted it but it just picks up where it left off.

### Steps to reproduce

1. Run import.
2. Try to delete queue record from queues DB table.
3. Queue record magically reappears.

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.30

**Comment by john-henry** [comment]
This particular issue is driving me insane. Where might we stop this in the meantime before this enhancement happens?

**Comment by max8hine** [comment]
I am in favour of this. the cancelability to both scheduled pagination and current queue job is very important, especially when the error occur and there is no way to cancel it.

**Comment by angrybrad** [comment]
In Craft 3.5+ you can cancel queue jobs from the Queue Manager utility.
