### ISSUE TITLE
N-dash being dropped from import

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/feed-me#560]
### Description

I have a CSV file that includes a field for a range of ages. In the data dump, it is formatted like this "10 – 20". That bar between the numbers is _not_ a hyphen though, it is an **n-dash** symbol. When I try to import that into a Craft plain text field, I get "10  20", with the **n-dash** removed. 

The field type this cell of data is to be imported into is a Plain Text field. 

### Steps to reproduce

1. Import a cell from a CSV with an n-dash character in it.
2. Check resulting data in Craft.

### Additional info

- FeedMe version: 4.1.0
- Craft version: 3.1.30

**Comment by brandonkelly** [comment]
Just gave this a whirl and wasn’t able to reproduce it. Maybe the dash isn’t actually an n-dash, and some other special character that isn’t supported by the database?

**Comment by johnfmorton** [comment]
Thanks for checking. I’ve asked my client to remove the character which appeared to be an N-dash and replace it with a hyphen. I wonder if their could be database differences that might have been causing it. Just guessing at that though.
