### ISSUE TITLE
isAbsoluteUrl TypeError when importing a user photo from a url when a default is set

### ISSUE THREAD

**Issue by Tam** [craftcms/feed-me#562]
### Description
`isAbsoluteUrl` throws a TypeError when importing a user photo from a url with the Create asset option selected, and a default asset defined.

```
Argument 1 passed to craft\helpers\UrlHelper::isAbsoluteUrl() must be of the type string, array given, called in /var/www/html/vendor/craftcms/feed-me/src/elements/User.php on line 189
```

### Steps to reproduce

1. Setup an import for Users where `photo` is set to a url, create asset is checked, and a fallback is specified.
2. Try to import

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.31

**Comment by brandonkelly** [comment]
Thanks for reporting, just fixed this for the next release.

To get the fix early, change your `craftcms/feed-me` requirement in composer.json to:

```json
"require": {
  "craftcms/feed-me": "dev-develop#53cd568e86665aadaffeda8b91b339bf34d0c504 as 4.1.1",
  "...": "..."
}
```

Then run `composer update`.
