### ISSUE TITLE
Sites within same group and translatable per group, are not updated on import

### ISSUE THREAD

**Issue by amityweb** [craftcms/feed-me#564]
I have a group, Spanish, in which are 4 sites, Spain, Brazil, Mexico and Colombia. 
The fields are set to be translateable per group. 
I run a feed to import content into Spain and that works fine
When I create a new site, such as Brazil, the content from Spain is copied over as expected.
Then I added a new field for my entries. 
I updated the FeedMe feed to link the new field to the feed
I imported Spain again
The Spain site had the new field entered with content OK
The other spain sites do not have data in the field, it is empty.

So it seems the fields are duplicated on creating the site as expected, but they are not when importing using FeedMe. 

Craft CMS 3.1.29
Feed Me 4.1.0

**Comment by amityweb** [comment]
Looking into this further, I guess FeedMe does not initiate a resave of entries which is needed. 

In the meantime discovered this command which will do the job:
`php craft resave/entries --section=Pages --site=es`

Note usage of --section and --site to ensure only the correct ones are processed. 

The resave results in the new field being duplicated. 

Would be good if FeedMe builds this in I guess?

**Comment by brandonkelly** [comment]
This is fixed for the next release.

To get the fix early, change your `craftcms/feed-me` requirement in composer.json to:

```json
"require": {
  "craftcms/feed-me": "dev-develop#bd2faaf667b1547cdc5f73052e85d52a12543bab",
  "...": "..."
}
```

Then run `composer update`.
