### ISSUE TITLE
Import Primary Element and Subitems

### ISSUE THREAD

**Issue by harispepic** [craftcms/feed-me#570]
### Description
I have an array that needs to be imported and inside this array there is another array that needs to be imported, is there a solution how to do this with a feed import?

The array looks like this:
```json
{
    "data": {
        "title": "XY",
        "name": "XY",
        "version": "XY",
        "plugins": {
            "data1": {
                "name": "XY"
            },
            "data2": {
                "name": "XY"
            }
        }
    }
}
```

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.33

**Comment by brandonkelly** [comment]
How-to questions are best asked on https://craftcms.stackexchange.com, with the [plugin-feedme](https://craftcms.stackexchange.com/questions/tagged/plugin-feedme) tag.
