### ISSUE TITLE
Can't import a date

### ISSUE THREAD

**Issue by amityweb** [craftcms/feed-me#571]
Can't import a date. 

Initially set as a timestamp:
`<post_date>1250607439</post_date>`

Also tried a date:
`<post_date>2009-08-18 14:08:57</post_date>`

Selected "Data provided for this field is formatted as: Auto" in the Feedme settings

Also tried selecting yyyy/mm/dd and importing dates in this format (but I dont want to, it has no time!), and it still did not work. 

Error on import is:
`Call to undefined method Carbon\Carbon::parse() - DateHelper.php: 43`

**Comment by brandonkelly** [comment]
Sounds like maybe the Carbon library didn’t get installed when you installed Feed Me, or the autoloader missed it. Try running `composer update` and see if that helps.

**Comment by amityweb** [comment]
Just a FYI in that I had not looked into this issue further. I created a custom field for date and imported to that. I had already run composer update several times so just not had time to look into it all and went with the custom field for now. Have since run composer updated and Craft update several times so next time I need to import I can take a look again.
