### ISSUE TITLE
csv tab delimiter - The delimiter must be a single character

### ISSUE THREAD

**Issue by ChristopherDosin** [craftcms/feed-me#572]
### Description
I am trying to import a csv file with a tab delimiter, and i am getting the above error. I am totally new with CraftCMS, so i don't know how i could solve this problem or where i have to change something etc.

### Steps to reproduce

I created a `config/feed-me.php` and i have set the `csvColumnDelimiter` to `\t`, then i created the feed within the backend.
```
<?php

return [
    '*' => [
        'pluginName' => 'Feed Me',
        .....
        'csvColumnDelimiter' => '\t',
       .....
```
We could fix the error with something like `fgetcsv($file, 0, $delimiter);` i think, but i don't know where.

### Additional info

- Plugin version: 4.1.1
- Craft version: 3.1.33

**Comment by brandonkelly** [comment]
`'\t'` should be `"\t"` (double quotes).

**Comment by ChristopherDosin** [comment]
yep, saw the error by myself also 10 seconds ago :D  thanks for your fast help! 👍
