### ISSUE TITLE
Group sites slugs not syncing, but defaulting to English. Imported using FeedMe. 

### ISSUE THREAD

**Issue by amityweb** [craftcms/feed-me#574]
I have imported many sites using FeedMe. My sites are in Groups, so for example, the German group has Germany and Austria in it, Spanish group has Spain and Mexico. 

I have set my custom fields between a mix of using the data group wide, or just for that site. 

When I import say German, I did not think I would need to import into Austria, as my fields should be syncing. So I imported in German and Austria pages are there and all update OK. 

The only problem is the slugs of the secondary group sites, so Austria and Mexico for example, have English slugs. So the slugs are not syncing within the group. 

Is this normal? How can I get my slugs to sync? So the import creates the correct slugs for the main sites like Germany and Spain, but its not affecting the slugs for the sites within their groups like Austria or Mexico. 

Thanks

**Comment by i-just** [comment]
Hi, I know it’s been a long time since you asked this question, but maybe you or someone who stumbles upon this thread finds the answer useful.

As of Craft 4.5, slugs have their own translation method, so it’s possible to import & manage them like you would titles.
