### ISSUE TITLE
"Default" User Groups are not being respected

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/feed-me#576]
### Description

This bug feels very similar to #299.

---

When importing a batch of Users from a CSV, the User Groups "Default Value" isn't being respected...

<img width="981" alt="Ω 2019-07-10 at 3 34 48 PM" src="https://user-images.githubusercontent.com/5309692/61010151-fb808000-a329-11e9-9e23-c100106e34f4.png">

^ As you can see in that image, I specified "Companies" as the default User Group.

But after running the import, I look at the User which was created. There are no User Groups selected...

<img width="138" alt="Ω 2019-07-10 at 3 41 55 PM" src="https://user-images.githubusercontent.com/5309692/61010201-29fe5b00-a32a-11e9-99d6-6fc77699bd50.png">

---

### Steps to reproduce

1. Import Users via a CSV
2. Set the "User Groups" > "Default Value"
3. Run the import

You'll notice that the User Groups Default Value is not respected.

### Additional info

- Plugin version: Feed Me 4.1.1
- Craft version: Craft Pro 3.1.34

**Comment by chadcrowell** [comment]
Same thing here. Also can't get user groups assigned when including a column in the CSV with user group IDs, handles, or names. 

Plugin version: Feed Me 4.1.1
Craft version: Craft Pro 3.2.9

**Comment by olivierbon** [comment]
@lindseydiloreto - though slightly counter intuitive, if you want the default value to be used, you need to select *Use default value* from the Feed Element dropdown.

![feed-me](https://user-images.githubusercontent.com/146041/62622397-8ac78600-b91e-11e9-8890-2b8122750774.png)

**Comment by olivierbon** [comment]
@chadcrowell - if you want to have multiple values in one `CSV` column,  you can set a `dataDelimiter` using [a configuration file](https://docs.craftcms.com/feed-me/v4/get-started/configuration.html).

Assuming a "**|**" as a `dataDelimiter`, a Groups column with multiple handles would look like:

"group1|group2|group3"

**Comment by engram-design** [comment]
For what it's worth, the necessity of having to set "Use default value" is because of all the different ways data can be imported. Sometimes you'll want to import an empty string, array or null value into a field, which would override existing values - sometimes wanted behaviour - so its tricky to check for values if sometimes 'falsey' values are valid (as in, you _want_ the default to be empty).

Its annoying, but there for a reason 😁

**Comment by olivierbon** [comment]
Thanks for clarifying @engram-design !

**Comment by lindseydiloreto** [comment]
Good to know, thanks @olivierbon and @engram-design! 🍺
