### ISSUE TITLE
failed to install feed-me: No plugin exists with the handle "feed-me"

### ISSUE THREAD

**Issue by terryupton** [craftcms/feed-me#578]
### Description
Upgraded to the latest Craft release (Craft Pro 3.2.3) and I have tried to install the Feed Me plugin both via the command line and the back-end and I keep getting the following error:
'failed to install feed-me: No plugin exists with the handle "feed-me"'

<img width="1866" alt="Screenshot 2019-07-17 at 10 51 00" src="https://user-images.githubusercontent.com/5698596/61366077-c7a0df80-a880-11e9-962d-683d75d69ab2.png">

<img width="1058" alt="Screenshot 2019-07-17 at 10 51 38" src="https://user-images.githubusercontent.com/5698596/61366118-dc7d7300-a880-11e9-96df-f7c71937919c.png">

<img width="1738" alt="Screenshot 2019-07-17 at 10 52 46" src="https://user-images.githubusercontent.com/5698596/61366209-0898f400-a881-11e9-8f5d-ef2823a7521d.png">

### Steps to reproduce

1. Upgraded to Craft 3.2
2. Ran composer require craftcms/feed-me
3. Ran ./craft install/plugin feed-me
4. Also tried to install via the control panel.

### Additional info

- Plugin version: 4.1
- Craft version: 3.2.2

**Comment by iamkeir** [comment]
I am experiencing this - did you manage to fix?

**Comment by terryupton** [comment]
@iamkeir yeah. Here was the advice form Craft. I believe I just added it to the project.yamk file and it all worked. 

> You have 2 options to fix this:

Go to Settings → Plugins and remove Feed Me.
In your database remove the feed-me row in your craft_plugins table and remove the craft_feedme_feeds table altogether.
Re-install from the Plugin Store.
OR add the below to your project.yaml under the plugins section as in the attached (line 834):

feed-me:
    schemaVersion: 2.1.2
    enabled: true
then run ./craft project-config/sync.

**Comment by iamkeir** [comment]
Thanks @terryupton for the quick response. Did they suggest what led to it happening?

**Comment by terryupton** [comment]
No. I don’t recall. Sorry. I think it might have been my mistake in this instance.
