### ISSUE TITLE
Supplied filename is not used for asset

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/feed-me#580]
### Description

When importing Assets from a set of remote URLs defined in a JSON feed, structure like:

```JSON
[
    ...,
    { 
        "url": "https://www.example.com/?no=path&but=plenty&of=parameters", 
        "filename": "filename.jpg",
        "folder": "folder/structure/4-levels/deep"
    },
    ...
]
```
_(each field in the JSON mapped to the equivalent asset field in the mapping screen of the feed, title field is set to filename as above - no titles available in this feed. Unique identified for the feed set to filename - filenames are unique)_

**FeedMe uses the filename it got from parsing the image URL for saving to disk and not the filename as supplied in the JSON. This does not get changed to the filename as supplied in the feed.** 

In the case of this feed, the URL used to retrieve the image bears no relation to the filename of the image and the parser does not come up with a reasonable result.

It looks like the on disk filenames contain the host / domain and a hash of some sort, like this: `www.example-xijwl3vjt_190724_123920.jpeg`. The filename on the assets table is correct, as per the feed.

Each asset is imported to a specific folder a consistent number of levels deep, because there will be a huge number of images imported via this mechanism (probably ~70 Gb worth in the end).

No image thumbnails are shown in the control panel, I presume because of the mismatch between the db and file-system.

### Additional info

- Plugin version: 4.1.1
- Craft version: 3.2.5.1

**Comment by brandonkelly** [comment]
Feed Me doesn’t have a way to specify an incoming asset’s filename; just its location which should be used to import the asset. Did you actually select `filename` or `folder` in any of the Feed Element dropdowns that leads you to believe that they would have been used?

**Comment by rob-baker-ar** [comment]
![feedme filename example](https://user-images.githubusercontent.com/39988088/62853096-35ef8b00-bce3-11e9-8246-5d18cd3f6f41.png)

On the field mapping screen (3rd screen)  when setting up the feed, it asks for Title, URL or Path, Filename and Folder. As per the screen shot: filename and folder were mapped to fields of the same name in the feed. The examples it shows pulled out of the feed are good representations.

**Comment by rob-baker-ar** [comment]
...Not sure this should be closed just yet - sorry for the delay, I have not been at work.

**Comment by rob-baker-ar** [comment]
Update: This can be worked around by loading an image from a different URL, i.e. one that ends with the filename desired.

A few Rewrite rules later, I have convinced the source server to use a URL of the necessary format to generate the filename needed.

It would be nice if it used the filename in the feed instead though.

**Comment by bryantAXS** [comment]
I'm running into this as well. I'm fetching remote images using the URL setting, and also providing an updated filename and folder I want the images saved to. In this case, the files uploaded are based on the filename inside the URL and not the filename I'm explicitly setting.

**Comment by i-just** [comment]
This has been working as expected for a while now (the filename mapping is respected), so I’m going to close this issue. Tested against v4.4.0 (the latest one at the moment is 4.8.0) and v5.0.4 (the latest one at the moment is 5.3.0).
