### ISSUE TITLE
If photo url is blank, the search still finds a photo

### ISSUE THREAD

**Issue by alexmglover** [craftcms/feed-me#582]
### Description

When a user element's photo url is blank, the import still finds a photo.

It seems like the fix is to just add an `empty($value)` check and return before running the `AssetElement` search. I am not sure if this is a bug with the `AssetElement` query or if this was how it is intended to work, so I didn't submit a PR.

It does seem to me that the AssetElement should not return a value if the filename being passed in is blank.

### Steps to reproduce

1. Create a feed with an empty photo to import into a user element.
2. Run import.

### Additional info

- Plugin version: 4.1.1
- Craft version: 3.2.6

**Comment by alexmglover** [comment]
I should probably clarify that the feed itself is what has the blank photo, and the import still sets a photo on the user element.

**Comment by vnali** [comment]
one workaround is checking for $value [here](https://github.com/craftcms/feed-me/blob/develop/src/elements/User.php#L180) like;
        if ($value==''){
            return null;
        }
and it seems problem is [here](https://github.com/craftcms/feed-me/blob/develop/src/elements/User.php#L180). 
even if filename is empty, query returns an asset anyway.

**Comment by billymedia** [comment]
I am also encountering the same issue, users with no photos seem to find a random existing photo and save that agains the user, the fix above worked but i would assume hacking the core file in this way isnt ideal. Any ideas @engram-design  ?

**Comment by billymedia** [comment]
anyone?

**Comment by ryssbowh** [comment]
Same problem here

**Comment by ryssbowh** [comment]
I'd really hoped this would have been fixed after the recent bunch of updates, but still happening.
Is there any update as for when this would be fixed ?

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1283 for the next v4 and v5 releases
