### ISSUE TITLE
Icon picker support

### ISSUE THREAD

**Issue by mustasj** [craftcms/feed-me#584]
I have about 2000 entries to import and need to get icons on all of them.
i'm using the [Icon picker](https://verbb.io/craft-plugins/icon-picker) plugin from Verb.
So it would be nice if it was possible to import the icon with feed me, instead of doing it one by one.
I've added this to the "Icon picker" repo too, dont know who is more suited to do the integration

**Comment by angrybrad** [comment]
In a future release, it will be up to 3rd party plugins to support Feed Me. Related: https://github.com/craftcms/feed-me/issues/545
