### ISSUE TITLE
Sync error in log with 0 elements

### ISSUE THREAD

**Issue by jamealg** [craftcms/feed-me#585]
### Description
This isn't a breaking issue but the error message did throw me off. I have a feed that runs every minute and only includes elements that are newly created or updated. Sometimes there are 0 elements returned. In that case I see this error in my logs:

```
Most Recent Sync: Starting processing of node #1
↳ Most Recent Sync: Match existing element with data {"blueframeId":""}.
↳ Most Recent Sync: Unable to match an existing element. Have you set a unique identifier for ["blueframeId"]? Make sure you are also mapping this in your feed and it has a value. - Element.php: 126.
```
There are 0 nodes to process so there shouldn't be a "node #1" to process. The error message doesn't make sense.

It appears to function normally when there are feed items to process.

### Steps to reproduce

1. Create a JSON feed that looks like this:

```
{
"paginationUrl": null,
"broadcasts": []
}
```

2. Create feed
Element type: entry
Import Strategy: Create & Update

3. Run feed via direct feed URL

### Additional info

- Plugin version: 4.1.1
- Craft version: 3.2.8

**Comment by brandonkelly** [comment]
We just released Feed Me 4.3.0, which clears out all log messages when there are no items to process.
