### ISSUE TITLE
Optgroups causing error when mapping import

### ISSUE THREAD

**Issue by alexmglover** [craftcms/feed-me#589]
### Description

It seems that an optgroup is causing issues with imports on select. I am getting the error Undefined index: value on line 71 of FeedMeVariable.php. Checking to see that `$value[$index]` is set seems to fix the error.

### Steps to reproduce

1. Create a select field on a section with an opt group.
2. Create a feed in feedme and progress to the field mapping screen. This is where you will find the error.

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.2.8

**Comment by pixelmachine** [comment]
I can confirm I am also seeing this error

**Comment by KatieMFritz** [comment]
I'm also having this problem. I'm not even trying to update that field, but I can't import to the section that contains it. 😩

**Comment by pixelmachine** [comment]
@KatieMFritz 
It's a horrible work around but I've been removing the select field from the section, running the import and then re-adding the field after the import is complete. There's no data loss, the field you remove and re-add will retain it's settings and entry values.
