### ISSUE TITLE
Entries created with 3.0.0-beta.23 won't update until save manually.

### ISSUE THREAD

**Issue by JorgeAnzola** [craftcms/feed-me#591]
### Description

Well, basically that. It's a long shot, here. I used Feed Me 3.0.0-beta.23 to import a lot of stuff like a year ago. Now, there seems to be a problem, but the entries won't update with a new feed until I save each manually. I've tried doing it with the resave command, without luck. Does anybody know or have had something similar?

### Additional info

- Plugin version: 3.0.0-beta.23 then ^4.0.0
- Craft version: 3.2

**Comment by mofman** [comment]
Think we're having a similar issue. Everything is imported fine but this twig snipet doesnt run until i go into the entry in the cms and click save again? 

```
{% set today = craft.entries({
    section: 'welcomeScreens',
    welcomeScreenDate: '= ' ~ 'now'|date('Y-m-d'),
}).one() %}
```

**Comment by JorgeAnzola** [comment]
My solution is really case-specific, but I solved it with a console command that fetches the entry, and based on the reference of my old json feed updated the new references. After that updating is done, I'm able to run the feed normally. What I wanted was to match and old reference with a new reference on Feed Me, but I did it with the console.
