### ISSUE TITLE
Stuck on the non-progressive loading bar

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/feed-me#594]
### Description
I have been stuck on the non-progress indicating loading bar for about an hour now. I am wondering whether to shut it down or not. There doesn't seem to be any errors or logs. How do I know whether this is still successfully running or not? Is it common for it to take this long before it switches to a normal progress bar?

**UPDATE**
It's now been 12 hours and still on the non-progressive loading bar

![feedme-non-progressive-loading](https://user-images.githubusercontent.com/36191462/63423522-6383b500-c404-11e9-8057-bdae8b690a9c.png)

### Steps to reproduce

1. Set up RSS feed
2. Run feed
3. Progress begins

### Additional info

- Plugin version: 4.1.1
- Craft version: Craft Pro 3.2.9

**Comment by angrybrad** [comment]
Going to go ahead and close this, but the Queue Manager utility in Craft 3.5+ makes it a lot east to monitor queue job progress.
