### ISSUE TITLE
Support for a Phone Number Field

### ISSUE THREAD

**Issue by laurabennett** [craftcms/feed-me#600]
### Description
Running a data import with map location data is working great but nothing is being pulled in to the Phone Number field. Not sure if this would be a request for FeedMe or the third-party Phone plugin but it would be really handy if Craft had a build in field type or validation for phone numbers. The import doesn't return an error (just doesn't save the value) and does import a value if I change to a plain text field.

### Steps to reproduce

1. Add a Phone Number Field
2. Run FeedMe with a value and mapping to the phone number

### Additional info

- Plugin version: Feed Me | 4.1.2
Phone Number | 1.2.3
- Craft version: Craft Pro 3.3.0.1

**Comment by angrybrad** [comment]
Craft currently doesn't have a native phone number field type (this FR would cover it https://github.com/craftcms/cms/issues/5854 if you'd like to comment) and a near-future release of Feed Me is going to move all support for plugin field types to the plugins themselves.
