### ISSUE TITLE
Commerce Product import doesn't allow you to set date format resulting in incorrect dates

### ISSUE THREAD

**Issue by jonXmack** [craftcms/feed-me#602]
### Description
While setting up XML imports for migrating content from EE to Craft, I've been using a unix timestamp as the post date. When importing into Entries there's a dropdown that lets you select the format that the import should expect (Data provided for this field is formatted as:) which I then set to Timestamp (s). When importing into Commerce Products this doesn't appear, and my timestamps aren't being read properly, leading to dates such as 11/9/9320.

### Steps to reproduce

1. Create a Commerce Products import using XML with the post date as a unix timestamp.
2. Set the post date to your date element
3. Run the import

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.1.2

**Comment by bymayo** [comment]
@jonXmack I've just come across this issue, but I found when you format the field in EE as a timestamp it doesn't import correctly. The best way is to do it as ATOM:

`"entryDate": "{entry_date format='{DATE_ATOM}'}",`

**Comment by pdaleramirez** [comment]
Fixed the bug on this commit: https://github.com/craftcms/feed-me/pull/1314/commits/dd5939b66925a93c37fc8e3c522f9ac8b5577071

**Comment by i-just** [comment]
A similar issue was raised and resolved here: https://github.com/craftcms/feed-me/issues/1287. Commerce Products now have the “Data provided for this field is formatted as” dropdown.
