### ISSUE TITLE
User import doesn't set 'preferred locale' to language preference

### ISSUE THREAD

**Issue by wiegerjelsma** [craftcms/feed-me#612]
### Description
When importing a user through CSV file the value for 'preferred locale' is not set as the language preference.

![Schermafbeelding 2019-09-26 om 15 11 18](https://user-images.githubusercontent.com/25075044/65691408-10d79180-e071-11e9-97b3-e941befd74c0.png)
### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.1.2

**Comment by nordentwickler** [comment]
Any news on that?

**Comment by wiegerjelsma** [comment]
No, not yet. Maybe it got solved during updates. I haven't looked further into this.

**Comment by nordentwickler** [comment]
Nope, it hasn't - there are not entries in the userpreferences table genarated -> which means, no preferred locale.

**Comment by i-just** [comment]
Hi, thanks for reporting and apologies for the delayed response. I created a PR for this.

**Comment by angrybrad** [comment]
Resolved via https://github.com/craftcms/feed-me/pull/1289 for the next v4 and v5 releases.
