### ISSUE TITLE
Linkit field not respecting fieldtype

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/feed-me#615]
### Description
Trying to import an csv to create entries with several linkit fields. I can specify a `Type`, ` Custom URL` and `Custom Text`, but the `Type` always gets `fruitstudios\linkit\models\Url` instead of `fruitstudios\linkit\models\Phone` I specify as the default.

### Steps to reproduce

1. Entry with Linkit field which only has the "Phone" option enabled and "Allow custom text"
2. Csv to create a new entry
3. Map the linkit field to for example:
- Type - `Use default value` - `fruitstudios\linkit\models\Phone`
- Custom URL - `<Phone full> 0031 6 12345678`
- Custom Text - `<Phone> 06 12345678`
4. Save and do the import
5. Field will be mapped but overridden with "Url" type like `"phone":{"type":"fruitstudios\\linkit\\models\\Url","value":"0031 6 12345678","customText":"06 12345678"}`

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.4.1

**Comment by elivz** [comment]
I am running into this too. Looks like the URL "type" is hardcoded in the field importer. So whatever type you set in your source data will always be overwritten. Can be fixed by changing line 45 of `src/fields/Linkit.php` to:

    if ($preppedData && empty($preppedData['type'])) {

**Comment by olivierbon** [comment]
Fixed in #622

**Comment by brandonkelly** [comment]
Feed Me 4.2.0 is out now with the fixed Linkit support.
