### ISSUE TITLE
CakePHP error importing entries fields

### ISSUE THREAD

**Issue by janhenckens** [craftcms/feed-me#616]
### Description
We're seeing an error with feeds that have an entries field in the settings:

````
Invalid data type, must be an array or \\ArrayAccess instance. - Hash.php: 50
````
In this cakephp [file](https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L50).

When dumping the data that is causing the exception, that appears to be `craft\\fields\\Entries`.

This used to run without issues and I'm not sure since when it's broken.

### Steps to reproduce

1. Have a feed that includes relations to other entries in the site
2. Have an entries field on that feed, set select the related entry

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.7

**Comment by janhenckens** [comment]
Update: after an afternoon of debugging & dumping stack traces we ended up seeing the Feed Me was trying to import and create Commerce products, simply because the field in question had "variants" as its handle. Changing the handle fixed it.

Commerce isn't installed on this so so this might be something worth having a look at. Thanks!

**Comment by paul-blundell** [comment]
Just ran into this exact same issue. Renaming the field from variants fixed the issue. Thanks.

**Comment by MaartenVenema** [comment]
This issue still persists.

**Comment by carlcs** [comment]
Thanks @janhenckens for posting this issue. Saved me from wasting time debugging!

**Comment by janhenckens** [comment]
Cheers @carlcs :) I was hoping this would be fixed by now :)

**Comment by angrybrad** [comment]
Having a hard time trying to reproduce this, unfortunately. Can someone send a sample feed, database dump, and composer.json file over to support@craftcms.com and reference this issue so we can dig in further?

**Comment by carlcs** [comment]
Hello @angrybrad, here’s everything you need to reproduce this problem. Thanks for looking into it!

[Archiv.zip](https://github.com/craftcms/feed-me/files/5688881/Archiv.zip)

**Comment by carlcs** [comment]
Ok, so there seems to be a new bug in Feed Me 4.3.3 that didn’t exist in 4.3.1. Even after changing the field handle to something else than `variants`, it’s still not importing content into that field. Probably unrelated to the “Invalid data type” error this issue is about. But I’d probably recommend to use 4.3.1 to reproduce and debug this.

**Comment by angrybrad** [comment]
Thanks, everyone - fixed for the next release.

**Comment by Kashkin** [comment]
This bug appears to exist in Craft 4 when importing from a feed with a key of `productId`. The same error listed above is returned, and relabelling the key resolved the issue.
