### ISSUE TITLE
Job failures on paginated feeds result in an endless loop of jobs

### ISSUE THREAD

**Issue by timkelty** [craftcms/feed-me#626]
Here's what I'm seeing:

- A particular job in a paginated feed fails for whatever reason (timeout, etc)
- Despite the job eventually failing (and thus is retried), job for the next page often still created and starts running. So, we now have a `page=1`job retried and running, and a `page=2` job running. 

You can see where this is going…any time a job fails in this way, you'll end up with an endless series of jobs running through all the pages over and over.

It seems that the "next page" feed should _only_ ever be spawned when the previous job is completed and removed from the queue.

It seems like the way feedme handles pagination is logically flawed and prone to these kind of errors.
Perhaps it should go through the entire feed first, and retrieve all the pagination URLs, make a job for each, and then let them run, rather then starting the next page at the end of the previous?

**Comment by timkelty** [comment]
@brandonkelly any update on this?

This behavior has made feedme pretty much unusable for larger paginated imports for us.

**Comment by brandonkelly** [comment]
We just released Feed Me 4.3.0, which replaces the `feed-me/feeds/run` command with a new `feed-me/feeds/queue` command, which will throw exceptions by default, and you must explicitly pass a `--continue-on-error` option if you want it to log errors and keep plugging away.

```bash
> php craft feed-me/feeds/queue 1,2,3 --continue-on-error
```
