### ISSUE TITLE
Imported entries not using the default value for the Author field

### ISSUE THREAD

**Issue by alexroper** [craftcms/feed-me#627]
### Description

Imported entries all have the current logged in user (me) as the Author instead of the default value set in the field mappings. The only way I can work around this is to log in as that user and run the feed.

### Steps to reproduce

1. Create import settings with Google Sheets feed and Create new elements import strategy.
2. In field mappings set the Author field to "Use default value" and select a different user as the default value.
3. Run import.

<img width="1003" alt="Screen Shot 2019-11-13 at 11 44 13 AM" src="https://user-images.githubusercontent.com/377542/68798881-12065300-060c-11ea-8a0d-0316e9b82ea3.png">

### Additional info

- Plugin version: 4.1.2
- Craft version:  3.3.13

**Comment by olivierbon** [comment]
@alexroper this is a bit of UI thing. 

Make sure you set *Data provided for this user is* to ID. Submitted a fail-safe for this [here](https://github.com/craftcms/feed-me/pull/628/commits/92848eafaf5b29c43162eb40c256c3acb4662ece).
