### ISSUE TITLE
CSV Matrix import

### ISSUE THREAD

**Issue by nelhop** [craftcms/feed-me#631]
### Description

A list of timestamps is separated by `|` as delimiter in a csv file:
```
...;1600207200 | 1600812000 | 1601416800;...
```

This entry is mapped to the corresponding matrix field:
![settings](https://user-images.githubusercontent.com/1862955/69556310-cdcc6880-0fa4-11ea-9d52-64833191bdee.png)

The Log file prompts no errors and shows:
![output](https://user-images.githubusercontent.com/1862955/69556309-cdcc6880-0fa4-11ea-87b1-5900aa0b82aa.png)

Everything seems to work smoothly **but the field remains empty**. I have tried multiple date formats without luck.
With other field types, i.e. category slugs, importing multiple values with the delimiter works fine.
(I am pretty sure this worked about six month ago, but have no Idea what changed since then...)

I am thankful for every hint to solve this.

### Additional info

- Plugin version: 4.1.2
- Craft version: 1.3.4

**Comment by bomanden** [comment]
Just subscribed , also interested in the answer. 

Another question: 
Does your enabled/disabled values get handled on the matrix fields ?  
( have problems importing disabled statuses )

**Comment by angrybrad** [comment]
Closing this out for age, but if anyone still runs into it, comment here and we can re-open.
