### ISSUE TITLE
Feed Me ignores json-nodes containing Emails

### ISSUE THREAD

**Issue by klick** [craftcms/feed-me#633]
### Description

I need to import a bunch of users from a json-resource where one node is the users email. But that node does not even show up in the Feed Me’s field mapping select list.

Is this standard behavior?

Json example:

```
{
"name": "username",
"field_user_firstname": "First",
"field_user_lastname": "Last",
"field_user_email": "mail@example.com",
"created": "So., 17.11.2019 - 15:20",
"field_user_role": "string",
"field_user_statement": "string",
"field_user_newsletter_mailchimp": "string",
"uid": "12345"
},
```

### Steps to reproduce

1. Creating feed to import from json resource in Craft
2. Email-node being available

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.16.3

**Comment by klick** [comment]
My bad, seems to be an authentication issue with Drupal which is the provider of the json resource. The mail field gets suppressed to non-logged-in users.

**Comment by olivierbon** [comment]
Glad you got it figured out!
