### ISSUE TITLE
Converting Wordpress linebreaks to paragraphs

### ISSUE THREAD

**Issue by tyssen** [craftcms/feed-me#635]
Apologies if this is the wrong place to ask. I've looked on StackExchange, asked on Twitter and in Discord, but before I try and do something myself, I was wondering if anyone has done anthing that replicates https://developer.wordpress.org/reference/functions/wpautop/  when importing content into Craft using FeedMe?

**Comment by angrybrad** [comment]
You could do this with a plugin that listens for related Feed Me element processing events: https://docs.craftcms.com/feed-me/v4/developers/events.html#feed-processing-related-events
