### ISSUE TITLE
Final feed save step (feed-me/feeds/status) does not add job to queue

### ISSUE THREAD

**Issue by timkelty** [craftcms/feed-me#638]
When stepping through saving a feed, the final screen (feed-me/feeds/status) says that it has started running the feed, but it doesn't.

Clicking "run feed" from the index works fine.

Note: not sure if this is why, but I have `'runQueueAutomatically' => false,` and `queue/listen` daemonized in a dedicated process.

- Feed Me 4.1.2

**Comment by Moucky** [comment]
Seems like I am having the same problem. I thought it was due to a recent update but this is quite old. Things were working as expected when I setup the site initially but I cannot say when the problem started occurring.

**Comment by brandonkelly** [comment]
That final step no longer pretends that the feed is already processing. So… we fixed… the glitch.
