### ISSUE TITLE
Cannot enter feed url

### ISSUE THREAD

**Issue by baronetto** [craftcms/feed-me#640]
### Description
When I enter the URL of a feed and hit save the URL is replaced by another one: "https://specialurl.io/feed.json"

### Steps to reproduce

1. Create new feed
2. Enter the desired URL
3. Enter any element type
4. Hit save
5. The URL is replaced by "https://specialurl.io/feed.json"

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.17 Pro

**Comment by angrybrad** [comment]
Can you update to the latest Craft and Feed Me release and see if this is still an issue for you? If so, just comment back here and we'll re-open and investigate further.

**Comment by angrybrad** [comment]
@holmey guessing you created a `config/feed-me.php` config file and copy/pasted the example from here: https://docs.craftcms.com/feed-me/v4/get-started/configuration.html#control-panel

If you want to use that file, you'll need to update it with a proper feed URL.

**Comment by holmey** [comment]
@angrybrad that's it. Thank you for your quick help.
