### ISSUE TITLE
Session does not exist in a console request

### ISSUE THREAD

**Issue by nstCactus** [craftcms/feed-me#642]
### Description

Some entries (always the same) won't import when import is triggered via the console command.
The error message is:
> Session does not exist in a console request. - Application.php:133
It works fine when triggered from the CP or using the Direct Feed Link. I also have  another feed that only has a Number and a PlainText field that works fine, event when triggered from the console commands.

### Steps to reproduce

1. Create a feed and map its fields (types of mapped fields: PlainText, Number, LightSwitch, DateTime, Assets, Category & ether/simplemap)
1. Trigger an import using the console command : `./craft feed-me/feeds/run --id=1`

### Additional info

- Plugin version: 4.1.2
- Craft version: 3.3.16.3

**Comment by leevigraham** [comment]
@nstCactus I did some digging and it looks like feedme is trying to get the users temporary upload directory for new entries 

![image](https://user-images.githubusercontent.com/25124/79346622-eea65200-7f75-11ea-94c8-9e531cf71e26.png)

I think the only way around this is to set a user id via the command line (if that's even possible) or upload all the assets first in your import and then import the entries.

// @brandonkelly

**Comment by nstCactus** [comment]
Good catch! This makes sense. Maybe setting `$userFolder`to _storage/runtime/temp_ for console requests would fix this.

**Comment by thijskaspers** [comment]
Old issue, but I'm getting this same error just now on certain entries in a feed, usually the first one and an entry in the middle of the feed that is processing.

We changed from triggering the direct feed URL to the console command, e.g.: `./craft feed-me/feeds/queue 1` and that is when this issue started to pop up in the logs.

![Schermafbeelding 2021-03-19 om 16 11 32](https://user-images.githubusercontent.com/1608184/111802101-ea915b80-88cd-11eb-9691-3808a3c60a10.png)

**Comment by thijskaspers** [comment]
Any update on this? We are still getting this issue when running feedme from a cronjob with `/usr/bin/wget -O - -q -t 1 "URLHERE"` as shown in the feedme documentation.

When we manually run the feed from the back-end, all goes well, but when the cronjobs runs them we keep getting the `Session does not exist in a console request` error occasionally.

**Comment by phpsa** [comment]
Fixed in release of craft 3.7.4
