### ISSUE TITLE
Twig runtime error when running in Craft 3.4 beta

### ISSUE THREAD

**Issue by membla** [craftcms/feed-me#643]
### Description

Acessing /cp/feed-me/feeds on Craft 3.4 beta throws a Twig runtime error:

`Impossible to access a key ("craft\elements\Entry") on a string variable ("{"craft\\elements\\Asset":"","craft\\elements\\Category":"","craft\\elements\\Entry":{"section":"6","entryType":"6"}}").`

**Comment by klick** [comment]
Same here and this seems to prevent content from being imported too.

**Comment by timkelty** [comment]
Yep, here too.

**Comment by timkelty** [comment]
@membla @klick if anyone needs this before my PR gets merged, you can put this in your composer.json:

`"craftcms/feed-me": "dev-fix-createModelFromRecord-for-3.4",`

and 

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/timkelty/feed-me"
    }
  ]
```

**Comment by klick** [comment]
Thank you, sir.

**Comment by brandonkelly** [comment]
Feed Me 4.2.0 is out now with this fix. Thanks @timkelty!
