### ISSUE TITLE
CURL error parsing local file

### ISSUE THREAD

**Issue by andersaloof** [craftcms/feed-me#655]
### Description

Parsing a local file on a Windows 10 setup fails, returning cURL error 3.

This IF check (https://github.com/craftcms/feed-me/blob/develop/src/services/DataTypes.php#L135) returns **false** for a windows path (in my case, the path returned from https://github.com/craftcms/feed-me/blob/develop/src/services/DataTypes.php#L132 is `C:\WEB\project-name\storage/runtime/products_no.json`).

I've tested the 4 latest versions of DataTypes.php and the various IF checks used against this path, with the following result:

```
$testUrl = "C:\WEB\project-name\storage/runtime/products_no.json";

// 24 Apr 2019: 
var_dump(!UrlHelper::isAbsoluteUrl($testUrl)); // true

// 15 Nov 2019:
var_dump(strpos($testUrl, '://') === false && !UrlHelper::isProtocolRelativeUrl($testUrl) && !UrlHelper::isRootRelativeUrl($testUrl)); // true

// 15 Jan 2020:
var_dump(strpos($testUrl, '://') === false && UrlHelper::isRootRelativeUrl($testUrl)); // false

// 15 Jan 2020:
var_dump(strpos($testUrl, '/') === 0 && !UrlHelper::isProtocolRelativeUrl($testUrl)); // false
```

### Steps to reproduce

1. On a windows 10 machine, setup a feed from a local file with an alias as path, eg. @storage/somefile.json
2. Run feed

### Additional info

- Plugin version: 4.2.0.1
- Craft version: 3.3.20.1

**Comment by andersaloof** [comment]
Couldn't a more reliable check be to use `file_exists()`?

**Comment by andersaloof** [comment]
Any progress on this issue?

It's quite frustrating to remember to edit the source file when the plugin updates, to keep things working in Windows environments.

**Comment by TimvanDijkhuizen** [comment]
I'm having the same problem, I hope it will be fixed soon.
