### ISSUE TITLE
Unable to set status to enabled on a disabled entry on a multisite installation

### ISSUE THREAD

**Issue by andersaloof** [craftcms/feed-me#659]
### Description

If an entry is disabled on a site (either by the feed or manually), it is not possible to enable it again when running a feed for that site.

### Steps to reproduce

1. Create two sites
2. Create a field to use as the unique identifier for an entry
3. Create a section and add the unique field to the entry
4. Create two local files in `storage/runtime`
```
# file1.json
[
  {
    "unique_id": 23,
    "title": "An example title"
  }
]

# file2.json
[
  {
    "unique_id": 23,
    "title": "En eksempel tittel"
  }
]
```
4. Setup two feeds, one for each site with strategy "Add & Update & DisableForSite", parsing file1.json and file2.json. Map the title and unique_id fields against the entry title and the unique field created in step 2. Make sure the unique field is used as the unique identifier for the feeds.
5. Run both feeds and observe that both sites have gotten the correct entry created.
6. Edit file2.json and change both the title and the unique id
7. Run the feed that parses file2.json again. A new entry with the new title is created, and the old entry is disabled correctly (as its missing in the feed)
8. Now revert the changes to file2.json and run feed once again. The new entry created in step 7 is correctly disabled (as its missing in the feed), but the original entry is not re-enabled correctly. The log says "No content has changed", even though I would assume the status should change from disabled to enabled.

### Additional info

I've tested this on a single site installation, and it works as expected.

I've tried setting the status field on the feed to 'Use default value' and set the default value to 'Enabled', but it makes no difference.

- Plugin version: 4.2.0.1
- Craft version: 3.2.20.1

**Comment by angrybrad** [comment]
This is most likely resolved in the just-released 4.3.0 if you want to give it a whirl. If it's still an issue, comment back here and we'll re-open.
