### ISSUE TITLE
Only the filename is checked when deciding if it should download

### ISSUE THREAD

**Issue by ijy** [craftcms/feed-me#663]
### Description

Feed Me seems to only check the filename when deciding whether to download a remote image with the "Use existing asset" option selected:

![Screen Shot on 2020-01-31 at 09-10-59](https://user-images.githubusercontent.com/434593/73527397-e759b880-440a-11ea-81f9-47683d95f74b.png)

In many cases filenames clash but the URL is unique. E.g.

http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7B0bd18a53-9055-41d3-b227-26a41aafdf25%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7B11c93ef9-e1d9-4bc3-8f9f-0d579e9cb98e%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7Bd2a91ee5-5ef3-4ef3-bae9-8b290079bdf7%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7B5abab8ee-0647-4941-867b-d3c9a313d9c5%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7B40626a0b-58dd-4cbf-805a-b61147acff94%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7Bd8ec1265-b3f8-4374-9571-54247edae6a7%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7Be526c71d-17b2-4bac-8150-2d29dcad382b%7D/main/LOUNGEDINER.jpg
http://med05.expertagent.co.uk/in4glestates/%7B6c28d09f-b36f-4a85-aa25-e92a4aff3e28%7D/%7Bc1257f91-005b-4998-87ae-c1f05b2ab4a2%7D/main/LOUNGEDINER.jpg

This results in only the first image being downloaded and then used incorrectly in places where the same filename is referenced.

In this particular case Feed Me downloads many thousands of remote images daily so having the "Use existing asset" option selected is essential as when it is set to "Replace existing asset" the time it takes the feed to process is several hours with a *lot* of extra wasted bandwidth, CPU, and time.

In addition to the filename I also think it should be checking the headers for Last-Modified and the MD5 to see if that image (full URL) has been updated.

### Steps to reproduce

1. Setup a property feed with image assets included
2. Set to "Create asset from url, if exists: Use existing asset"

### Additional info

- Plugin version: 4.2.0
- Craft version: 3.3.19

**Comment by i-just** [comment]
This was raised again here: https://github.com/craftcms/feed-me/issues/749, and there’s a PR awaiting review. I’m closing this as a duplicate, but you can go ahead and follow along under #749.
