### ISSUE TITLE
[Craft 3.4] - Progress bar skipped, button styling error

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/feed-me#664]
So with the introduction of the queue manager in 3.4, the progress bar in Feed Me no longer works like it used to. As soon as you start running the import, it goes immediately to "Processing complete!" and you have to go over to the Queue Manager to see the actual progress (which I think is actually fine, but the messaging should probably be changed to reflect that). 

Also, super minor styling issue, but the "Save" and "Save & Continue" buttons in Feed Me page footers now hang off the bottom edge of their container in 3.4.

- Plugin version: 4.2.0.1
- Craft version: 3.4.1

**Comment by brandonkelly** [comment]
That page wasn’t reporting reliable info even before Craft 3.4, if there was anything in the queue that was already processing which wasn’t the feed.

Switched to this for the next release:

![The new result page at the end of setting up a feed](https://user-images.githubusercontent.com/47792/77698157-61bb3a80-6f6d-11ea-9492-6704d42468bb.png)
