### ISSUE TITLE
Feed into Global sets?

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/feed-me#670]
I don't know if I'm missing something or not, but I can't see any way for Feed Me to import into fields in Global sets. I'm using Craft 3.4.5 Pro and Feed Me 

If that's not currently possible, do you think there might be a chance to get it implemented? I'd really like to be able to get Feed Me to set and update some important default values for the site.

Thanks in advance for any help or advice you may be able to give with this.

Andrew Macpherson

**Comment by brandonkelly** [comment]
We just released Feed Me 4.3.0 with the ability to import global set data.
