### ISSUE TITLE
Entry with Assets Field, that allows multiple files - only allows one file

### ISSUE THREAD

**Issue by cruiser12** [craftcms/feed-me#671]
### Description
My Entry has an Assets Field, that allows multiple assets/files like a gallery.
My XML files show multiple sub-nodes (n0,n1,n2, etc), but i cannot address them.
Only by selecting the e.g. n0/node_export_file_url i can import only the first image of the gallery.
Is there a solution for it?

<img width="1166" alt="Bildschirmfoto 2020-02-16 um 04 22 06" src="https://user-images.githubusercontent.com/133954/74598596-32630500-5074-11ea-8e71-4d69613cb4d9.png">

latest Craft 3.4

**Comment by jdsdev** [comment]
I'm not one of the developers, but it looks like you just need to give all of your sub-nodes the same name, as in the docs: https://docs.craftcms.com/feed-me/v4/guides/importing-assets.html

```
<?xml version="1.0" encoding="UTF-8"?>
<Images>
    <Image>
        <Title>Feed Me Social Card</Title>
        <URL>https://craftcms.com/uploads/plugins/feed-me/_800x455_crop_center-center_none/feed-me-social-card.png</URL>
        <Caption>Some Caption</Caption>
    </Image>

    <Image>
        <Title>Craft Commerce Social Card</Title>
        <URL>https://craftcms.com/uploads/plugins/commerce/_800x455_crop_center-center_none/commerce-social-card.png</URL>
        <Caption>Another Caption</Caption>
    </Image>
</Images>
```

I've done a similar import using JSON and not had any issues.
