### ISSUE TITLE
Import matrix with duplicate field names

### ISSUE THREAD

**Issue by jdsdev** [craftcms/feed-me#672]
If multiple blocks in a matrix have a field with the same name, i.e. let's say they all start with `blockTitle`, Feed Me can't differentiate between the different blocks types.

This can result in lost content as Feed Me will choose the first block type that has a field called `blockTitle`. To avoid this issue, it would be good to either check all of the fields before choosing a block type, or allow the block type to be imported as well.

**Comment by ul8** [comment]
Agreed, and in the meantime, this limitation really should be added to the docs. Thanks!

**Comment by kevadamson** [comment]
Yeah I've got this issue as well. I was relying on this plugin to migrate a lot of entries from a blog to a recipes section, but the fact that I have matrix types which use the same field names means I can't :\

**Comment by i-just** [comment]
Sounds like the same issue as described in #1184 and #1226.

It was adjusted in v5.1.0 via https://github.com/craftcms/feed-me/commit/b7c5c9e8c48290077acc4f0d1a280dbf48b60d50, https://github.com/craftcms/feed-me/commit/8931ff6a29261a0509b7ffb9ee79f64a06588567, and https://github.com/craftcms/feed-me/commit/0a530207775f4c4e1c93e96f9ffc449a8494fdfa
