### ISSUE TITLE
Phantom license from old Craft 2 Feed Me Pro installation causing CP errors

### ISSUE THREAD

**Issue by michellekb** [craftcms/feed-me#675]
When I log into my Craft 3.3.20.1 Pro with Feed Me 4.2.0.1, there's an error banner "There’s a licensing issue with the Feed Me plugin." When I click the Resolve button beside that message, it takes me to Plugins Settings, and under Feed Me there is an error message "Your license key is invalid" with the license number that was valid when we bought Feed Me for Craft 2 in 2017-ish. I understand Feed Me is now part of Craft, but cannot figure out how to clear this error, since there's no longer a License area in Feed Me settings. Going into the database and changing craft_plugins.licenseKeyStatus from 'invalid' to 'unknown' seemed to solve the problem but it reverted back after some time (I guess it makes sense it wouldn't be that easy).

We are unable to even use Feed Me at present, because of (unrelated (I think?)) issue #665, but in hopes that that will be resolved, I'd rather not have to uninstall Feed Me, and therefore lose my config settings for it, in order to clear the licensing error.

**Comment by jamesmacwhite** [comment]
@michellekb You should be able to safely reinstall without losing settings.

You'd need to backup your `craft_feedme_feeds` table previous to uninstalling, but you can import this back and your feed settings and mappings will be restored.

Possibly the license key might still be set in your project.yaml or if not enabled, the `craft_info` table config column might have it stored as JSON key somewhere.

For what it's worth, in my `craft_plugins` table I also have `unknown` but it isn't causing problems.

**Comment by angrybrad** [comment]
@michellekb is this is still an issue for you, hit us up at support@craftmcs.com and we'll help debug further.
