### ISSUE TITLE
Bug: Default value overrides the value provided by the feed if it's `null`

### ISSUE THREAD

**Issue by gustavs-gutmanis** [craftcms/feed-me#680]
### Description

When there are `null` values provided by the feed, they get defaulted to empty strings.

### Steps to reproduce

1. Create a feed with some values set to `null`
2. Set up field mapping by leaving the default values blank (don't touch them at all)
3. Run the feed and notice that all of the `null` values are now empty strings in the database table

### Expected Results

It would be nice to have an option to default to `null` or a possible solution would be to check for the existence of the key in the feed item. So if the key's not present - default to an empty string or whatever, or if it's present, then use the value provided, which could be `null`, could be an empty string, could be anything. 

### Additional info

- Plugin version: 4.2.0.1
- Craft version: 3.4.8

**Comment by kristiansp** [comment]
I'm not entirely sure, but I think that when a value is `null`, Feed Me will skip that variable on import altogether, just like if it wasn't in the feed.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1228
