### ISSUE TITLE
Asset import fails if there is a query string

### ISSUE THREAD

**Issue by nyehughes** [craftcms/feed-me#682]
### Description

Asset import fails with the following error:
Invalid characters passed for attempted conversion, these have been ignored - AssetHelper.php: 321.

Googling around seems to suggest problem is trying to use base_convert($string, 10, 36) with a non-number, on PHP versions more than 7.4.

### Steps to reproduce
import an asset with a query string, for example, WFOCouncil-StPetersburg.jpg?dl=1
### Additional info

- Plugin version:4.2.0.1
- Craft version: 3.4.9
- PHP version: 7.4.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
