### ISSUE TITLE
slug gets updated with every import

### ISSUE THREAD

**Issue by tuursw** [craftcms/feed-me#684]
When I am running an import with feed me, the slug also get updated, adding a number to the original slug

So which each import the slug is becoming
/slug-1
/slug-2
/slug-3

I've tried different approaches to keep the original slug but I can't seem to get it to work.

**Comment by BrandonJamesBorders** [comment]
@tuursw I'm experiencing this as well. What did you do to resolve this issue?

It appears to be creating a new entry ID, leaving the old one behind. They don't show up under trashed, running's craft's garbage collection doesn't get them either.

**Comment by tuursw** [comment]
unfortunately not... I am currently deleting the entries, cleaning up the database and running the import to get the desired result.
This doesn't need to be done frequently fortunately

**Comment by i-just** [comment]
Hi, thanks for getting in touch. This will happen if a matching element can’t be found, so a new one is created (assuming your import strategy has “create new elements” checked). If a new entry is created, a slug will be auto-generated based on the title. If the generated slug already exists, a number will be appended to the end.

In the import logs (Control Panel > Feed Me > Logs tab), you can see the steps the script takes for each element it imports. 

This is an example of the logs for importing an entry that already exists in the CMS. The unique identifier in the feed is set to `title`, and Feed Me can find an existing entry with the title “test 1” in the CMS. 3rd line from the top reads, “Existing element `#474` found.”:

<img width="2043" alt="Screenshot 2023-06-30 at 12 09 17" src="https://github.com/craftcms/feed-me/assets/4500340/dc21cdc5-1388-4b5d-a8dd-7bcec87d47f6">

And this is what the logs say if it can’t find an existing entry in the CMS.
<img width="2055" alt="Screenshot 2023-06-30 at 12 09 29" src="https://github.com/craftcms/feed-me/assets/4500340/f4b09b2e-ee95-4118-8220-eafd6df2a6b4">

I hope the above helps clear things up. 

I’ll close this now, but if this doesn’t clear things up and you’re still experiencing this issue, please post a screenshot of the mapping screen, a screenshot of the first screen in the feed - one where you define the name, file, import strategy etc., and a snippet of the data you’re importing that causes this behaviour.
