### ISSUE TITLE
Import into entry section with not imported SuperTable field results in error and failed import

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/feed-me#688]
### Description

Import a feed into a section that has a number of mapped fields. Include a SuperTable field but do not map any import data to be imported into that field (i.e. the whole of the SuperTable field is not an import target at all).

Result is an error in a foreach loop in the class `craftcms/feed-me/src/fields/SuperTable.php` on line 153 (`_getFieldMappingInfoForNodePath()` method). `$fields` is not an array.

I looks like the reason is that there are no fields in that table mapped but it's not catching the condition where we don't want to import anything into that field.

Removing the SuperTable field from the entry type fixes this, but I need the field on there!.

### Additional info

- Plugin version: 4.2.2
- Craft version: 3.4.12

**Comment by jeroenlammerts** [comment]
This is still an issue, #1088 tried to fix it but doesn't work.

**Comment by i-just** [comment]
Looks like this has been resolved a while ago. I just tested against 4.4.0 and 5.0.4, and all works as expected when importing into an entry type that contains a Super Table field, and that field is not mapped to have data imported into it.
