### ISSUE TITLE
Matrix field mapping between 2 different feed paths causes missing data

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/feed-me#689]
### Description

If you have a (JSON but probably applies to other formats too) feed for Matrix field mapping paths like:

```
[JSON Path]                ->    [Matrix Field Path]
content-text/block/body    ->    body[text][body]
images/block/image         ->    body[image][image]
```

There are cases where the images as above will _replace/overwrite_ the body text previously added.

When debugging this, latching on to mostly all of the events that Feed Me raises, it looks like when the JSON is parsed it gets confused because there are *separate* JSON fields mapping to a single Matrix field (but different blocks).

I think the event that reveals the most is `EVENT_BEFORE_PARSE_FIELD`. At this point, the `feedData` array (in the above example) looks like:

```
...
"content-text/block/0/body" => "..."
...
"images/block/0/image" => "..."
...
```

Because the zero index after "block" is the same and the destination is the same matrix field, I think the latter overwrites the the previous when the array is "prepared" for saving, shown in the `EVENT_AFTER_PARSE_FIELD` - that has keys like "new1", "new2", etc. and no sign of the original "body" content.

### Additional info

- Plugin version: 4.2.2
- Craft version: 3.4.12

**Comment by i-just** [comment]
I believe it was fixed in Feed Me 5.1.0 (see #1184 for more info), so I’m going to close it. Please feel free to get in touch again if this is a different and still unresolved issue.
