### ISSUE TITLE
Normalize file extension so .JPG files are valid

### ISSUE THREAD

**Issue by leevigraham** [craftcms/feed-me#691]
### Description

It looks like AssetHelper isn't lowercasing the extension. This results in invalid file extensions on case sensitive systems when the extension is uppercase eg `.JPG`

 https://github.com/craftcms/feed-me/blob/develop/src/helpers/AssetHelper.php#L284

### Steps to reproduce

Try to import a Asset with a `.JPG` extensions

### Additional info

- Plugin version: 4.2.2
- Craft version: 3.4.15

![image](https://user-images.githubusercontent.com/25124/79403417-3eb30200-7fd2-11ea-8dd7-704bdcacaeab.png)

**Comment by brandonkelly** [comment]
We just released Feed Me 4.3.1 with a fix for this.
