### ISSUE TITLE
Feed with "Add & Disable" strategy always disables all elements in section

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/feed-me#696]
### Description
My paginated feed runs successfully the first time and populates the section with all 3 pages of data, but on subsequent runs, every entry is disabled. In the debug output for the feed, every node is skipped on the second run (no content has changed) but then: 

`The following elements have been disabled: ["6","38","8","40","10","42","12","44","14","46","16","48","18","20","22","24","26","28","30","32","2","34","4","36"].`

I've tried every field as the source for matching elements with the same results. I've also tried just running the first page without pagination with the same results.

### Steps to reproduce
1. Set up a feed with https://madebyraygun.com/projects/mock-users/page-1.json as the source. Use the "Create New Elements" and "Disable Missing Elements" strategy and "nextPage" as the pagination URL. 
2. Run the feed once to successfully populate the section.
3. Run the feed again to disable all entries in the section.

### Additional info
Fresh Craft installation with 1 section and 2 fields. 
Sample database is [here.](http://madebyraygun.com/projects/mock-users/feedme.db.zip)
Debug text [here.](http://madebyraygun.com/projects/mock-users/debug.txt)
Relevant log files [here.](http://madebyraygun.com/projects/mock-users/logfiles.zip)

- Plugin version: 4.2.2
- Craft version: 3.4.17.1

**Comment by angrybrad** [comment]
Just cut FeedMe 4.2.3 with a fix for this.
