### ISSUE TITLE
When creating parent entries the first entry with a specific parent doesn't get that parent assigned

### ISSUE THREAD

**Issue by rmales** [craftcms/feed-me#698]
### Description

If I set up a feed to create parent entries when they don't exist the first entry that is created by the feed doesn't get that parent entry assigned.

I think this is because in the Feed Me `parseParent` method, the child entry's `newParentId` property is not set in the branch that runs when the parent entry does not exist. See: https://github.com/craftcms/feed-me/blob/dc14484d62a739b343f952874ede85490ff600f6/src/elements/Entry.php#L148-L168

### Steps to reproduce

My data structure is something like this:
```
[
  {
    "chapter": "Introduction",
    "title": "Introduction",
    "text": "…",
    "images": []
  },
  {
    "chapter": "Introduction",
    "title": "Contents",
    "text": "…",
    "images": []
  },
…
```
In my feed I select parent entries based on the 'chapter' property (mapped to the parent entry title) and chose to create entries if they don't exist.

### Additional info

- Plugin version:  4.2.2
- Craft version: 3.4.18

**Comment by i-just** [comment]
Thanks for reporting. It was fixed as part of this issue: https://github.com/craftcms/feed-me/issues/1154
