### ISSUE TITLE
Collapsed checkbox on Matrix blocks not working

### ISSUE THREAD

**Issue by Friksel** [craftcms/feed-me#709]
### Description
It doesn't matter if Collapsed in the matrix blocks of the FeedMe Matrix blocks list is checked or not, in the output the Matrix Blocks will be displayed opened, never collapsed.

### Steps to reproduce

See above

### Additional info

- Plugin version: 4.2.3
- Craft version: 3.4.23

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1284 for the next v4 and v5 releases.
