### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/feed-me#715]
Found a few broken links in the docs...

https://docs.craftcms.com/feed-me/v4/feature-tour/creating-your-feed.html#backup

![feed-me@2x](https://user-images.githubusercontent.com/5309692/86062572-dc3ca000-ba1d-11ea-90cd-bd13c20d2f8e.png)

Might be worth running a broken link checker across the whole set of Feed Me docs.

**Comment by mattstein** [comment]
Thanks @lindseydiloreto! Just fixed and double-checked, so after a healthy refresh you shouldn’t be able to find any broken links in the docs. 🤞

**Comment by lindseydiloreto** [comment]
Fantastic, thanks @mattstein! 🍺
