### ISSUE TITLE
High CPU usage can't update table

### ISSUE THREAD

**Issue by AlexandreCarvalhoDeMelo** [craftcms/feed-me#717]
### Description
Hello guys, i've been encountering this problem from to time
every time i import a specific feed the CPU goes wild and i end up with the following error on production

sendto(4, "x\0\0\0\3UPDATE `structureelements` "..., 124, MSG_DONTWAIT, NULL, 0) = 124
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "0\0\0\1\0\0\0\3\0\0\0(Rows matched: 0  Cha"..., 7804, MSG_DONTWAIT, NULL, NULL) = 52
sendto(4, "\31\0\0\0\3RELEASE SAVEPOINT LEVEL1", 29, MSG_DONTWAIT, NULL, 0) = 29
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 7752, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "<\0\0\0\3SELECT *\nFROM `structureele"..., 64, MSG_DONTWAIT, NULL, 0) = 64
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 7741, MSG_DONTWAIT, NULL, NULL) = 957
sendto(4, "}\0\0\0\3SELECT *\nFROM `structureele"..., 129, MSG_DONTWAIT, NULL, 0) = 129
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 6784, MSG_DONTWAIT, NULL, NULL) = 847
sendto(4, "\21\0\0\0\3SAVEPOINT LEVEL1", 21, MSG_DONTWAIT, NULL, 0) = 21
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 5937, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "H\0\0\0\3SELECT *\nFROM `structureele"..., 76, MSG_DONTWAIT, NULL, 0) = 76
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 5926, MSG_DONTWAIT, NULL, NULL) = 957
sendto(4, "[\0\0\0\3DELETE FROM `structureeleme"..., 95, MSG_DONTWAIT, NULL, 0) = 95
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 4969, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "x\0\0\0\3UPDATE `structureelements` "..., 124, MSG_DONTWAIT, NULL, 0) = 124
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "0\0\0\1\0\0\0\3\0\0\0(Rows matched: 0  Cha"..., 4958, MSG_DONTWAIT, NULL, NULL) = 52
sendto(4, "x\0\0\0\3UPDATE `structureelements` "..., 124, MSG_DONTWAIT, NULL, 0) = 124
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "0\0\0\1\0\0\0\3\0\0\0(Rows matched: 0  Cha"..., 4906, MSG_DONTWAIT, NULL, NULL) = 52
sendto(4, "\31\0\0\0\3RELEASE SAVEPOINT LEVEL1", 29, MSG_DONTWAIT, NULL, 0) = 29
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 4854, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "<\0\0\0\3SELECT *\nFROM `structureele"..., 64, MSG_DONTWAIT, NULL, 0) = 64
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 4843, MSG_DONTWAIT, NULL, NULL) = 957
sendto(4, "}\0\0\0\3SELECT *\nFROM `structureele"..., 129, MSG_DONTWAIT, NULL, 0) = 129
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 3886, MSG_DONTWAIT, NULL, NULL) = 847
sendto(4, "\21\0\0\0\3SAVEPOINT LEVEL1", 21, MSG_DONTWAIT, NULL, 0) = 21
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 3039, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "H\0\0\0\3SELECT *\nFROM `structureele"..., 76, MSG_DONTWAIT, NULL, 0) = 76
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\nF\0\0\2\3def\nrecovered1\21structu"..., 3028, MSG_DONTWAIT, NULL, NULL) = 957
sendto(4, "[\0\0\0\3DELETE FROM `structureeleme"..., 95, MSG_DONTWAIT, NULL, 0) = 95
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 2071, MSG_DONTWAIT, NULL, NULL) = 11
sendto(4, "x\0\0\0\3UPDATE `structureelements` "..., 124, MSG_DONTWAIT, NULL, 0) = 124
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "0\0\0\1\0\0\0\3\0\0\0(Rows matched: 0  Cha"..., 2060, MSG_DONTWAIT, NULL, NULL) = 52
sendto(4, "x\0\0\0\3UPDATE `structureelements` "..., 124, MSG_DONTWAIT, NULL, 0) = 124
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000^Cstrace: Process 15094 detached

I noticed that when i run this importer craft runs 5700 queries is that normal?
thanks!

**Comment by AlexandreCarvalhoDeMelo** [comment]
Just in case you wondering the consumed json file is small

**Comment by angrybrad** [comment]
Can you send a database dump, composer.json file and a sample feed over to support@craftcms.com so we can try to reproduce?
