### ISSUE TITLE
After saving mapping step, resulting page says my feed 'has been queued up' but it has not.

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/feed-me#719]
### Description
After saving the mapping step of my import, I end up on a page that state that my queue '...has been queued up' (this template: https://github.com/craftcms/feed-me/blob/master/src/templates/feeds/_status.html). However, this is not the case. My feed have been saved, but I have not yet triggered it. It is not yet in the queue. 

I think this is confusing.

### Steps to reproduce

1. Save the mapping step of a feed
2. Read the resulting message

### Additional info

- Craft version: 3.4.27
- PHP version: 7.3
- Database driver & version:
- Plugins & versions: FeedMe 4.2.0.1

**Comment by Friksel** [comment]
I agree with you on that the terminology here is confusing. I also had to think twice when start using this plugin weeks ago. But I think that they mean by 'queued up' that the feed is saved and ready to run. When you click on the link it directly runs, so is 'queued up' in a way. But that has nothing to do with the queue of Craft itself.

**Comment by angrybrad** [comment]
This has been resolved in the 4.3.0 release.
