### ISSUE TITLE
Feed Me import only one matrix block

### ISSUE THREAD

**Issue by ernestobleijenberg** [craftcms/feed-me#726]
When importing an external json file, only 1 item is imported into a matrix block. I want to import both "text" and "Image" from a news article (json file) into craftCMS, and import these in separate blocks in the Matrix. So if I assign both text and image to an field in de Matrix Block in de Feed Me plugin, only one of them is imported. Mostly the one on top.

I have tested the plugin on multiple environments, but it does not work properly on all.

Is this problem known? If so, what is the solution?

**Comment by olivierbon** [comment]
Malformed `JSON` - [See documentation](https://docs.craftcms.com/feed-me/v4/guides/importing-into-matrix.html)

Resolved in support.
