### ISSUE TITLE
[3.5.0-RC4] Extra Space Between Unique Identifier Checkboxes

### ISSUE THREAD

**Issue by ademers** [craftcms/feed-me#727]
### Description

There appears to be extra space between the checkboxes related to CSS margins.

### Steps to reproduce

1. Update a 3.4.x site to 3.5.0-RC4.
2. View `Set a unique identifier to match against existing elements` in an existing FeedMe feed.
3. Notice extra space between checkboxes.
4. Screenshot: https://share.getcloudapp.com/kpub1zlo

### Additional info

- Craft version: 3.5.0-RC4
- PHP version:
- Database driver & version:
- Plugins & versions: FeedMe 4.2.3

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now with a fix for this.
