### ISSUE TITLE
Importing JSON with single root element causes errors

### ISSUE THREAD

**Issue by studiosyntax** [craftcms/feed-me#746]
### Description
Importing a JSON feed with a single root element and three properties, results in Feed Me thinking it's 3 seperate nodes and importing does not work. 

I've tried the same request with Insomnia, which results in this JSON response:

```
{
  "error": false,
  "access_token": "XXXXXXXXXXXXXXXXX",
  "expires_on": "November, 14 2020 17:26:05 +0100"
}
```

Trying to import that with Feed Me shows this in the logs:
```
info | FeedName get token: Processing 0 elements finished in 0.00s | 14-09-2020 17:28
error | FeedName get token: Starting processing of node #3.Show detail | 14-09-2020 17:28
error | FeedName get token: Starting processing of node #2.Show detail | 14-09-2020 17:28
error | FeedName get token: Starting processing of node #1. Details:
 ↳ Undefined offset: 0 - Process.php: 184
```

Not sure if this is just a wrong JSON response to begin with, but I've worked with similar setups before. 

### Steps to reproduce

1. Create a feed which points to a JSON endpoint with a single root element and 3 properties
2. Map the fields
3. Run the feed, get errors
3. No profit 

### Additional info

- Craft version: 3.4.30
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: 
  - Feed Me 4.2.3
  - SuperTable 2.6.4

**Comment by kristiansp** [comment]
I guess Feed Me expects a list of elements, even if it's a list of one. If you are able to wrap it in brackets `[]`, I guess it should work.

**Comment by studiosyntax** [comment]
I guess so too. Probably not really a Feed Me bug, though it would help if Feed Me could somehow see and work with the single object. I'll see if I can convince the company who's API we're calling to wrap this in brackets.
