### ISSUE TITLE
Saving a feed says it's been queued up, but doesn't run

### ISSUE THREAD

**Issue by darylknight** [craftcms/feed-me#751]
### Description

When you create a feed, finish it off and save it, FeedMe takes you to a screen that says "Feed has been queued up" with a button to go to queue manager, but queue is empty, and the feed doesn't run until you go back to the FeedMe settings and click Run Feed manually.

![image](https://user-images.githubusercontent.com/1250017/93859503-5e0f3300-fcc6-11ea-81d2-e2d69a131f65.png)

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.8
- Database driver & version: MySQL
- Plugins & versions: FeedMe 4.2.3

**Comment by angrybrad** [comment]
This has been resolved in [4.3.0](https://github.com/craftcms/feed-me/blob/develop/CHANGELOG.md#430---2020-11-06)
