### ISSUE TITLE
Entry status not getting changed to "disabled" when updating entries from import

### ISSUE THREAD

**Issue by brimby** [craftcms/feed-me#760]
### Description

If an already existing enabled entry is to be updated from an import to have a status of disabled, the status does not change.

### Steps to reproduce

1. Have an enabled entry.
2. Run a json import with an entry that corresponds to the existing enabled entry, and the only changed value is a value of 0 on the property that is linked to the status attribute of the entry. You can have the default value of the field as either "Don't import" or "disabled" and the result should be the same.
3. Run import which is set to "add and update and delete" entries. Status on updated entry should remain as enabled, in spite of the 0 value on the import.
4. If you delete the entry and run the import again, the entry should be created as disabled (as it should), so the bug only seems to relate to updating entries and not when "adding" them.

### Additional info

- Craft version: 3.5.13.2
- PHP version: 7.2
- Database driver & version:
- Plugins & versions: Feed Me 4.2.4

**Comment by kristiansp** [comment]
@brimby If you explicitly give the status field the value of disabled, it would make sense that it also disables the entry when you have import strategy set to update, no? I mean, in this case the disabling of the entry is a side effect of the import (whereas disable as an import strategy will disable existing entries that don't appear in the feed). Or did I misunderstand?

**Comment by gstjohn** [comment]
Experiencing the same and have found a fix. PR incoming.

**Comment by brimby** [comment]
The issue is that the status doesn't change to disabled when i give it a
field value of disabled. It remains enabled.

**Comment by brimby** [comment]
Nice!

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now @gstjohn’s PR #765.
