### ISSUE TITLE
Undefined offset in Process.php when handling a JSON feed with array keys

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/feed-me#761]
### Description

The import of our JSON feed fails with the error `Undefined offset: x - Process.php: 184`. We found out that this is happening because the JSON feed has an array key for each child element.

For example, this feed will fail:

````
{
    "2799": {
        "stockId": "2799",
        "brand": "Mercedes-Benz",
        "model": "SK 3028"
    },
    "2829": {
        "stockId": "2829",
        "brand": "Volvo",
        "model": "FL12 280"
    },
    "2844": {
        "stockId": "2844",
        "brand": "Renault",
        "model": "Premium 450"
    },
    "2615": {
        "stockId": "2615",
        "brand": "Schmitz Cargobull",
        "model": "SCS 24/L-13"
    }
}
````

While this feed will work:

````
[
    {
        "stockId": "2799",
        "brand": "Mercedes-Benz",
        "model": "SK 3028"
    },
    {
        "stockId": "2829",
        "brand": "Volvo",
        "model": "FL12 280"
    },
    {
        "stockId": "2844",
        "brand": "Renault",
        "model": "Premium 450"
    },
    {
        "stockId": "2615",
        "brand": "Schmitz Cargobull",
        "model": "SCS 24/L-13"
    }
]
````

**Noteworthy**
The funny thing is, the first example will succeed when clicking on the "Debug" button at the feed. That one will show an example of the generated array and results in a successful import, while clicking on the "Run feed" link fails.
_Offtopic:_ Is it expected behaviour that the "Debug" button will run an actual import? Shouldn't it be a dry run?

### Additional info

- Craft version: 3.5.14
- PHP version: 7.3
- Database driver & version: mariadb 10.4
- Feedme version: 4.2.4

**Comment by brandonkelly** [comment]
Feed Me 4.3.0 is out now with a fix for this. Thanks for reporting!

**Comment by rickmills** [comment]
Just a heads up, on 4.3.1 this is still happening. 

Example error in the feedme log: `Undefined offset: 1177 - Process.php: 191`

Example data:

```json
{
  "71825": {
    "pageId": 71825,
    "parentId": 11420,
    "appId": 17189,
    "title": "A title",
    "content": "lots-of-html-stripped",
    "objects": {
      "files": null,
      "images": null
    }
  },
  "81785": {
    "pageId": 81785,
    "parentId": 11420,
    "appId": 18725,
    "title": "Example Title",
    "content": "lots-of-html-stripped",
    "objects": {
      "objects": {
      "files": [
        "http://example.com/example.doc",
        "http://example.com/example2.doc"
      ],
      "images": null
    }
  },
  [...]
}

```

Completely speculating here but could it possibly down to the list of items not being in numeric order?

**Comment by angrybrad** [comment]
Should really be fixed in https://github.com/craftcms/feed-me/commit/b96465cd0d5ffa0d1c81f8940de562eefac08e92 - will get out an official release soon.

**Comment by bfjare** [comment]
I'm getting this same error with XML. Importing from EE.  The XML is validated and these were working before.  The error happens when mapping fields.

_PHP Notice – yii\base\ErrorException
Undefined offset: 1_

Here is the XML structure.

`<?xml version="1.0" encoding="UTF-8"?>
<studies>
	{exp:channel:entries 
		channel="academy_studies"
		disable="" 
		limit="500" 
	}
		<study>
			<count>{count}</count>
			<title><![CDATA[{title}]]></title>
			<slug>{url_title}</slug>
			<categories>
				{categories}
					<category>
						{category_name}
					</category>
				{/categories}
				<category></category>
			</categories>
			<post-date><![CDATA[{entry_date format="%Y/%m/%d"}]]></post-date>
			<image><![CDATA[{banner_image}]]></image>
			<project-description-alternate-title><![CDATA[{project_description_alt_title}]]></project-description-alternate-title>
			<study-description><![CDATA[{study_description}]]></study-description>
			<key-findings-alternative-title><![CDATA[{key_findings_alt_title}]]></key-findings-alternative-title>
			<keyfindings><![CDATA[{key_findings}]]></keyfindings>
			<reccomendations-alternative-title><![CDATA[{recommendations_alt_title}]]></reccomendations-alternative-title>
			<reccomendations><![CDATA[{reccomendations}]]></reccomendations>
			<report>
				{report}
					<report>
						<pdf><![CDATA[{report:pdf}]]></pdf>
						<button-label><![CDATA[{report:button_label}]]></button-label>
					</report>
				{/report}
			</report>
			<related-accounts>
				{related_accounts}
					<account>
						<![CDATA[{related_accounts:username}]]>
					</account>
				{/related_accounts}
				<account></account>
			</related-accounts>
		</study>
	{/exp:channel:entries}
</studies>`
