### ISSUE TITLE
"Import strategy" checkboxes can't be changed with feed-me version 4.3.0

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/feed-me#769]
### Description

I've updated to the latest version and I can no longer change the "Import strategy" checkboxes. No matter what I select, after saving the settings, only the first checkbox remains checked (Create new elements).

### Steps to reproduce

1. Have the newest feed-me plugin (4.3.0)
2. Create a new feed
3. Set element type to "Entry"
4. Change the "Import strategy", e.g. select "Create new elements", "Update existing elements" and "Delete missing elements")
5. Hit save

![Schermafbeelding 2020-11-08 om 18 03 01](https://user-images.githubusercontent.com/1608184/98471457-b190fe00-21ec-11eb-8f11-fffd563f0efe.png)

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.3
- Database driver & version: MariaDB 10.4
- Plugins & versions: Feed-me 4.3.0

**Comment by thijskaspers** [comment]
Addition: found out this only happens when element type is set to "Entry"

**Comment by johndwells** [comment]
Came here to report this - however it isn't that the values aren't being _saved_, it is that the checkboxes are not re-checked when you re-visit the settings page. So it means that EVERY time you want to edit a field, you have to be sure to re-check those boxes desired.

**Comment by brandonkelly** [comment]
Sorry about that. Just released 4.3.1 with a fix for this.
