### ISSUE TITLE
Feed me - Single - Calling unknown method: craft\fields\Entries::getBlockTypeFields() - Component.php: 300

### ISSUE THREAD

**Issue by KoeketieneDesign** [craftcms/feed-me#771]
### Description
Trying to migrate over data into a single but getting an error `Calling unknown method: craft\fields\Entries::getBlockTypeFields() - Component.php: 300`

<img width="1427" alt="Screenshot 2020-11-10 at 16 41 33" src="https://user-images.githubusercontent.com/20947573/98696377-00b56b00-2374-11eb-9c96-6d06b24a9d29.png">

### Additional info

- Craft version: 3.5.15.1
- Plugins & versions: Feed Me - 4.3.1

**Comment by angrybrad** [comment]
This error ended up being because Feed Me doesn't support nested Matrix + Super Table importing: https://github.com/craftcms/feed-me/issues/470
