### ISSUE TITLE
How to stop a feed from running/processing after it has started?

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/feed-me#772]
When we delete a feedme task from the queue manager, the feed processing still continues in the background. We've noticed this because many new "Updating search indexes" tasks are still being spawned, and also new assets are still being uploaded in the background.

This can be annoying when you've noticed a bug during import, and the feed has hundreds of entries to process.
What is the correct way of stopping a feedme import after it has started?

**Comment by ben-callaway** [comment]
I've found this. Only way to truly stop it is kill the task in FeedMe, restart Supervisor (if using), PHP and sometimes the server!

**Comment by shaunmolloy** [comment]
Also came across this.

Restarting services may not always be an option for shared servers.

I deleted the product type and added it back as a workaround.
