### ISSUE TITLE
Slug not updating for other site/language imports

### ISSUE THREAD

**Issue by Qronicle** [craftcms/feed-me#773]
### Description

We have a multilingual site setup, and are importing our entries from an existing platform. First we import all the data for the main website (title is mapped, slug is left empty and will thus be auto-generated from title). This is all working okay, entries are created, slugs reflect the titles. (We also store our old ID to an "original ID" field to reference this entry later on.)

We then have another feed for the second website/language, this one is similar to the first feed, but is linked to the website with the other language, and only updates data to existing entries. Again, title is mapped and slug is left empty, and original ID is used to match for existing entries. This all works flawlessly as well: when we switch website in the backend of the entry, we see the translated title as expected. *However*, the slug for this translated entry is still the slug that was generated for the original entry.

A few members of my team swore that this wasn't the case in the past, and the slug would reflect title changes. Me, I'm not too sure because I'm pretty new to Craft, but is there a way to make the slug reflect title changes automatically, or is it expected to work this way?

I've been reading (or at least trying to read) the feedme code, but I can't seem to find anything that handles the conversion of titles to slugs before saving, so I suppose this is handled by the base cms package code.

### Steps to reproduce

See above

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4
- Database driver & version: Mariadb 10.5.6
- Plugins & versions: Feed me 4.3.1

**Comment by iparr** [comment]
I just wanted to say that this happens to me and I wish it didn't.

- Craft version: 3.5.15.1
- PHP version: 8.2
- Database driver & version: MySQL 8.0.33
- Plugins & versions: Feed me 5.1.3.1

My plan now is to try and write something that manipulates / translates a slug field before import and using that field for the slug rather than expecting it to just adopt what is in the title.

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

Let’s say we have 2 sites and a channel section in our CMS. The channel section is enabled for both sites, the propagation method is set to “Save entries to all sites enabled for this section”, and the entry type for the channel has the title set to be translatable for each site. 

If you go to `site1` in the CMS and create a new entry for that channel, it’s created for both sites. The slug is generated based on the title. The title and slug are used for this entry on both sites. If you then switch to `site2`, you can change the title, but the slug won’t automatically get updated (though you can change it manually).

The same thing will happen when importing via Feed Me. When you run your first feed, the entry gets created, and the slug is autogenerated. When you run the second feed and the existing entry is found, the title gets updated, but the slug won’t get autogenerated again. You’d have to provide a new value in your feed for it to get updated or use the trick suggested by @iparr.

I hope this helps clear things up!
