### ISSUE TITLE
Cannot import commerce product when setting default variant price to 0

### ISSUE THREAD

**Issue by piotrpog** [craftcms/feed-me#779]
This causes error:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'price' cannot be null The SQL being executed was: INSERT INTO commerce_variants (id, productId, sku, price, width, height, length, weight, minQty, maxQty, stock, isDefault, sortOrder, hasUnlimitedStock, dateUpdated, dateCreated, uid) VALUES (6814, 6813, 'TH/714/03', NULL, '0', '0', '0', '0', NULL, NULL, NULL, 0, 1, NULL, '2020-12-01 19:36:22', '2020-12-01 19:36:22', '386466ca-97a6-4d29-b158-0db6eff466de') - Schema.php: 677.

**Comment by piotrpog** [comment]
I also notices similar error with stock with value 0. This time not set as default value, but taken from XML property of source:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'stock' cannot be null The SQL being executed was: INSERT INTO commerce_variants (id, productId, sku, price, width, height, length, weight, minQty, maxQty, stock, isDefault, sortOrder, hasUnlimitedStock, dateUpdated, dateCreated, uid) VALUES (7279, 7278, 'TH/1454', '189', '0', '0', '0', '0', NULL, NULL, NULL, 1, 1, NULL, '2020-12-02 14:30:51', '2020-12-02 14:30:51', '718c1aa0-a750-4716-b4c1-644af4030714') - Schema.php: 677.

**Comment by piotrpog** [comment]
Little info - i managed to overcome this error temporarly using this: 

```
Event::on(
    \craft\commerce\elements\Variant::class, 
    \craft\base\Element::EVENT_BEFORE_SAVE, 
    function(\craft\events\ModelEvent $e) {
        if($e->sender->stock = ''){
        	$e->sender->stock = 0;
        }
        if($e->sender->price = ''){
        	$e->sender->stock = 0;
        }        
    }
);
```

**Comment by piotrpog** [comment]
Temporaty fix:
```
Event::on(
    \craft\commerce\elements\Variant::class, 
    \craft\base\Element::EVENT_BEFORE_SAVE, 
    function(\craft\events\ModelEvent $e) {

    if($e->sender->stock == null){
    	$e->sender->stock = 0;
    }     

    }
);
```

**Comment by skramstad** [comment]
I think this one is related https://github.com/craftcms/feed-me/issues/724
@piotrpog thanks for posting a temp fix.

**Comment by piotrpog** [comment]
@skramstad 
Well bug was already fixed, but for future reference, you need to put such code in your module file, in `init()` function.

**Comment by joepagan** [comment]
As this seems the most appropriate place for it, just want to highlight if you are smooth brained like me you can still hit this SQL violation if you have set a default value, but you haven't explicitly selected the `use default value` option in the dropdown.

Will trigger error:
![image](https://user-images.githubusercontent.com/2337910/146197557-f40353dc-71fa-46a6-b6f1-770bcf73fe46.png)
 
You'll be fine:
![image](https://user-images.githubusercontent.com/2337910/146197630-2666f3f0-ef07-4eb0-9f00-a58f76194af1.png)

cc @angrybrad seems like you've helped with this before (sorry to bother you), would be better UX if the default value field would only appear when the right dropdown option is selected, or, maybe some strikethrough/greyed out input which changes on the selected option if you wanted to add to your never ending task list.

**Comment by yalamber** [comment]
I am getting same error in craft commerce 4. Any solution for this in craft coffers 4
