### ISSUE TITLE
Nested subcategories with the same slug, different parent, only imports the last sub-category

### ISSUE THREAD

**Issue by anchovy** [craftcms/feed-me#780]
### Description
We're importing nested categories patent/child into a category via csv, leaving the slug blank, so feedme is generating the slug off the title.
Feedme is then using the slug to check for existing subcategories, but it's ignoring the parent category - so is matching parentA - subcat with parentZ - subcat and so not adding parentA - subcat 

### Steps to reproduce
Create an csv import matching 

_parent,subcat_
breakfast,coffee
breakfest,cornflakes
lunch,cheese
lunch,sandwich
lunch,fruit
dinner,cheese
dinner,pasta
dinner,fruit
dinner,coffee

![image](https://user-images.githubusercontent.com/599005/100815852-c4c08200-34a9-11eb-8018-dc5ab04d103c.png)

#### Which I'd expect after running the import is:
breakest
 * coffee
 * cornflakes

lunch
 * cheese
 * sandwidge
 * fruit

 dinner
 * cheese
 * pasta
 * fruit
 * coffee

but what we are getting is:

breakest
 * cornflakes

lunch
 * sandwich

dinner
 * cheese
 * pasta
 * fruit
 * coffee

If I add another column to the csv, slug, and set this to the slug in feedme, it works correctly - but then we're left with unslightly slugs i.e. www.site/category/lunch/lunch-cheese when we want www.site/category/lunch/cheese and www.site/category/dinner/cheese etc.

_parent,subcat,slug_
breakfast,coffee,breakfast-coffee
breakfest,cornflakes,breakfast-cornflakes
lunch,cheese,lunch-cheese
lunch,sandwidge,lunch-sandwich
lunch,fruit,lunch-fruit
dinner,cheese,dinner-cheese
dinner,pasta,dinner-pasta
dinner,fruit,dinner-fruit
dinner,coffee,dinner-coffee

![image](https://user-images.githubusercontent.com/599005/100815904-ddc93300-34a9-11eb-9ce5-e4340a72a90c.png)

### Fix
Matching via slug should take into account the parent slug - so we can have nestled categories with the same name and slug, which will all be unique when associated with their parent category.

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.31
- Plugins & versions:  Feed Me | 4.2.4

**Comment by i-just** [comment]
Hi, thanks for reaching out and apologies for the late response. I just raised a PR that will allow the Parent to be selected as a unique identifier. In your case, you’d want to select both Title and Parent as unique identifiers, which would allow the data to be imported as expected:

<img width="2087" alt="Screenshot 2023-06-30 at 16 09 59" src="https://github.com/craftcms/feed-me/assets/4500340/d6d1b954-3f0d-44fb-970c-e743c30efe50">

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1343 for the next v4 and v5 releases.
