### ISSUE TITLE
Feedme 4.3.3 breaks importing of remote assets

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/feed-me#787]
Since updating to the latest version (4.3.3) remote images are no longer downloaded and saved. I've downgraded feedme to 4.3.2 and that one works.

We've had a lot of images connected to entries from previous feed imports (stored in a Matrix field), but after running "Process feed" with Feedme 4.3.3, the matrix field is now blank for all entries.

![Schermafbeelding 2020-12-14 om 15 07 34](https://user-images.githubusercontent.com/1608184/102090738-1e1ba000-3e1e-11eb-8e32-90805ad9df18.png)

Image array is empty in the logs, not doing anything.

Here are the feed settings for that Matrix field:

![Schermafbeelding 2020-12-14 om 15 08 44](https://user-images.githubusercontent.com/1608184/102090894-54f1b600-3e1e-11eb-8110-09292e18f1ce.png)

As you can see the Matrix field has 1 text field and 1 asset field. After processing the feed, the Matrix field is blank for all handled entries, so the text field isn't importing either.

I'm not sure yet if the asset or the matrix field is the issue, but it's probably related to this commit: https://github.com/craftcms/feed-me/commit/ac930ca61c029ac024c66e1b3e1c2a45d146f60f, since not much else has changed in 4.3.3 that's related to Assets?

### Steps to reproduce

1. Create a Matrix field with 1 text field and 1 asset field
2. Map the Matrix field to a Feedme feed that uses remote images
3. Run the feed

### Additional info

- Craft version: Craft 3.5.16
- PHP version: 7.3
- Database driver & version: MariaDB 10.5

**Comment by angrybrad** [comment]
@thijskaspers Any chance you could send a db dump and your composer.json file to support@craftcms.com?

**Comment by angrybrad** [comment]
@thijskaspers not 100% sure if it'll fix what you're seeing, but can you test https://github.com/craftcms/feed-me/commit/482e0db276c65e3c03b7b47e8d8efda824d583fb and see if it helps? If you're still seeing your issue, https://github.com/craftcms/feed-me/issues/787#issuecomment-744628878 will help us debug it.

**Comment by thijskaspers** [comment]
@angrybrad just tested 4.3.4 which has https://github.com/craftcms/feed-me/commit/482e0db276c65e3c03b7b47e8d8efda824d583fb in it, and can confirm that it is working again 👍 . So it had nothing to do with the assets after all, thank for the quick fix!
