### ISSUE TITLE
CSV Feed No Longer Works in Craft 3.6.2

### ISSUE THREAD

**Issue by acantes** [craftcms/feed-me#798]
### Description

Since upgrading a local version of a website I'm developing to Craft 3.6.2 (from 3.5.x) Feed Me can no longer find any Primary Elements in the CSV file I am looking to import nightly. It was doing so correctly before. 

I just see the dreaded "/root (x0 element)" in the Primary Element dropdown.

The feed has not changed during this time, and I have tested the same with a fresh test project, so I suspect something could be up.

Happy to send the location of the CSV file in a DM if that helps.

### Additional info

- Craft version: 3.6.2
- Feed Me version: 4.3.4
- PHP version: 7.4.11

**Comment by TheBlendNews** [comment]
I'm having the same issue with a file that previously used to work in another CraftCMS install. I can't figure out what it is either. I just see /root (x0 element) and there is no way to debug it. I just tried with a local and a remote file as well.

**Comment by TheBlendNews** [comment]
I'll post my info as well:

Craft: 3.6.2
FeedMe: 4.3.4
PHP: 7.4.14

The last install it worked on was an older version of craft, so your theory makes sense. Additionally XML and stuff still works fine.

**Comment by angrybrad** [comment]
Can someone send a database dump, composer.json/lock files and a sample feed for us to try and reproduce locally?

**Comment by TheBlendNews** [comment]
> Can someone send a database dump, composer.json/lock files and a sample feed for us to try and reproduce locally to [support@craftcms.com](mailto:support@craftcms.com)?

Sent!

**Comment by acantes** [comment]
> Can someone send a database dump, composer.json/lock files and a sample feed for us to try and reproduce locally to [support@craftcms.com](mailto:support@craftcms.com)?

Also sent. Thank you!
