### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by myleshyson** [craftcms/feed-me#802]
### Description
I can't require the craftcms/feed-me package via composer because it's ralouphie/mimey dependency only supports php 7.
This happens when changing the platform requirement in `composer.json` from the default 7.2.5 to 8.0. 

It seems like that mimey package is dead too. Last commit was 2 years ago.

### Steps to reproduce

1.  Update the default platform requirement setting in crafts composer.json file to 8.0
2. try to run `composer require craftcms/feed-me`
3. see the following
![Screen Shot 2021-02-04 at 3 07 40 PM](https://user-images.githubusercontent.com/11747187/106949276-bcc7cd00-66fa-11eb-9068-24ff65f37663.png)

### Additional info

- Craft version: 3.6.2
- PHP version: 8.0.1
- Database driver & version: mysql 8
- Plugins & versions: feed-me plugin ^4.3

**Comment by angrybrad** [comment]
Thanks... went with Craft's `FileHelper::getExtensionByMimeType()` instead.

**Comment by myleshyson** [comment]
Haha sweet! Brand new to craft and had no idea that function existed. Glad it's resolved.
