### ISSUE TITLE
Error on Asset Import:  Class 'Mimey\MimeTypes' not found - AssetHelper.php: 317

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/feed-me#804]
### Description

When running an import with an external asset URL, I'm getting this error for every image field:

`Class 'Mimey\MimeTypes' not found - AssetHelper.php: 317`

### Steps to reproduce

1. Setup an import with an asset field
2. Set the asset field to fetch an external image url

### Additional info

- Craft version: 3.5.18
- PHP version: 7.1
- Database driver & version: MariaDB
- Plugins & versions: Feed Me 4.3.5

**Comment by angrybrad** [comment]
Sorry about that... just released 4.3.5.1 with the fix.

**Comment by loqus** [comment]
Got a File(/etc/xdg) is not within the allowed path(s): when updating this release

**Comment by angrybrad** [comment]
@loqus Can you share a full stack trace leading up to that error? Does your php.ini file have [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) restrictions in place?

**Comment by loqus** [comment]
Yeah I had an open_basedir restriction. I don't have a fill stack trace. I added the path and retried the update. All went well.
