### ISSUE TITLE
Import of SEOMatic image through Feedme not working

### ISSUE THREAD

**Issue by sg-modlab** [craftcms/feed-me#813]
### Describe the bug
Trying to map an asset to the SEO image via Feedme is not working. Not sure if that is something to share here or something for Feedme.

### To reproduce
Steps to reproduce the behaviour:

Here is a snippet of the JSON being read by Feedme:

<img width="1236" alt="CleanShot 2021-02-19 at 18 12 07@2x" src="https://user-images.githubusercontent.com/529067/108571358-05c47780-72de-11eb-8dbf-480210e48e07.png">

### Expected behaviour
The image (which is confirmed to be in our assets) will be mapped and shown as a custom image in the SEO field associated with entry. Mapping the filename of the image should work.

### Versions
- SEOMatic version: 3.3.32
- Feedme version: 4.3.5.1
- Craft version: 3.5.17.1

**Comment by khalwat** [comment]
Could this be because the Asset IDs in SEOmatic are actually stored here: https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaBundleSettings.php#L92

...and what is here is just the URL or Twig for the image? https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/MetaGlobalVars.php#L74

**Comment by RedLucas** [comment]
I also have the same issue as https://github.com/nystudio107/craft-seomatic/issues/840. 

I did update the seomatic plugin to incorporate the fix on the seomatic side but to no avail.

We have multiple asset field imports for the same feed, one outside the seomatic field, and three within. I can see that the non-seomatic field is importing fine. In the logs I can see that while it does process the asset import, and change to an ID for the non-seomatic:
`info	↳ Blog: Search for existing asset with query {"status":null,"folderId":279,"kind":["image"],"limit":"1","filename":"filename.jpg","includeSubfolders":true}	4/8/2021 10:15 AM
info	↳ Blog: Found 0 existing assets: []	4/8/2021 10:15 AM
info	↳ Blog: Fetching remote image https://example.com/image_uploads/image/filename.jpg - filename.jpg	4/8/2021 10:15 AM
info	↳ Blog: Creating asset with content {"tempFilePath":"\/var\/www\/html\/storage\/runtime\/temp\/feedme\/filename.jpg","filename":"filename.jpg","newFolderId":"279","volumeId":"5","avoidFilenameConflicts":true,"scenario":"create","conflict":"index"}	4/8/2021 10:15 AM`

`info	↳ Blog: Data ready to import {"title":"New &amp; Improved: Announcing The Beginner's Guide To Link Building","slug":"link-building-guide","postDate":"2021-03-30T16:00:00.000000Z","authorId":39553,"blogImage":[961683],`

It does not take any action on the seomatic field. 

`info	↳ Blog: Data to update for blogImage: [961683].	4/8/2021 10:15 AM
info	↳ Blog: Data to update for seoSettings: {"metaGlobalVars":{"seoTitle":null,"seoDescription":"description text.","seoImage":"https:\/\/example.com\/image_uploads\/og_image\/60623570a87598.91393427.png","canonicalUrl":null,"twitterImage":"https:\/\/example.com\/image_uploads\/twitter_image\/606235707092a2.28766115.png","ogImage":"https:\/\/example.com\/image_uploads\/og_image\/60623570a87598.91393427.png"}}.	4/8/2021 10:15 AM`

**Comment by khalwat** [comment]
The feature is there, built into SEOmatic -- but apparently it isn't working as expected. Unclear if it's an SEOmatic integration bug or something to do with FeedMe.

**Comment by khalwat** [comment]
But now that you mention it, given the list of other plugins that are natively supported in FeedMe, maybe it would make sense that SEOmatic was integrated into the FeedMe plugin as a FR rather than:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/integrations/feedme/SeoSettings.php

**Comment by khalwat** [comment]
Based on looking over the code, I don't think this is a FeedMe issue, but rather an SEOmatic integration issue. I've re-opened the issue, and added my diagnosis to it:

https://github.com/nystudio107/craft-seomatic/issues/840#issuecomment-816147518

**Comment by angrybrad** [comment]
Going to close this out, then... ping me if you need anything @khalwat.

**Comment by engram-design** [comment]
For anyone following along, should be fixed in this [issue](https://github.com/nystudio107/craft-seomatic/issues/840#issuecomment-816259629) with SEOMatic's integration.
