### ISSUE TITLE
Importing 'Enabled' status doesn't work

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/feed-me#822]
### Description

Setting 'Enabled' status of Entries via an XML import is not working.
The FeedMe log shows that `"enabled":true` was detected and that the Entries were added or updated successfully:
```
info | ↳ My Test Import: Match existing element with data {"title":"Testing"}.    | 18/03/2021 05:43
info | ↳ My Test Import: Data ready to import {"title":"Testing","enabled":true}. | 18/03/2021 05:43
info | ↳ My Test Import: Entry #46886 added successfully.                         | 18/03/2021 05:43
```
But the Entries remain in the 'Disabled' state.
Data is imported successfully to all other fields.
Even if I set 'Status' to "Use default value" and the default value to "Enabled" it still does not update the status.

Some things to note:

- Entries are being added to a Channel Section
- The Section is available on multiple Sites (the import is targeting the Primary Site)
- Propagation Method is "Save entries to all sites enabled for this section"
- Default Status for the Primary Site is Disabled

### Steps to reproduce

- Import this xml file using Create and Update strategies:
```
<?xml version="1.0" encoding="UTF-8"?>
<entries>
  <entry id="688">
    <title>Testing</title>
    <status>Enabled</status><!-- I've also tried values of true and 1 here with same result -->
  </entry>
</entries>
```
- Set Title to `<title>` and Status to `<status>`
- Or use default value "Enabled" for Status
- Run feed...
- The added / updated Entry is Disabled (despite `"enabled":true` appearing in the Log)

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.15
- Database driver & version: MySQL 8.0.23
- Plugins & versions:
  - Campaign	1.19.1
  - Cloner	1.2.2
  - Control Panel Nav	3.0.15
  - Copy	1.0.3
  - Dashboard Begone	1.0.1
  - Feed Me	4.3.6
  - fortrabbit Object Storage Volume	2.1.0
  - Patrol	3.1.3
  - Redactor	2.8.5
  - SEOmatic	3.3.35

**Comment by dreadfullyposh** [comment]
I'm also seeing this behavior. Any chance you've found a fix?

**Comment by KarlBishop** [comment]
I used an ugly backwards workaround...

It only works if your XML contains **ALL** the entries you want `enabled` and **none** of the entries you want `disabled`:

1) Set all entries to `enabled` in the CP
2) When importing, tick one of these boxes based on your needs:

    - "Disable missing elements globally"
    - "Disable missing elements in the target site"

After the import, all entries not included in the XML will be `disabled`, leaving just the ones you wanted `enabled`.

**Comment by rathesDot** [comment]
I have a similar issue but with JSON imports. I tried `enabled`, `Enabled`, `live`, `1` and `true` as values but none of them work.

**Comment by dreadfullyposh** [comment]
I've been having moderate success with '1' but in quotes as a string. It does seem that it's not always consistent though.

**Comment by andrewcgregory** [comment]
Also experiencing what sounds like the same issue. We are importing a JSON feed of entries, pulled from another system. The import works fine, but it is inconsistent that the entries come in as enabled. If they are not enabled, then when we run the feed again it seems to enable them. Any chance on a fix for this as the workaround posted does not fit our requirements since the feed we are importing only has a set of data from the last 2 weeks, but we want to keep all of the previous data enabled in Craft.

**Comment by stevefloat** [comment]
We're also experiencing this issue - or at least one very similar - in Feed Me v4.3.6.

We have a JSON feed of entries with a mix of 'Enabled' and 'Disabled' statuses. We have a separate task to build this JSON feed to ensure all existing statuses from Craft are preserved.

I can see in the JSON file that the correct 'Disabled' status is set for my entry in question, however once the import runs the entry is set to 'Live'.

We have other entries where the statuses are correctly preserved. 

The primary difference for the entries where we see the status being _incorrectly_ applied, is that they were previously set to 'Live'. I have tested this by manually changing an entry from 'Live' to 'Disabled' in Craft, running the import (where the JSON feed has the correct 'Disabled' status) and can see the entry is reset to 'Live'.

I've been through our own set up many times to see if anything is interfering, however it feels like the above bug.

Any feedback would be helpful on this!

**Comment by bleepsandblops** [comment]
Encountering same issue as https://github.com/craftcms/feed-me/issues/822#issuecomment-935171228

**Comment by angrybrad** [comment]
Feed Me 4.5.1 is out with a fix for this. Thanks for reporting!
