### ISSUE TITLE
Importing categories doesn't limit search for existing categories to selected category group

### ISSUE THREAD

**Issue by ctigelaar** [craftcms/feed-me#836]
### Description
I tried importing some categories for a specific category group, but every time I ran it I got the error "There was a problem getting the parent element" for a specific category. It turns out the category title exists already in a different category group. But why is it trying to search for parents that don't belong to the selected category group in step 1 of the feed config? I expect it would search for existing parents within the limits of the selected category group.

### Steps to reproduce

1. Create two category groups and add some items to one group, be sure to include one with the title "Foo"
2. Create a JSON feed with entries for the second group, be sure to also include a category "Foo" in your JSON file. For example:
```json
[
  {"title": "Foo"},
  {"parentTitle": "Foo", "title": "John Doe"},
  {"parentTitle": "Foo", "title": "Jane Doe"}
]
```
3. Create a category import feed and select to add the items to the second category group.
4. For the field mapping, select "title" for the "Title" field, and "parentTitle" for the "Parent".
5. Run it and check the logs.
6. It will give you an error for the items that have the parent set to "Foo".

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4.12
- Database driver & version: MySQL 8.0.22
- Plugins & versions: Feed Me: 4.3.6

**Comment by i-just** [comment]
Hi, thanks for reporting. This was fixed as part of this issue: https://github.com/craftcms/feed-me/issues/1154
