### ISSUE TITLE
Certificate verification issues

### ISSUE THREAD

**Issue by tyssen** [craftcms/feed-me#842]
### Description
I'm working on an import of a feed from a Simple Machines Forum (SMF) which contains images from lots of external sources. Some of the images are importing OK, but most of them are failing with:

> fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed. 

I haven't been through all of the ones that have failed, but each one I've looked at, I can open directly in a browser tab. Most of them are `https` addresses. Some are `http` addresses that redirect to `https` versions. 

Most of ones that are failing are from `i.imgur.com` or the client's own domain (although I'm doing the import on my local copy of the site at the moment).

I've just found that the client's own domain is being protected by Cloudflare so it's possible we're running into [this issue](https://stackoverflow.com/questions/53321187/file-get-contents-ssl-operation-failed-from-my-own-server-only).

### Additional info

- Craft version: 3.6.12
- PHP version: 7.3.5
- Database driver & version: 5.7.28
- Plugins & versions: FeedMe 4.3.6

**Comment by angrybrad** [comment]
This is either a problem with the local SSL certificate chain on the server that Craft is installed on (likely) or the SSL certificate on the remote end that the feed lives on.

Nothing much FeedMe can do about that, but if it's still an issue comment back here and we can help investigate.
