### ISSUE TITLE
Slow to import many products as search index is updated

### ISSUE THREAD

**Issue by shaunmolloy** [craftcms/feed-me#843]
### Description

Been using feedme to import commerce products and I had a CSV
file that contains 131,358 lines. PHP ran out of memory with that,
for the memory_limit set to 256mb.

I split the file into 4 parts, containing around 33k lines in each file.
That allowed me to process the feeds and import products.

Though the import to create products with variants for just 131k
products has taken 1.5 days so far and it's still running for 1 out
of the 4 feeds.

I also needed to periodically delete search index updates from
the queue, for the site to continue working. Each morning (yesterday
and today) I deleted 8-13 million search index update rows.

```sql
DELETE FROM queue
WHERE description = 'Updating search indexes';
```

Is this related to why the process is so slow? It shouldn't really take
a few hours to import that many products, not a few days.

**Comment by angrybrad** [comment]
Just released Feed Me 4.4.0 where you have to option to disable updating search indexes on a per-feed basis, which should resolve this.
