### ISSUE TITLE
Undefined offset: 1 - Users.php: 72

### ISSUE THREAD

**Issue by nicholashu** [craftcms/feed-me#844]
### Description

I am unable to add users to a user relation field in an entry

### Steps to reproduce

1. Create an entry with a user field that has Admin and a group as a source
2. Set that user field to email in feed-me when creating a new feed

### Additional info

The issue exists because 
`$sources = Hash::get($this->field, 'settings.sources');`
 on line 60 of `src/fields/Users.php`
 returns  `["admins","group:xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxx"]`
and so `list(, $uid) = explode(':', $source);`
is unable to set a $uid for "admins"
- Craft version: 3.6.13
- Plugins & versions: Feed-me 4.3.6

**Comment by i-just** [comment]
Hi, thanks for reporting! I just raised PRs to action this.

@tommysvr, thanks for reproducing and confirming the scope!

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1337 and https://github.com/craftcms/feed-me/pull/1338/ for the next v4 and v5 releases.

Thanks, @i-just and @tommysvr!
