### ISSUE TITLE
Youtube videos aren't

### ISSUE THREAD

**Issue by cookie10codes** [craftcms/feed-me#859]
### Description
We spoke about the mime type issue we encountered when entering the youtube through Feed Me to save in the Embedded Assets plugin. The issue for this was opened on their [issue tracker and got closed](https://github.com/spicywebau/craft-embedded-assets/issues/184).

We updated the [AssetHelper](https://github.com/craftcms/feed-me/blob/4.3.6/src/helpers/AssetHelper.php#L350) with the explode `$contentType = explode(';', $contentType[0]);` so the mime issue was solved.

Unfortunately, we still receive an error that the video isn't able to save. Embedded Assets saves a json file and stores information about the specific media (in this case, a Youtube).

The error:
<img width="1252" alt="Screenshot 2021-07-09 at 09 46 07" src="https://user-images.githubusercontent.com/20947573/125042775-866fee80-e09a-11eb-9006-c1d55f6030d7.png">

This is [the feed](https://feeds.educationendowmentfoundation.org.uk/?scope=news&page=0&key=4-3sRcpBn9bD-cZA-BxvhaUgQXps3h-y92fPymAtETZ786ZbYAUWhK9QzTEEi) that we are using. You can find, inside of the builder, a video block which is causing the bug to happen. (Make sure you don't set the pagination, it will import 36 items and in 4 or 5 cases you'll have the Youtube error)

### Steps to reproduce
It's erroring on each video block

### Additional info

- Craft version: Craft Pro 3.7.0-beta.5 (also got it on 3.6.17)
- PHP version: 8.0.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Embedded Assets: 2.7.0

**Comment by angrybrad** [comment]
You had mentioned this worked at one point - do you happen to recall the version of Feed Me you were using when it last worked?

**Comment by cookie10codes** [comment]
> You had mentioned this worked at one point - do you happen to recall the version of Feed Me you were using when it last worked?

If I recall correctly, it was "4.3.4"

**Comment by angrybrad** [comment]
I'm having a hard time seeing how this could have ever worked, tbh.

Currently, 3rd party field/element support in Feed Me is implemented on Feed Me's side:

https://github.com/craftcms/feed-me/tree/develop/src/fields
https://github.com/craftcms/feed-me/tree/develop/src/elements

And there's never been anything for Embedded Assets in Feed Me itself.  

If we take that plugin out of the equation, Feed Me natively does have some support for fetching remote images and creating assets for them (https://github.com/craftcms/feed-me/blob/develop/src/helpers/AssetHelper.php#L84-L131), but it's expecting an actual image to live at the URL and not a chunk of HTML like a YouTube link.

I went back to 4.3.4 with the feed you provided and got a PHP error just like on the latest.

I went back to 4.2.0 and didn't get a PHP error, but what Feed Me did was download the HTML for the YouTube page and create an asset from it with the filename as the last segment of the URL, which is what I'd expect.

I did fix the PHP error for the next release (https://github.com/craftcms/feed-me/commit/acfdca2cf5dd95a4982841f0c6f8c42fbf38c267) so the behavior will be consistent with how it behaved at 4.2.0 (although now you also have to allow .htm/.html in https://craftcms.com/docs/3.x/config/config-settings.html#allowedfileextensions which 4.2.0 was not respecting).
