### ISSUE TITLE
Craft 3.7 columnSuffix not included in SQL on import

### ISSUE THREAD

**Issue by mats852** [craftcms/feed-me#864]
### Description
https://craftcms.com/docs/3.x/extend/field-types.html#storing-content

While feeding data in my Craft project, I noticed that I was receiving this error

```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "field_someField" does not exist LINE 8: WHERE ("entries"."sectionId"=$2) AND ("field_someField")...
```

This field has now the `columnSuffix`, I had to delete it from the database data and structure to import the data.

### Steps to reproduce

1. Create a new field in Craft 3.7.x
2. Import an entry that has an Entry field, and that Entry field has a columnSuffix

### Additional info

- Craft version: 3.7.1
- PHP version: 7.4
- Database driver & version: PostgreSQL 11
- Plugins & versions: Feed-Me 4.3.6

**Comment by myleshyson** [comment]
Yea this makes feedme unusable for us at the moment with 3.7. Any update on this?

**Comment by sjeng** [comment]
Added PR for this issue. 
#867

**Comment by angrybrad** [comment]
I can kinda see how this might be happening, but I'm not able to setup a test case to reproduce it locally, unfortunately. Any chance either of you could send a database dump and composer.json file along with a sample feed to reproduce over to support@craftcms.com, so we can look into it further?

**Comment by lenvanessen** [comment]
@angrybrad it happens on trying to find relations trough a custom field. Eg you set:
![Schermafbeelding 2021-08-04 om 10 02 36](https://user-images.githubusercontent.com/23024452/128144884-43b15b6f-f010-4b83-a6bb-a0de2554fed0.png)

And it will mess up the search query for the specific entry

**Comment by angrybrad** [comment]
Feed Me 4.4.0 is out with a fix for this.
