### ISSUE TITLE
craft\feedme\base\Element::parseSlug() ignores allowUppercaseInSlug config

### ISSUE THREAD

**Issue by mats852** [craftcms/feed-me#865]
### Description

The class method craft\feedme\base\Element::parseSlug() ignores `allowUppercaseInSlug` configuration in the CMS.

On line 294, the `mb_strtolower` function call lowercases every slug:

https://github.com/craftcms/feed-me/blob/acfdca2cf5dd95a4982841f0c6f8c42fbf38c267/src/base/Element.php#L285-L301

But the method `_createSlug` calls StringHelper::toKebabCase with the proper configuration.

https://github.com/craftcms/feed-me/blob/acfdca2cf5dd95a4982841f0c6f8c42fbf38c267/src/base/Element.php#L331-L346

### Steps to reproduce

1. Feed a slug with an uppercase letter, even with the `allowUppercaseInSlug`

### Additional info

- Craft version: 3.7.1
- PHP version: 7.4
- Database driver & version: PostgreSQL 11
- Plugins & versions: Feed-me 4.3.6

**Comment by angrybrad** [comment]
Feed Me 4.4.0 is out with this fix.
